### ISSUE TITLE
Groupings are not saved

### ISSUE THREAD

**Issue by vetalball** [Ibericode/mailchimp-for-wordpress#100]
I think, that the bug is in the map_data_to_list [method](https://github.com/Ibericode/mailchimp-for-wordpress/blob/master/includes/class-field-mapper.php#L204)
 In that case you're trying to check variable $data, which was never initialized.
And if I add
```
 $data = $this->form_data; 
```
before that line - everything works fine

**Comment by dannyvankooten** [comment]
Hey @vetalball , nice catch, thanks for reporting this on GitHub!

We've just pushed out version 2.3.2 of the plugin, where this (among some other minor bugs) is fixed. 

https://wordpress.org/plugins/mailchimp-for-wp/changelog/

Hope that helps!

**Comment by vetalball** [comment]
Cool! Thank you for your prompt reply!
