### ISSUE TITLE
Admin notice: Zend_Exception: No object named "request" is registered.

### ISSUE THREAD

**Issue by arnevanhoorn** [ibericode/mailchimp-for-wordpress#103]
When submitting the form I get the following error:
Admin notice: Zend_Exception: No object named "request" is registered.

**Comment by iMazed** [comment]
Hi arnevanhoorn, this appears to be an issue coming from MailChimp. You can read our update here: https://mc4wp.com/blog/issue-with-mailchimp-api-zend-exception/
