### ISSUE TITLE
WooCommerce product review form: Checkbox should be above not below submit button

### ISSUE THREAD

**Issue by gerdneuman** [ibericode/mailchimp-for-wordpress#110]
I have the same problem as described in https://github.com/ibericode/mailchimp-for-wordpress/issues/82#issuecomment-103612954

For WooCommerce product reviews (which behave just like a comment but add the possibility to add a 1 to 5 star rating) the checkbox is below the submit button and it seems to be not a theming issue as WooCommerce is just calling WordPress' [comment_form](https://codex.wordpress.org/Function_Reference/comment_form) function 

Would be great if support for WooCommerce would be "more" complete and this "bug" be fixed. 

Thanks for an otherwise great plugin!

**Comment by dannyvankooten** [comment]
Hi @gerdneuman ,

We believe this is addresses in version 3.0 (and most likely in 2.3.x as well), can you confirm please?
