### ISSUE TITLE
Please consider adding author to class-general.php

### ISSUE THREAD

**Issue by vzeazy** [ibericode/mailchimp-for-wordpress#121]
Hi Guys,

I'm currently using a custom contact form in theme.
The name and id of the name element of the form is "author".

The class general form on line 156 checks the follow:
'name', 'yourname', 'username', 'fullname', 'contactname'

Consider adding author to this list as it is likely a fairly common use case as well.
'name', 'yourname', 'username', 'fullname', 'contactname', 'author' 

Hope it get's added to the code. All the best.

**Comment by dannyvankooten** [comment]
Hi @vzeazy,

That is a great suggestion, will add it to the list of field name tries!

**Comment by vzeazy** [comment]
Great to hear. Great plugin! :)
