### ISSUE TITLE
Potential to Place Response Messages Outside of Form

### ISSUE THREAD

**Issue by vzeazy** [ibericode/mailchimp-for-wordpress#131]
Hi Guys,

I've been implementing the form in a bunch of websites.

However, most of the time I'm using a bootstrap modal to display it.
Issue arises when page refreshes with a response message and user is not able to see it.

Tried to hack it with js, but didn't have much luck.

Is there any potential to add hook allowing to send response message to a pre-specified class.

Will be happy to help.

All the best.

**Comment by dannyvankooten** [comment]
Hi @vzeazy ,

I'm giving this some thought and wonder how far we should take this in the plugin itself - would a function to retrieve the form response for the current request suffice? 

I'm thinking something along the lines of two functions, one to check whether a form was submitted and another to get the response for the submitted form. This will allow you to re-open the modal and show the form response wherever you want.

_Example_
```php
if( mc4wp_form_is_submitted( $form_id ) ) {
   // open modal
   // ..

   // get form response
   $response = mc4wp_form_get_response( $form_id ); 
}
```

What do you think? :)

**Comment by vzeazy** [comment]
Yeah, that seems like a clean way to approach it. Would cover a variety of use cases.
Thanks for the quick response and great plugin. :)

**Comment by dannyvankooten** [comment]
Hey @vzeazy ,

Sorry for the wait but I've just added this to the release/2.3.8 branch. We're hoping to ship it later today or early tomorrow!

To implement the new functions, you can use the following code (this is for the free version, without form ID's).

```php
if( mc4wp_form_is_submitted() ) {
   // print JS to open modal
   // ..

   // get form response
   $response = mc4wp_form_get_response_html(); 

   // echo response wherever you want 
   echo $response;
}
```
