### ISSUE TITLE
Contact form 7, checkbox and single opt-in not triggering welcome message  

### ISSUE THREAD

**Issue by altonwebsites** [ibericode/mailchimp-for-wordpress#133]
Hi
As the title says, I'm using Contact form 7, mc4wp, and single opt-in (as requested by client). Checking the checkbox adds the email to the mailchimp list but no welcome message (final welcome email) is triggered. I'm using mc4wp's own form with the same list and the welcome message is sent just fine. HTML below for contact form. 

    <p>[text* your-name placeholder "Your name*" akismet:author] </p>
    <p>[email* your-email placeholder "Your email*" akismet:author_email]</p> 
    <p>[text your-telephone-number placeholder "Your telephone number"] </p> 
    <p>[text your-country placeholder "Your country"] </p>
    [response]
    <p>[textarea your-message placeholder "Your message"] </p>
    [mc4wp_checkbox "I would like to receive e-newsletters about special offers, featured work and news updates."] 
    <p class="page-contact-us-required">* required</p>
    <p>[submit "Send"]</p>

Options in mc4wp Checkbox menu: 
<img width="982" alt="screen shot 2015-07-22 at 11 55 26" src="https://cloud.githubusercontent.com/assets/10417228/8823877/7193652a-3068-11e5-8031-4178753c534b.png">

Thanks, Steve

**Comment by hchouhan** [comment]
Hello altonwebsites,

The welcome email is sent by MailChimp.com and not us. Have you setup your account so all new subscribers get the welcome email?

**Comment by altonwebsites** [comment]
Hi, thanks for the response. 
Yes I realise that. Here's what I'm experiencing: 

Double opt-in + mc4wp form = subscriber added to list & welcome email sent
Double opt-in + CF7 with [mc4wp_checkbox] = subscriber added to list & welcome email sent
Single opt-in + mc4wp form = subscriber added to list & welcome email sent
Single opt-in + CF7 with [mc4wp_checkbox] = subscriber added to list, NO welcome email sent

(CF7 is Contact Form 7)
Thanks, Steve

**Comment by hchouhan** [comment]
Hello Steve,

I found this http://kb.mailchimp.com/lists/signup-forms/enable-final-welcome-email. And it looks like the email is sent when someone clicks on the "Confirm email" link sent for verifying email. I might be wrong but the best person to confirm this is the Support Team of MailChimp.com. I'll keep this issue open until my colleague also checks into it.

**Comment by altonwebsites** [comment]
Hi Harish, 
Thanks for looking into this. I'd agree with you but the mc4wp form using single opt-in still sends out the final welcome email and doesn't require the user clicking the "confirm emial" link in the verification email
Thanks, Steve

**Comment by dannyvankooten** [comment]
Hi @altonwebsites ,

This is intended behaviour in the free 2.x branch of the plugin, the "send welcome email" option is only present in the Premium version of the plugin at this point.

We're working on version 3.0 of the plugin which will expose this functionality to both free and premium users, so it will become available even when on the free version of the plugin but it'll be at least a month before we're able to release that.

Please consider upgrading to the premium version of the plugin if you want a quick fix for this. It'll give you an option like this in the admin view.

![image](https://cloud.githubusercontent.com/assets/885856/8897728/7b6804d6-3444-11e5-88e3-40220f0076b7.png)

**Comment by altonwebsites** [comment]
Hi Danny, thanks for the response - been on holiday for two weeks hence the slow reply. I've now asked the client to consider upgrading. Will close this issue.
Steve
