### ISSUE TITLE
MC4WP and EDD - Form showing Twice on Checkout Page

### ISSUE THREAD

**Issue by growdev** [ibericode/mailchimp-for-wordpress#134]
MC4WP hooks into the `edd_purchase_form_user_info` action to add the subscribe checkbox on the EDD Checkout page. 

This action is called twice in EDD template:
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/checkout/template.php#L209

https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/checkout/template.php#L500

Which results in two checkboxes:

![checkout_-_shop_plugins](https://cloud.githubusercontent.com/assets/290886/8945491/79a3ca9a-354d-11e5-90b9-5c4296c42183.jpg)

Perhaps you could have a switch to use `edd_purchase_form_user_info_fields`, or `edd_purchase_form_user_register_fields` instead so there is only one checkbox?

**Comment by dannyvankooten** [comment]
@growdev You rock Daniel, great catch. Will fix!
