### ISSUE TITLE
`role="form"` isn't needed

### ISSUE THREAD

**Issue by XhmikosR** [ibericode/mailchimp-for-wordpress#135]
Hi.

`role="form"` isn't needed anymore and it results in a validation warning.

Just wanted to let you know.

Cheers.

**Comment by dannyvankooten** [comment]
Hi @XhmikosR ,

I'm now looking into this but do you have any resources stating that `role="form"` is no longer needed? I'm searching around for a bit now but most sites still state that it's useful for screen readers. Bootstrap and the likes are still using it, so it seems like using it couldn't hurt. 

Please prove me wrong, I might be missing something here.. :)

**Comment by XhmikosR** [comment]
Hey.

Check the PR for a link.

IIRC we have removed it in Bootstrap too a few months ago.

**Comment by dannyvankooten** [comment]
TIL. Awesome, thanks so much @XhmikosR !
