### ISSUE TITLE
Some text not getting translated

### ISSUE THREAD

**Issue by iMazed** [ibericode/mailchimp-for-wordpress#141]
Even when using a fully translated .po file, translations do not work out of the box. Language for, for example, error messages gets stuck on English. Confirmed with a fresh Dutch install, but will need further testing to make sure.

**Comment by dannyvankooten** [comment]
Are you sure this is on a fresh install and not on an install that had message settings saved already?

**Comment by dannyvankooten** [comment]
Never mind, caught it too! The plugin was caching the untranslated options (since options were loaded before translations). Fixed now! :+1:
