### ISSUE TITLE
Add option to automatically add form to posts

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/mailchimp-for-wordpress#147]
Eg using an autocomplete input field that allows the following values.
- All posts
- Posts in category X
- Posts with tag Y
- All pages
- "Hello world" (individual post title)
- "Sample page" (individual page title)

**Comment by arnelap** [comment]
You did it! At least the first 2. ;)
You can now "Append to posts" per category.
Close the issue or keep building?
