### ISSUE TITLE
Anti-CSRF Tokens / Nonces can be replayed

### ISSUE THREAD

**Issue by Varbaek** [ibericode/mailchimp-for-wordpress#151]
During a security review of a web application that integrates MailChimp, it was discovered that the MailChimp plugin for WordPress does not appear to reject the nonce aka. the Anti-CSRF tokens if they are replayed as shown in the request below. 

Can you please investigate and perhaps push an update to the WordPress repository, so that nonces/tokens are either: 
a) Only valid once; or
b) Valid for ~5 minutes, etc.

Alternatively, the WordPress nonces may work as well.

Request: 
POST /subscribe/ HTTP/1.1
Host: example-domain.tld
Accept: */*
Accept-Language: en
User-Agent: Mozilla/5.0
Connection: close
Referer: https://example-domain.tld/subscribe/
Content-Type: application/x-www-form-urlencoded
Content-Length: 161

mc_submit_type=html&mcsf_action=mc_submit_signup_form&mc_mv_EMAIL=name@email.tld&mc_signup_submit=Subscribe&_mc_submit_signup_form_nonce=d86fa89be6

**Comment by Varbaek** [comment]
An attacker can for example issue the above request a thousand times, where MailChimp sends out the emails on behalf of example-domain.tld.

If an attacker performs this type of attack against e.g. 1000 WordPress websites with MailChimp installed, it could have some security issues.

**Comment by dannyvankooten** [comment]
Hey @Varbaek,

Seems like a nice find but unfortunately (or rather: luckily) it doesn't seem to be our plugin that's vulnerable to this sort of attack. Using our plugin, the query parameters you post would have no effect at all.

This repository is for the following WordPress.org plugin: https://wordpress.org/plugins/mailchimp-for-wp/ . 

From the looks of it, you're talking about this one: https://wordpress.org/plugins/mailchimp/ . Please double check as I am not super sure about that, not very familiar with their code.

Anyway, hope that helps and thanks for helping out!
