### ISSUE TITLE
More detailed error message in case of cURL or firewall issues

### ISSUE THREAD

**Issue by iMazed** [ibericode/mailchimp-for-wordpress#153]
Right now the plugin gives an error message when a HTTP request cannot be made. The error message does not display any info that connects it to the MC4WP plugin, so it often gets dismissed by users as not a part of their issue. More details would also make it easier to debug for the support team.

![2015-09-01 08_30_58-mailchimp plugin license settings - mailchimp for wordpress lite increase yo](https://cloud.githubusercontent.com/assets/3907432/9597637/1b34d92a-5084-11e5-95a3-2d29f674f10d.png)

**Comment by dannyvankooten** [comment]
:+1:

**Comment by dannyvankooten** [comment]
It would be very neat if we could link to a dedicated article in our KB from the error message. [Trello card](https://trello.com/c/gkHudkH1/82-kb-article-on-http-errors)

**Comment by dannyvankooten** [comment]
Closed by e7d9e1c319d56a63938b6f3717f70e632d4fe39a
