### ISSUE TITLE
Autocomplete is filling honeypot field.

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/mailchimp-for-wordpress#166]
This might just be due to developers filling it once and AutoComplete then remembering it. However, if it is because AutoComplete thinks it is an `email` field that should be filled, we should do something that prevents this.

**Comment by dannyvankooten** [comment]
Apparently, `autocomplete="off"` is not yet fixing it (in Chrome at least). This needs looking into.

It could be that once autocompleted, autocomplete does not forget so `autocomplete="off"` only works for fields that have not yet been autocompleted before...

**Comment by cfaria** [comment]
Seems like this only happens in Chrome, as I've tested on Firefox and Opera and works like a charm.

**Comment by cfaria** [comment]
Ok, so I've put an id (**nocomplete**) to the field _mc4wp_required_but_not_really on /wp-content/plugins/mailchimp-for-wp-pro/includes/class-form.php ln 138:

```php
$hidden_fields = '<div style="position: absolute; left: -5000px;"><input type="text" id="nocomplete" name="_mc4wp_required_but_not_really" value="" tabindex="-1" autocomplete="off" /></div>';
```

I've made this little script to fire when I click a submit button, but of course is a bit dirty, and it works only with my code, but with this all forms are working ok:

```javascript
$(document).ready(function(){
  $('.btn').on('click',function(){
    $('#nocomplete').val('');
  });
});
```

Seems like we detected the problem. Now we need a proper solution.

**Comment by cfaria** [comment]
Ok, better to put a class instead of a unique id. So the code should be now this:

/wp-content/plugins/mailchimp-for-wp-pro/includes/class-form.php ln 138:
```php
$hidden_fields = '<div style="position: absolute; left: -5000px;"><input type="text" class="nocomplete" name="_mc4wp_required_but_not_really" value="" tabindex="-1" autocomplete="off" /></div>';
```

Somewhere (custom js or one of the forms)
```javascript
$(document).ready(function(){
  $('.btn').on('click',function(){
    $('.nocomplete').val('');
  });
});
```

**Comment by dannyvankooten** [comment]
Hey @cfaria , that sounds like the best workaround for now! It does decrease the anti-SPAM security a little bit for bots able to run JavaScript but is still better than removing the honeypot field altogether.

I'm on the move for a few days but will do some extensive research on this. Thanks for buying us some time!

**Comment by dannyvankooten** [comment]
Based on some reading, we have a few things to try.

- Use a value for the honetpot, so it is filled by default. This can be a space.
- try `autocomplete="false"`, this should work in Chrome..

**Comment by cfaria** [comment]
Hi Danny, I've seen this behaviour again on version 2.7.23.

I thought it was fixed but it does'nt. The input is filled up again so I need to fall back to my dirty solution.

I know I have to update to 2.7.26 (and later to 3.0) but I don't know if this issue will remain.

**Comment by dannyvankooten** [comment]
Hi @cfaria ,

Ugh, oh no. I'm pretty sure it will be gone on 3.x but can you please test against the `master` branch to confirm? Once you have time of course. I've seen no others coming across the same issue so we should be good..
