### ISSUE TITLE
Add-in filter to disable honeypot validation

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/mailchimp-for-wordpress#183]

**Comment by leecollings** [comment]
Is there any progress to this? I need to remove the inline styling that the honeypot is causing:

`<div style="display:none;"></div>`

What's the best way I can remove this honeypot input field?

**Comment by dannyvankooten** [comment]
Hi @leecollings,

Why do you want to remove this field? The inline styling is there so that the honeypot field never actually shows for humans, since that would mean people filling it & then being marked as spam.

**Comment by leecollings** [comment]
I want to remove the inlien styling because it's flagging up on every SEO check I perform. It would be better to use JS to add a class rather than apply inline styling, is this possible?

**Comment by dannyvankooten** [comment]
Hi @leecollings, thanks for clarifying.

It'd be hard to do that right now (not impossible) but more importantly: I really don't think it would make any practical difference at all. What problem do the SEO tools have with that one inline style? 

We're doing it like this because it's a one-time, non repetitive field and using a CSS rule or JS rule would mean that the field will show whenever someone has JS disabled or when the theme is using stricter CSS rules to override our CSS rule. The latter is unfortunately very common in WordPress themes. =/

**Comment by leecollings** [comment]
Hmm okay, I think I might need to try another Mailchimp plugin, sorry to say. If there's any update to this, or if there's a way to get rid of this honeypot field and elieviate the need for inline styling, I would probably be interested in looking back into this.

**Comment by dannyvankooten** [comment]
No worries @leecollings, sorry to hear but best of luck on your site(s).

**Comment by dannyvankooten** [comment]
PS. I'd love to hear which SEO checks are saying that inline styles are bad, could you share me a few?

**Comment by leecollings** [comment]
All of them.



Kind regards,



Lee Collings | Graphic Designer & Web Developer
m 07429 955847
e lee@leecollings.co | w www.leecollings.co

This email and any attachments to it may be confidential and are intended
solely for the use of the individual to whom it is addressed. Any views or
opinions expressed are solely those of the author and do not necessarily
represent those of Lee Collings Co Ltd. If you are not the intended
recipient of this email, you must neither take any action based upon its
contents, nor copy or show it to anyone. Please contact the sender if you
believe you have received this email in error.
