### ISSUE TITLE
Incompatibility with Visual Composer

### ISSUE THREAD

**Issue by cadaar** [ibericode/mailchimp-for-wordpress#186]
When both plugins are installed Malchimp for wordpress and Visual Composer, the latter stops working as supposed when editing a page.

**Comment by defries** [comment]
To be fair, most plugins stop working when Visual Composer is activated.

**Comment by cadaar** [comment]
Probably right, but still would be good to have them both working since we make constant use of Visual Composer functionality.

**Comment by dannyvankooten** [comment]
Hey @cadaar - can you shoot us an email on support@mc4wp.com. To be able to properly test this, we'll need to have a copy of Visual Composer or to take a look at the issue in your installation from up close. 

We're not a big fan of Visual Composer but you're right, definitely something we're eager to fix!
