### ISSUE TITLE
Onboarding: API key input field should be required

### ISSUE THREAD

**Issue by jphorn** [ibericode/mailchimp-for-wordpress#191]
Mailchimp API key input field at admin.php?page=mailchimp-for-wp should be required IMHO. Currently you're able to use Save Changes without inputting the API key.

**Comment by dannyvankooten** [comment]
Hey @jphorn ,

Thanks for the suggestion. We actually allow emptying the API key field as we found making the field required is a bit of a pain when you want to empty it later on (when working on a client's site, for example).

We have other validation mechanisms in place that take care of missing API key fields, so this is not likely something we'll address any time soon.

Thank you for thinking along though, I really appreciate it!
