### ISSUE TITLE
Need more info on Interest grouping

### ISSUE THREAD

**Issue by jphorn** [ibericode/mailchimp-for-wordpress#193]
Add more explanation to option 'Replace interest groups'. I'm a relative newbie to Mailchimp in general and a total newbie to this plugin and have really no clue whatsoever what this option is about. The info description is also really confusing and doesn't really help to be honest. Maybe add some `<abbr>` tags, links to more info (open in new tab/window!) and/or extra explanation, but right now this option doesn't make any sense to me at all.

![2015-11-18 17 57 41](https://cloud.githubusercontent.com/assets/478156/11247925/8e29f21c-8e1e-11e5-985b-90bb312b199e.png)

Possibly related: #46

**Comment by dannyvankooten** [comment]
That help text could definitely be more helpful. :+1: 

What about this?

![image](https://cloud.githubusercontent.com/assets/885856/11263470/810c2eca-8ebd-11e5-8d72-c2a4317a06e9.png)

Linking to [What does "Replace Groupings" mean?](https://mc4wp.com/kb/what-does-replace-groupings-mean/)
