### ISSUE TITLE
Warning when editing a form

### ISSUE THREAD

**Issue by chantalcoolsma** [ibericode/mailchimp-for-wordpress#196]
When I edit a form, I get a warning after the list checkbox:

Warning: in_array() expects parameter 2 to be array, null given in /srv/www/webpressed/htdocs/wp-content/plugins/mailchimp-for-wp/includes/forms/views/tabs/form-settings.php on line 23
> <MailChimp list name>

Any idea?

**Comment by dannyvankooten** [comment]
Thank you @chantalcoolsma - fixed it in that last commit and will push out an update for it later this week. Appreciate you opening an issue in the right place!

**Comment by chantalcoolsma** [comment]
You are welcome. When I selected the list and saved settings, it was normal. I guess it only happens when you don't have a list selected.
