### ISSUE TITLE
When hit 'preview this form' it creates a page draft entry.

### ISSUE THREAD

**Issue by apokyro** [ibericode/mailchimp-for-wordpress#200]
Hi,

I just want to mention that in the new version (3.0.1) when you hit 'preview this form' to view the created form it creates a page with status draft in the listing of pages.
This is not normal!

Best,
Apostolis

**Comment by dannyvankooten** [comment]
Hi @apokyro ,

Thanks for creating an issue! 

The page draft is actually intended behaviour, the draft is used as a placeholder to contain the form shortcode that is showing the preview. 

There are other ways to accomplish the same thing (like faking a page by modifying all of WordPress' request variables) but that's very error-prone and frankly, a lot more code for the same result.

We could delete the draft after each preview but that would greatly reduce the performance. Do you have a good argument for not creating the draft page at all? 

Let me know please!

**Comment by apokyro** [comment]
Hi @dannyvankooten ,

I understand that plugin creates an draft page for viewing purpose.
Maybe you have to think another method to display a preview e.g. inside a modal just like the preview of a theme.
You know better!

regards
