### ISSUE TITLE
Conflict with WP Editor plugin, can't edit form code.

### ISSUE THREAD

**Issue by Maidesign** [ibericode/mailchimp-for-wordpress#202]
![mailchimp](https://cloud.githubusercontent.com/assets/16012083/11390402/5d852f6a-937c-11e5-919d-b6f9017c9228.png)

Hello,
I've just upgraded the plugin Mailchimp for Wordpress to version 3.0, and now i can't edit the HTML code in Form Fields, it become gray in background, i tried with Google chrome and Firefox.
I have also a other wordpress blog, use the plugin Mailchimp for Wordpress lite version 2.3.14 and it work very good (i easily edit the HTML code).

Hope you can help me, thank you!
Mai

**Comment by dannyvankooten** [comment]
Hi Mai,

Could you show me the contents of your browser console? Most likely it is showing us some errors which will be very helpful in debugging this issue.

[Here's how to open the console in various browsers](http://webmasters.stackexchange.com/questions/8525/how-to-open-the-javascript-console-in-different-browsers).

If you want, you can send an email to support@mc4wp.com with a temporary admin account so I can take a look at the issue form up close. That would be super helpfulp. :)

Thanks in advance!

**Comment by Maidesign** [comment]
I opened the browser console, but there are nothing error.
I found a way to change the HTML code, i have to pause, stop the browser (when be loading), the background will not become the gray.
I've just sent to support@mc4wp.com and email with the login credentials.
![mailchimp](https://cloud.githubusercontent.com/assets/16012083/11390631/ad581a8c-937e-11e5-8ff4-bce53a2e2d43.png)

Thank you!

**Comment by Maidesign** [comment]
The problem is fixed, the plugin is conflict with WP Editor plugin.

Thank you so much Danny!

**Comment by dannyvankooten** [comment]
No worries, here to help. :smiley: I'm glad that fixed it!
