### ISSUE TITLE
Syntax Error on admin pages

### ISSUE THREAD

**Issue by widoz** [ibericode/mailchimp-for-wordpress#205]
Hi,

Got this syntax error on every admin page 

```javascript
load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,plupload&ver=4.3.1:2 Uncaught Error: Syntax error, unrecognized expression: /path/wp-admin/admin.php?page=mailchimp-for-wp-forms&view=edit-form&form_id=1717&tab=appearance
```

Removed all widgets, disabled and removed the plugin but the issue is still there. 

Not sure if it is a bug or something like that. 
Right now this issue put down my entire settings page. :/

**Comment by hchouhan** [comment]
@widoz, can you please email us at "support @ mc4wp.com". We would need some details to look into this.

**Comment by widoz** [comment]
@hchouhan exactly what I should write?

**Comment by dannyvankooten** [comment]
Hey @widoz ,

We've never seen this issue before so we would appreciate it if we could take a look from up close. If possible, could you email us with admin credentials? 

Thanks in advance!

**Comment by widoz** [comment]
Hi @dannyvankooten 

I can create a new site in my network and give you the access. Give me a little bit of time to create it.

**Comment by widoz** [comment]
Hi,

Sorry for the delay on this. Nevermind, seems the issue was caused by a settings class that use a js to split the tabs on settings pages.
