### ISSUE TITLE
Failed includes pulling down site after update?

### ISSUE THREAD

**Issue by PaulJFleming** [ibericode/mailchimp-for-wordpress#208]
Hi folks. I performed the update through my WP panel today and received the following error:

Warning: include(/home/xsaraj/public_html/tft23c.com/wp-content/plugins/mailchimp-for-wp/includes/admin/class-admin-texts.php): failed to open stream: No such file or directory in /home/xsaraj/public_html/tft23c.com/wp-content/plugins/mailchimp-for-wp/vendor/composer/ClassLoader52.php on line 186

Warning: include(): Failed opening '/home/xsaraj/public_html/tft23c.com/wp-content/plugins/mailchimp-for-wp/includes/admin/class-admin-texts.php' for inclusion (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/xsaraj/public_html/tft23c.com/wp-content/plugins/mailchimp-for-wp/vendor/composer/ClassLoader52.php on line 186

Fatal error: Class 'MC4WP_Admin_Texts' not found in /home/xsaraj/public_html/tft23c.com/wp-content/plugins/mailchimp-for-wp/includes/admin/class-admin.php on line 183

I've deleted the MC4wp plugin folder, reinstalled, repeat and rinse.....

Still brings the site down.
Wonder could you help as I love mc4wp as part of my automated process... :-)

Regs, Paul

**Comment by dannyvankooten** [comment]
Hi Paul,

That is weird, where are you downloading the update from? GitHub? WordPress.org?

**Comment by dannyvankooten** [comment]
It seems the download only completes partially and misses a certain file. Can you confirm that the `/includes/admin/class-admin-texts.php` file is not there?

Thanks!

**Comment by PaulJFleming** [comment]
Initially I simply updated through the plugin panel. Then it died.
I removed the plugins, then installed through plugin panel from WP
repository. Activated and it died.
Removed once more. Downloaded plugin from repository. Installed via upload
through plugin panel. Activated. It died.
Removed. Downloaded the zip from the github site you suggested in other
posts, uploaded through plugin panel, activated. It died.
Removed plugin once more.

I'm currently looking at the backup dates to try and restore the site to
how it was yesterday - as all was working like clockwork.
Will keep you advised on my progress.

**Comment by PaulJFleming** [comment]
Nope. I've just looked and it isn't there.

I've also restored from the backup, then checked and that file is missing,
and the errors read:
*Warning*: include(/home/xsaraj/public_html/
tft23c.com/wp-content/plugins/mailchimp-for-wp/includes/admin/class-admin-texts.php):
failed to open stream: No such file or directory in
*/home/xsaraj/public_html/tft23c.com/wp-content/plugins/mailchimp-for-wp/vendor/composer/ClassLoader52.php
<http://tft23c.com/wp-content/plugins/mailchimp-for-wp/vendor/composer/ClassLoader52.php>*on
line *186*

*Warning*: include(): Failed opening '/home/xsaraj/public_html/
tft23c.com/wp-content/plugins/mailchimp-for-wp/includes/admin/class-admin-texts.php'
for inclusion (include_path='.:/usr/lib/php:/usr/local/lib/php') in
*/home/xsaraj/public_html/tft23c.com/wp-content/plugins/mailchimp-for-wp/vendor/composer/ClassLoader52.php
<http://tft23c.com/wp-content/plugins/mailchimp-for-wp/vendor/composer/ClassLoader52.php>*
on
line *186*

*Fatal error*: Class 'MC4WP_Admin_Texts' not found in
*/home/xsaraj/public_html/tft23c.com/wp-content/plugins/mailchimp-for-wp/includes/admin/class-admin.php
<http://tft23c.com/wp-content/plugins/mailchimp-for-wp/includes/admin/class-admin.php>*
on
line *183*

Which is damned strange, as that backup is from 8 hours ago apparently -
shortly after it was all working fine? :-/

This is so strange....

**Comment by PaulJFleming** [comment]
Looked inside the zip file. That texts file is there. ? Some reason it's
not uploading......

Should I try manually uploading the missing file?

**Comment by PaulJFleming** [comment]
I have tried all manner of ways to upload that file into the right place.
Nope.
It says it is there in the ftp client, then just......vanishes.?????????????

I've tried through web upload panel and through filezilla. Both the same
result.

Seems just not to like that file! :-/

**Comment by PaulJFleming** [comment]
I have contacted my webhosts, Hostpresto, as the file just keeps vanishing.
I can create a blank version of class-admin-texts.php and it stays there in
the file list.
If I upload the correct one to overwrite it....it uploads and then promptly
vanishes.

Sorry if this is causing you a headache Danny. At this point I am wondering
what I am doing wrong.
I mean..... files just don't VANISH. So it must be me...... has to
be........

I sincerely doubt it is the plugin, otherwise you would be flooded with
squeals........

**Comment by PaulJFleming** [comment]
Hi Danny. Apparently, according to Hostpresto, their virus scanner
blacklisted the file. They have now whitelisted it, but on reinstall the
same issue has occurred.

General consensus from this - hosting issue as opposed to plugin issue. I'm
waiting for updates and will keep you advised.

**Comment by dannyvankooten** [comment]
Hi Paul,

Sorry for my absence but it's running a bit late where I am (Asia).

Appreciate the updates! Let me know if I can help somewhere..

**Comment by PaulJFleming** [comment]
Hi Danny,

Okay, everything is working again now. It seems that the host's server
anti-virus heuristics checked out the file and saw patterns it thought were
in keeping with malware or a trojan. In short, the file was automatically
quarantined, hence it disappearing from the directory no matter what I
tried.

They have since whitelisted the file, which means everything is working
once more.

Sorry if I caused you alarm, but nothing to do with the plugin itself. I
just thought I would give you this update in case anyone comes across a
similar issue in future and you can help them with this possibility in mind
:-D

Best regards & thanks for MC4WP :-)

Paul.

ps. I'm using MCSync too. Would love to hear more about the plans for
reverse synchronisation, so when a user unsubscribes, their status can be
changed in the local database so they are not re-added to the mailing list.
;-)
