### ISSUE TITLE
Cannot fill in email address details in email field in blog's front end?

### ISSUE THREAD

**Issue by bluepip** [ibericode/mailchimp-for-wordpress#209]
Cannot fill in email address details in email field in blog's front end?

**Comment by dannyvankooten** [comment]
Hi @bluepip ,

Do you have an URL where we can see this happening?

**Comment by bluepip** [comment]
Hi,

Yes it's http://thebodystore.us/blog/ 
It's on the MailChimp for WordPress - Top Bar

Thank you.
Date: Sun, 29 Nov 2015 21:01:57 -0800

**Comment by dannyvankooten** [comment]
Hi @bluepip ,

Your theme is setting the `color` for all input fields to `white`, rendering the text invisible to read. You can fix this by adding the following CSS to your theme its stylesheet.

```css
input.mctb-email {
    color: black !important;
}
```

Hope that helps. If not, let me know!

**Comment by bluepip** [comment]
Hi Danny,

Thank you for your help with that, it's much appreciated.

Best regards,
Lorna

Date: Mon, 30 Nov 2015 03:04:35 -0800
