### ISSUE TITLE
Improvements to Form Appearance settings

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/mailchimp-for-wordpress#212]
Currently, the form appearance tab is basically one setting (or a link to [the Styles Builder if using Premium](https://mc4wp.com/features/). It would be cool to rework this so the user can configure various settings after which the plugin will determine which stylesheet to load.

Let's use this issue to draft our ideas.

**Comment by dannyvankooten** [comment]
Possible improvement could be to present the user with the following settings.

#### Reset Form Elements
Values: `Yes / No`

Resets position, width & height of all form elements.

#### Color
Values: `#abcdef` (color picker)

Sets color of field:focus outline & submit button, much like the custom color theme in Premium.

#### Border

Values: `Diagonal Striped, ...`

Adds a pretty border using CSS3 techniques. See [snippets/forms/striped-diagonal-border.css](https://github.com/ibericode/mc4wp-snippets/blob/master/forms/striped-diagonal-border.css) for an example.

#### Styles Builder (Premium)

Allows setting custom styling per element. Adds to or overrides previously mentioned settings.

**Comment by tessakerrichwalker** [comment]
Question (apologies if wrong forum - this is my first post - you seem to have the most relevant content relating to my question) - it is possible to change the position of the text in the typeform fields? I'm not sure why (only) one of three fields I have squashes the text toward the left. I don't have Premium, but I don't think this would be a Premium feature

**Comment by dannyvankooten** [comment]
hi @tessakerrichwalker , do you have al ink to your site?

**Comment by tessakerrichwalker** [comment]
Thank you for the response! I don't have this version of the site live at the moment ... here is a screenshot. The third text box is the problem one.

<img width="631" alt="screen shot 2016-08-10 at 2 33 45 am" src="https://cloud.githubusercontent.com/assets/20952472/17593663/a946c634-5fb4-11e6-97cc-a01b74b2d8d4.png">
