### ISSUE TITLE
Styles Editor doesn't seem to be working

### ISSUE THREAD

**Issue by paulminors** [ibericode/mailchimp-for-wordpress#215]
I have just udpated to the new version of MC4WP and all my old forms (which use the styles editor) are no longer being styled by the editor. When I view the form in the styles editor the preview window shows the form as it should appear, but on the live site, the stylesheet isn't being pulled in and the form looks "naked".
![screenshot 2015-12-07 05 32 00](https://cloud.githubusercontent.com/assets/16178904/11614659/4b713aae-9cae-11e5-9ce9-401984ff7425.png)
![screenshot 2015-12-07 05 32 03](https://cloud.githubusercontent.com/assets/16178904/11614660/4b7192a6-9cae-11e5-95f7-b1cc1ecf72cb.png)
![screenshot 2015-12-07 05 33 57](https://cloud.githubusercontent.com/assets/16178904/11614661/4b73e862-9cae-11e5-8eb7-82b9163cf913.png)

**Comment by dannyvankooten** [comment]
Hi @paulminors ,

That is weird and definitely not supposed to happen, the upgrade routine should have taken care of this. Can you please go through the following steps to see if that fixes your issue?

1. Go to your form settings and ensure "Load Styles Builder styles" is selected in the **Appearance** tab.
2. Open the Styles Builder and click the "Build CSS" button to make sure the stylesheet file is created.

Thanks in advance!
