### ISSUE TITLE
Don't print_dummy_javascript when not necessary

### ISSUE THREAD

**Issue by kasparsd** [ibericode/mailchimp-for-wordpress#220]
`print_dummy_javascript()` in `MC4WP_Form_Asset_Manager` shouldn't be added to `<head>` by default, especially since there is no way of removing because `init_asset_manager()` stores the instance reference in a local variable in `MC4WP_Form_Manager`.

I noticed that only very recently (3.0.0 & 3.0.1 - November 23, 2015) you switched from binding to `document` to using a global `mc4wp`:

> Event binding: `jQuery(document).on('subscribe.mc4wp','.mc4wp-form', function(){ ... })` is now `mc4wp.forms.on('subscribed', function(form) { ... })`

I'm not sure why you decided to change it but using globals is not the right approach, I think.

**Comment by dannyvankooten** [comment]
Hey @kasparsd ,

Thanks for the input! 

The dummy JS is actually printed so people can register events from inside their forms without having the file containing the actual event binding loaded on every page, resulting in overall better page performance.

Why don't you want the dummy JS to be loaded and do you have an idea on how to tackle the event binding issue otherwise? 

Simply removing the dummy JS altogether would break a lot of sites, as people are usually adding JS snippets all over the place while we are lazy-loading our JS files.

Looking forward to your thoughts on this one. :)

**Comment by kasparsd** [comment]
Thanks for the explanation, @dannyvankooten.

I would assume that many sites use the default functionality of the plugin and therefore don't need to hook into `mn4wp.forms`. That is also my case where I use only the comments integration and that extra dummy JS is simply not needed.

Most JS scripts rely on global objects or other kind of standard data types for registering things before the actual library has been added. I imagine something like:

```
c4wp_forms = c4wp_forms || [];
c4wp_forms.push( { subscribed: function(form) {} } );
```

And then you would simply loop through the `c4wp_forms` array and register the events.

**Comment by kasparsd** [comment]
@dannyvankooten I have updated the #221 pull request to reflect the second suggestion.

**Comment by dannyvankooten** [comment]
Hi @kasparsd ,

I like your second suggestion, but the PR is not quite there yet. The `mc4wp_output_form` sometimes runs in a context where the the output is not echoed but returned as a variable, so that should be taken into account.

This happens when rendering a shortcode, for example. 

That said, it's definitely do-able. First thing I can think of is to start a separate output buffer that captures all output (so form HTML + any HTML outputted by the action callbacks) and returns that.

**Comment by dannyvankooten** [comment]
I'm taking a detailed look at this early next week or over the weekend by the way. :) Thanks for your suggestions & work so far, I really appreciate it!

Please don't feel obliged to put any more effort into this if you're not enjoying it. I'll make sure the JS isn't unnecessarily printed in the next release. :wink:

**Comment by kasparsd** [comment]
> Please don't feel obliged to put any more effort into this if you're not enjoying it.

@dannyvankooten I don't mind at all :) I really appreciate your work and the quality of it which is why I use it on my personal site and don't mind contributing back.

Secondly, this is a really interesting problem to solve, since compatibility with various themes and plugins is a huge issue (because they do all kinds of crazy things), and printing the _dummy_ JS in the header is probably the most reliable and painless method of dealing with it.

**Comment by dannyvankooten** [comment]
Hey @kasparsd ,

A new output buffer is now started just before the `mc4wp_output_form` action runs which captures all output attached to that action.

Then, as per your PR, the inline JavaScript is only printed whenever a form is printed on the page (only for the first form).

On top of that, the code is now loaded from a JS file of its own so it can be easily minified using task runners which allows us to print the minified version whenever `SCRIPT_DEBUG` is not enabled.

Appreciate your help on this one - pretty happy with the solution as it stands now. Let me know if you have any further suggestions. :)

**Comment by kasparsd** [comment]
@dannyvankooten Yeah, looks better now.

I'm wondering why you decided to `include` the JS file instead using `src`:

```
printf(
	'<script type="text/javascript" src="%s"></script>',
	MC4WP_PLUGIN_URL . "assets/js/forms-dummy-api{$this->filename_suffix}.js"
);
```

or even better -- registering it very early with `wp_register_script()` in `load_stylesheets()` and then calling `wp_print_scripts()`.

The current setup still doesn't allow users to disable the output of `print_dummy_javascript()`.

**Comment by dannyvankooten** [comment]
@kasparsd The minified file is 135 bytes, which is far too little to make up for the additional HTTP request (which comes with the cost of latency etc.). 

As the object is overridden later on, I'm not sure why anyone would want to disable the dummy JS. Have an example of why anyone would want to do this?

**Comment by kasparsd** [comment]
@dannyvankooten That is a good point. That extra HTTP request would happen for the very first request until it's stored and returned from the browser cache (if proper headers are sent) for all subsequent requests. However, the 135 bytes of inline JS is harmless, indeed.

I prefer to keep the HTML output really clean and avoid including any JS or other assets that are not used anywhere on the site. The [Minit plugin](https://github.com/kasparsd/minit), for example, can work only with assets that are added using the standard WP methods.
