### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by G4Zz0L1** [ibericode/mailchimp-for-wordpress#223]
Hi!

I'm trying to configure a wordpress of a friend of mine that have switched hosting service, and this installation gives this error:

Error connecting to MailChimp: error:14077458:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 unrecognized name.

This folder has worked on another server so i think it's a server configuration, but I don't know which one. SSL and curl configuration are ok, and I've found nothing related on the internet. Have you any ideas?

**Comment by dannyvankooten** [comment]
Hi,

Looking at the error message, I am pretty sure this is related to either CURL or OpenSSL. Which versions do you have installed of those?

I recommend running CURL 7.34+ and OpenSSL 1.0.1f or later (everything before that is vulnerable to the Heartbleed injection anyway).

Not sure how tech-savvy you are but this should really be matter of minutes for your host. :)

Hope that helps,!

**Comment by G4Zz0L1** [comment]
These are the two versions:

curl 7.42.1 (x86_64-suse-linux-gnu) libcurl/7.32.0 OpenSSL/1.0.1e zlib/1.2.8 libidn/1.25 libssh2/1.4.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP Metalink

OpenSSL 1.0.1k 8 Jan 2015 (Library: OpenSSL 1.0.1e 11 Feb 2013)
built on: 2013-09-27 11:30:59.000000000 +0000
platform: linux-x86_64
options:  bn(64,64) rc4(16x,int) des(idx,cisc,16,int) blowfish(idx) 
compiler: gcc -fPIC -DOPENSSL_PIC -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -m64 -DL_ENDIAN -DTERMIO -O3 -Wall -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -std=gnu99 -Wa,--noexecstack -fomit-frame-pointer -DTERMIO -DPURIFY -DSSL_FORBID_ENULL -D_GNU_SOURCE -Wall -fstack-protector -Wa,--noexecstack  -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM
OPENSSLDIR: "/etc/ssl"

**Comment by dannyvankooten** [comment]
Hi @G4Zz0L1 ,

Thanks, that's very helpful! 

From the looks of it, CURL is using OpenSSL 1.0.1e and a quick Google search for the error message indicates that this is indeed an issue with OpenSSL. I'm fairly certain that updating either `php-curl` and `openssl` will get rid of this issue. 

In any case, it shouldn't be an issue in the plugin itself as it uses the default `WP_HTTP` API.

**Comment by G4Zz0L1** [comment]
I've updated php-curl, curl, openssl and anything related, without any results. I know it's not plugin fault, but I don't know what to do, so I tried here for any possible response. Thanks anyway, and if you have any other ideas I can try, let me know...

**Comment by dannyvankooten** [comment]
Hey @G4Zz0L1 ,

Ugh, sorry to hear that. There is one more thing you could try, as I filed a related bug for this in WP 4.4 the solution for that might fix this as well.

https://core.trac.wordpress.org/ticket/34935#comment:10

**Comment by G4Zz0L1** [comment]
I tried to replace the ca-bundle.crt, but it doesn't seems to make any difference. The plugin still returns that error. Thanks anyway.

**Comment by dannyvankooten** [comment]
Maybe not the desired solution but as we're hitting a dead-end otherwise: what about disabling CURL as an HTTP Transport? A plugin like [Core Control](https://wordpress.org/plugins/core-control/) allows you to do that from their UI.
