### ISSUE TITLE
Array error

### ISSUE THREAD

**Issue by andreasw13** [ibericode/mailchimp-for-wordpress#225]
I am trying to update the form to enable a list I made but it keeps making this error when I try to save the settings.

**Comment by andreasw13** [comment]
Warning: array_merge() [function.array-merge]: Argument #1 is not an array in /var/www/diningministry.com/public_html/wp-content/plugins/mailchimp-for-wp/includes/forms/class-admin.php on line 175

Warning: Cannot modify header information - headers already sent by (output started at /var/www/diningministry.com/public_html/wp-content/plugins/mailchimp-for-wp/includes/forms/class-admin.php:175) in /var/www/diningministry.com/public_html/wp-includes/pluggable.php on line 1228

**Comment by dannyvankooten** [comment]
Hey @andreasw13 - good catch! We've just pushed out version 3.0.9 of the plugin in which this should be fixed. Thank you for the heads up!
