### ISSUE TITLE
W3C issue from autofill attribute

### ISSUE THREAD

**Issue by thonysmith** [ibericode/mailchimp-for-wordpress#227]
I'm working on a WordPress theme and this autofill attribute make the theme invalidated on W3C:
http://demo.thimpress.com/eduma/

It's easy to modify the plugin myself but it's would be convenience to have it fixed on the plugin itself.

**Comment by XhmikosR** [comment]
:+1: for this to be fixed since it's a regression in the 2 or 3 releases. I was about to report it myself.

/CC @dannyvankooten

**Comment by dannyvankooten** [comment]
Thanks @thonysmith @caydenberg @XhmikosR , pushing out an update for this in early January!
