### ISSUE TITLE
Add WP-Pro-Quiz Integration

### ISSUE THREAD

**Issue by christinate** [ibericode/mailchimp-for-wordpress#229]
Capture any "Email" custom field into a specified list.

THANK YOU!

**Comment by dannyvankooten** [comment]
Hey @christinate, I'll take a look to see if it's possible. Thank you for the suggestion!

https://wordpress.org/plugins/wp-pro-quiz/

**Comment by arnelap** [comment]
wp-pro-quiz hasn’t been updated in over 2 years, so I will close this ticket. 
For any custom integration, this should normally work: https://kb.mc4wp.com/add-sign-checkbox-custom-form/

It it doesn't, please ask for support here: please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp

Hope that helps. If you have any questions, please let us know!
