### ISSUE TITLE
Cant get radio button fields or checkbox fields to work in the plugin

### ISSUE THREAD

**Issue by YachtingsBest** [ibericode/mailchimp-for-wordpress#241]
I can't get radio button fields from mailchimp or checkboxes to work in the plugin unfortunately.  Can you advise please!

**Comment by dannyvankooten** [comment]
HI @YachtingsBest ,

What exactly isn't working? Do you have a link to your site so I can take a look?

**Comment by YachtingsBest** [comment]
Hi Danny, thanks for the quick reply, here's the url - http://www.yachtingsbest.com/icebreaker-draw/

Heres what our form looks like in mailchimp - http://prntscr.com/9t7l96

And here's what the form fields have for code:
`
<p>
    <label>Email Address</label>
    <input type="email" name="EMAIL" placeholder="Your email address" required>
</p>
<p>
    <label>First Name</label>
    <input type="text" name="FNAME" placeholder="Your First Name">
</p>
<p>
    <label>Last Name</label>
    <input type="text" name="LNAME" placeholder="Your Last Name">
</p>
<p>
    <label>Men's or Women's Base Layer Draw?</label>
    <label>
        <input name="MMERGE3" type="radio" value="Men's"><span>Men's</span>
    </label>
    <label>
        <input name="MMERGE3" type="radio" value="Women's"><span>Women's</span>
    </label>
</p>
<p>
    <label>Updates</label>
    <label>
        <input name="GROUPINGS[21473][]" type="checkbox" value="59673"><span>Yes! Sign me up for Icebreaker Updates</span>
    </label>
    <label>
        <input name="GROUPINGS[21473][]" type="checkbox" value="59681"><span>Yes! Sign me up for yachtingsbest.com Updates!</span>
    </label>
</p>
`

**Comment by dannyvankooten** [comment]
Hi @YachtingsBest ,

It looks like your theme is printing some styles that hide all `<label>` elements. As the checkboxes and radio inputs are wrapped in a `<label>` element, they are hidden from view as well.

It would be best to add the following line of code to your theme its Custom CSS setting.

```css
.hidden { display: none; }
```

Then, you can modify your form mark-up and hide labels selectively by adding `class="hidden"` to the fields you want to hide.

```html
<p>
    <label class="hidden">Email Address</label>
    <input type="email" name="EMAIL" placeholder="Your email address" required>
</p>
<p>
    <label class="hidden">First Name</label>
    <input type="text" name="FNAME" placeholder="Your First Name">
</p>
<p>
    <label class="hidden">Last Name</label>
    <input type="text" name="LNAME" placeholder="Your Last Name">
</p>
<p>
    <label>Men's or Women's Base Layer Draw?</label>
    <label>
        <input name="MMERGE3" type="radio" value="Men's"><span>Men's</span>
    </label>
    <label>
        <input name="MMERGE3" type="radio" value="Women's"><span>Women's</span>
    </label>
</p>
<p>
    <label>Updates</label>
    <label>
        <input name="GROUPINGS[21473][]" type="checkbox" value="59673"><span>Yes! Sign me up for Icebreaker Updates</span>
    </label>
    <label>
        <input name="GROUPINGS[21473][]" type="checkbox" value="59681"><span>Yes! Sign me up for yachtingsbest.com Updates!</span>
    </label>
</p>
```

**Comment by YachtingsBest** [comment]
Thanks for the response Danny.  Apologies that its a theme thing.  I still can't get it to work. If you have any advice great, but I realize if its about outside your scope for support.  Thanks!

j.
