### ISSUE TITLE
MC4WP plugin breaks Site

### ISSUE THREAD

**Issue by camclay** [ibericode/mailchimp-for-wordpress#243]
Hello,

I went and installed the Mailchimp and MC4WP Premium plugins this morning, and it breaks the site with a 500 Error on the backend. Front end is fine and doesn't affect users. To resolve I removed every plugin I had and individually reactivated each one. Traced it to MC4WP. 

All plugins are site are current, attached is a screenshot of my plugins folder. MC4WP is not in there, as I had to remove it to a backup folder, to gain access to the dashboard the second time. I can put the plugin back in the folder but if it is enabled it will break.

Is there anyway to get an older version of the plugin in the meantime?

Thanks,
Cam
![installedplugins](https://cloud.githubusercontent.com/assets/8294484/12582266/0807d13c-c40a-11e5-8a84-f96ba8082412.PNG)

**Comment by dannyvankooten** [comment]
Hi Camclay,

This is an issue we actually fixed just a few minutes ago, if you re-download the plugin from our site you should be good to go. I'm pushing out an update (version 3.0.1) as we speak!

**Comment by camclay** [comment]
Excellent,
Thank you so much!
