### ISSUE TITLE
Groups do not appear

### ISSUE THREAD

**Issue by deepliving** [ibericode/mailchimp-for-wordpress#248]
HI, I have MailChimp for WordPress - Premium.  When I create a form, my MC group fields appear in the top box of 'form fields'.

When I select a group there, I get a pop-up box with 'Initial value' defaulting to all my group descriptions, comma delimited.

Regardless of whether I leave that as is, or remove the names of the sub-groups I don't want, the plugin only puts the group name (and no group for a user to select) when it displays the form.  What am I missing?  

Example:  http://www.deepliving.com/resources/mentoring: in Mailchimp, 'Public mentoring calls' have various call dates as groups, yet none show here.

How do I get the plugin to show the (sub)groups for a group, so a user can select the ones they want? (this worked in previous versions of the plugin).

On a side note, can I delete the 'MailChimp for WordPress Pro' plugin as it seems to have been superseded with the 'Premium' plugin?

Thanks
Bennie

http://www.deepliving.com/

**Comment by dannyvankooten** [comment]
Hi @deepliving ,

I'm closing this as per our email conversation (your group type was "hidden" in MailChimp). If you're still having issues with this, please just let me know. :-)

**Comment by deepliving** [comment]
All good thx Danny!
