### ISSUE TITLE
Updated to latest 3.1.1 and submit form issues

### ISSUE THREAD

**Issue by wogboy101** [ibericode/mailchimp-for-wordpress#249]
Hi.
I have MailChimp for WordPress 3.1.1 and MailChimp for WordPress - Premium 3.1.
Today have updated the Mailchimp for Wordpress plugin to latest version and ever since the update, the Mailchimp Form has stopped working. Form was working fine before update. 
Without changing anything in the form, when trying to submit the form, it triggers the action: **Required field missing**. And form does not go forward.
What has changed to have this happen?
http://www.getprimal.com.au/get-started/

[Form Code.txt](https://github.com/ibericode/mailchimp-for-wordpress/files/121168/Form.Code.txt)

**Comment by dannyvankooten** [comment]
Hi @wogboy101 ,

Which version were you coming from? Can you please try changing the form code to the following?

```html
<p>
    <label>*First Name:</label>
    <input required="required" placeholder="Your first name" name="FNAME" type="text">
</p>
<p>
    <label>Last Name:</label>
    <input placeholder="Your last name" name="LNAME" type="text">
</p>
<p>
    <label>*Email Address:</label>
    <input required="required" placeholder="Your email address" name="EMAIL" type="email">
</p>
<p>
    <label>*Gender:</label>
    <label>
        <input required="required" value="Male" name="GENDER" type="radio"><span>Male </span>
    </label>
    <label>
        <input required="required" value="Female" name="GENDER" type="radio"><span>Female </span>
    </label>
</p>
<p>
    <label>*How Did You Hear About Us?:</label>
    <label>
        <input required="required" value="Google Search" name="HEAR" type="radio"><span>Google Search </span>
    </label>
    <label>
        <input required="required" value="Facebook" name="HEAR" type="radio"><span>Facebook </span>
    </label>
    <label>
        <input required="required" value="Friend" name="HEAR" type="radio"><span>Friend </span>
    </label>
    <label>
        <input required="required" value="Sign" name="HEAR" type="radio"><span>Sign </span>
    </label>
    <label>
        <input required="required" value="Other" name="HEAR" type="radio"><span>Other </span>
    </label>
</p>
<p>
    <label>*Register To Which List?:</label>
    <label>
        <input type="radio" name="_mc4wp_lists[]" value="2e130dd727" /><span>Primal Performance & Fitness </span>
    </label>
    <label>
        <input type="radio" name="_mc4wp_lists[]" value="dea9dc9619" /><span>Primal Krav Maga & Self-Defence </span>
    </label>
</p>
<p>
    <input value="Register!" type="submit">
</p>
```

**Comment by wogboy101** [comment]
Fantastic Danny. That's done it. Thank you very much for your help. The original code was working previously, but your removal of the required field for the mailchimp lists section worked.

Looking over the change logs for this issue, I believe it was the update to version 3.1, in particular the:

- "Make sure integrations have a MailChimp list selected before trying to subscribe."
- "When a field is required in MailChimp, it has to be required in forms as well now."

I guess with my original code, both lists were "requiring" an input, but having radio buttons, I only wanted one list.
Appreciate the prompt reply as well.

**Comment by dannyvankooten** [comment]
Awesome @wogboy101 , thanks for letting me know! I've created #252 so this doesn't happen again for others, sorry it had to be you this time. :smile:

**Comment by wogboy101** [comment]
No problems, fast turnaround. Love your work. And thanks.
