### ISSUE TITLE
Override Jetpack Comment Subscription

### ISSUE THREAD

**Issue by defries** [ibericode/mailchimp-for-wordpress#257]
When using the Jetpack Comments module the MC4WP Comment Form integration isn't actually displayed. In fact, it should probably replace the Subscribe to Blog checkbox but that might be worth another ticket.

**Comment by dannyvankooten** [comment]
This is impossible as Jetpack processes the comments on `wordpress.com` and doesn't provide any way for us to hook into that process or access the provided data. Sorry. :(

**Comment by defries** [comment]
There's got to be a way. Perhaps the Jetpackers are willing to include a
filter. They've been helpfull like that before. Will investigate.

**Comment by defries** [comment]
There is a way: https://jetpack.com/2013/05/01/remove-comments-carousel/

**Comment by hchouhan** [comment]
@defries That code is to disable comments. What we would need to make this integration work is to be able to hook into the JetPack comment submission process.

**Comment by defries** [comment]
Ah, you're right. I don't know what I was thinking there. Never mind. Carry on ;)
