### ISSUE TITLE
{response} doesn't determine position of response message

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/mailchimp-for-wordpress#263]
But it gets stripped off?

**Comment by dannyvankooten** [comment]
I can't seem to replicate this right now. `{response}` is correctly replaced with form response, with and without AJAX enabled.

**Comment by hchouhan** [comment]
Can we have this same behaviour when the form is used within a widget?

**Comment by dannyvankooten** [comment]
w.org support topic: https://wordpress.org/support/topic/change-position-of-success-and-error-messages?replies=5#post-8109099

**Comment by dannyvankooten** [comment]
I'm closing this as I think this is resolved?
