### ISSUE TITLE
Add {post} variable, to be used in form mark-up

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/mailchimp-for-wordpress#268]
Example:

```html
{post property="ID"}
```

Much like the `{user}` variable.

**Comment by arnelap** [comment]
i imagine another button above the form editor with "hidden fields". It could be used to add post ID, slug and other cool stuff. Only make post ID available in free version. Gray out the other choices and if you click them get a msg: only available in premium. 

We could even at some point add the group selection thing here.
