### ISSUE TITLE
Form without [State] completed on address field won't submit

### ISSUE THREAD

**Issue by GrahamBruno** [ibericode/mailchimp-for-wordpress#270]
I am trying to set up a form with a mailchimp address field.

The majority of users I anticipate using this form will be from the United Kingdom.

I am looking to set [addr1], [city] and [zip] as required fields but have [state] be optional.

The form is laid out as follows...

Address Line 1          ([addr1])
Address Line 2          ([city])
Address Line 3          ([State])
Postal Code              ([Zip])

Unfortunately, when I try to submit an address with everything filled in except Address Line 3 (i.e. [State]) I receive an Ooops... something wen't wrong message. My temporary workaround has been to prefill this with the value "Scotland" which is where I am expecting the majority of sign ups to come from.

Please could you try setting up a form with an address field where the [State] field is optional, try not filling it in and submitting the form to see if you also experience the same issue?

Many thanks in advance for your time.

**Comment by hchouhan** [comment]
Hello Graham,

Can you please email us at support@mc4wp.com so we can discuss this further?

**Comment by GrahamBruno** [comment]
Hi there,

Thank you for getting in contact. I can advise that I have managed to resolve the issue myself. The problem was that the Address field was set as compulsory in Mailchimp. Once it was set to optional there I set the relevant event fields [addr1], [city] and [zip] as compulsory within your plugin things then behaved as expected.

Kind Regards.

**Comment by GrahamBruno** [comment]
Hi there,

Apologies, I spoke too soon. It turns out that even after designating the Address field as being optional in the mailchimp settings I have found that not filling in [State] causes the address not be saved to mailchimp. I will email directly to discuss further.

**Comment by GrahamBruno** [comment]
Discussed with Arne from your support team. The mailchimp address field does not seem to cope well at all with addresses outside of the United States which is outside of your plugin's control. Agreed to implement addresses as separate fields in mailchimp.
