### ISSUE TITLE
Top header menu targets disabled when Mailchimp Top bar is dismissed

### ISSUE THREAD

**Issue by tmiguens** [ibericode/mailchimp-for-wordpress#274]
After dismissing the mail chimp top bar, the targets in top header menu are not clickable. Reopening mail chimp top bar restores them. URL is http://kuzziimotorsports.com. Mobile and desktop.
<img width="729" alt="screenshot 2016-03-16 22 07 59" src="https://cloud.githubusercontent.com/assets/16284537/13836124/a1f64658-ebc3-11e5-9fda-72d8d783dc5b.png">
<img width="462" alt="screenshot 2016-03-16 22 08 08" src="https://cloud.githubusercontent.com/assets/16284537/13836127/a9729af8-ebc3-11e5-8082-814114f0afce.png">

**Comment by arnelap** [comment]
I see #mailchimp-top-bar has inline style min-height as cause.
