### ISSUE TITLE
Alert/Success is showing in blog post when page loads

### ISSUE THREAD

**Issue by asafpriel** [ibericode/mailchimp-for-wordpress#279]
I use the form shortcode in pages and posts - for pages all is good. For posts, the form is showing with the alert (mc4wp-alert mc4wp-success).

**Comment by dannyvankooten** [comment]
Hi @asafpriel - do you have a link to your site so we can see this happening?

**Comment by asafpriel** [comment]
Hi Danny,

Thank you for getting back to me.

Here is the link of the post and the link for a page that it’s working just fine:

Post: https://gochange.co/blog/thanks-man-youre-man/ <https://gochange.co/blog/thanks-man-youre-man/>
Page: https://gochange.co/ <https://gochange.co/> or https://gochange.co/about/ <https://gochange.co/about/>

Best,
Assaf

On 30 Mar 2016, at 18:22, Danny van Kooten <notifications@github.com> wrote:

Hi @asafpriel <https://github.com/asafpriel> - do you have a link to your site so we can see this happening?

**Comment by asafpriel** [comment]
Hi Danny,

Can you please help with that?

Thanks,
Assaf

On 30 Mar 2016, at 19:19, Assaf Priel <asafpriel@gmail.com> wrote:

Hi Danny,

Thank you for getting back to me.

Here is the link of the post and the link for a page that it’s working just fine:

Post: https://gochange.co/blog/thanks-man-youre-man/ <https://gochange.co/blog/thanks-man-youre-man/>
Page: https://gochange.co/ <https://gochange.co/> or https://gochange.co/about/ <https://gochange.co/about/>

Best,
Assaf

On 30 Mar 2016, at 18:22, Danny van Kooten <notifications@github.com <mailto:notifications@github.com>> wrote:

Hi @asafpriel <https://github.com/asafpriel> - do you have a link to your site so we can see this happening?

**Comment by asafpriel** [comment]
Hi Danny,

Did you have time to take a look at the links I send?

Here it is again - please look at the bottom for the form and the error messages that always appear:
https://gochange.co/blog/thanks-man-youre-man/

Thanks,
Assaf

**Comment by dannyvankooten** [comment]
Hi Assaf,

I'm sorry for the terribly late reply, I've been a bit busy in the past few weeks.

What does your form code (on **MailChimp for WP > Forms > Your form**) looks like? 

In e8ad0347011050a9d87ad053e38fe54e568634d2 I made some changes to the logic that renders the form response, could you give [downloading the latest version from GitHub](https://github.com/ibericode/mailchimp-for-wordpress/archive/master.zip) a try to see if that fixes the issue?

Thanks in advance!

**Comment by asafpriel** [comment]
Thanks Danny. I'll try it.
