### ISSUE TITLE
Improved WPML integration.

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/mailchimp-for-wordpress#280]
Right now, we very carefully tell people to use our Premium add-on to create multiple forms (one form for each language) as this way, they get to use our "edit form" interface for creating the translated version of a form, which is a huge UX win over using WPML String Translator.

However, if we go this route then we might as well offer built-in WPML integration where they can switch between languages on the "Edit Form" page instead of creating a separate form for each language.

On the forms page, this will look like one single form but users can create a translated version of that form which will then be automatically shown when showing the original form in a shortcode or widget.

**Comment by dannyvankooten** [comment]
Taking this route, we might as well keep on offering the WPML String Translator functionality to users on the free version of the plugin.

**Comment by amitkvint** [comment]
@dannyvankooten we can help here. We can also think of a dedicated solution for users in which there's some 'bridge UI' using ST at the bg. If you'd like to discuss this together let me know please.

**Comment by amitkvint** [comment]
we already are doing that for GravityForms users - I can show you quickly if you want :)

**Comment by tremblayly** [comment]
I'm interested in this...so will be following the results.

**Comment by srdjan-jcc** [comment]
@dannyvankooten I see this issue is still present.
`add_action( 'plugins_loaded', '_mc4wp_bootstrap_integrations', 100 );`
Are there some reasons why you cannot use that hook?

**Comment by ugurterzi** [comment]
Users still unable to translate forms via WPML string translation. Is there any progress?

**Comment by dannyvankooten** [comment]
@ugurterzi https://www.google.nl/search?q=mailchimp-for-wp+wpml&oq=mailchimp-for-wp+wpml&aqs=chrome..69i57.3023j0j7&sourceid=chrome&ie=UTF-8
