### ISSUE TITLE
Mailchimp Integration Issue

### ISSUE THREAD

**Issue by christinakfrei** [ibericode/mailchimp-for-wordpress#286]
Hi there! I'm using Mailchimp for wordpress and it's been great. 

I created a "content upgrade" Merge Tag on Mailchimp, and then put that tag in the Mailchimp for Wordpress form, so that now I can see exactly who on my email list signs up for that content upgrade. Way cool. 

Now I want to create ANOTHER content upgrade and create a special signup form for THAT. But every time I go to Mailchimp for Wordpress / Forms, all I see is the original form for that particular email list. 

Can you create more than one form for a particular email list? In this case, my email list is called "The Good Bits".  I want all these forms to drive traffic to "The Good Bits" list. 

Please tell me I can create another form. AND how to do it. I've searched high and low for help on this. 

Much obliged.  

Christina

**Comment by hchouhan** [comment]
Hey Christina,

The ability to create multiple forms is provided in our Premium version. If you are interested in this please check out https://mc4wp.com/ for pricing and other features. We have a "30 days no questions asked" refund policy. So if you do not find it useful you can ask for a refund.
