### ISSUE TITLE
"Open in new window" Checkbox Doesn't Work for Link to Email Address

### ISSUE THREAD

**Issue by humbyrds777** [ibericode/mailchimp-for-wordpress#287]
I have created a General Form with MailChimp and have linked to it through a "Contact Us" page on my website. On the form, I have my email address as a link so that it will open a new email when selected. Under Advanced Options, I have the box checked to "Open in a new window", and I have tried unchecking it as well: It does not open in a new window (opens in the same window). Here is a link to the page/form on my site:

<a href="http://wirewrappedjewels.us10.list-manage.com/subscribe?u=a72315e840f1a1d86170f6778&id=d75e656c91">http://wirewrappedjewels.us10.list-manage.com/subscribe?u=a72315e840f1a1d86170f6778&id=d75e656c91</a>

**Comment by dannyvankooten** [comment]
Hi @humbyrds777 ,

That issue seems to be related to MailChimp itself, not to our MailChimp plugin for WordPress (we are not MailChimp). Your best bet would be to contact MailChimp support.

Sorry but good luck!

**Comment by humbyrds777** [comment]
Danny, I wish you would leave this open because my issue is not resolved. MailChimp support is unavailable to me (free account), and maybe someone else will have an answer. If you can "un-close" this thread, please do.
