### ISSUE TITLE
White Screen of Death after Saving Form

### ISSUE THREAD

**Issue by phongmedia** [ibericode/mailchimp-for-wordpress#289]
Testing on NGINX with PHP5-FPM and on Apache Prefork locally, I'm getting the same issue where Mailchimp for WP is crashing to a white screen of death after saving any form.

I tried disabling all plugins, and the issue still persists. By switching the theme to the WP-2015 theme, the issue finally went away.

This issue is happening when pressing save on this page:
`/wp-admin/admin.php?page=mailchimp-for-wp-forms&view=edit-form&form_id=XXX`

I've gone through and it's definitely the theme interacting with this plugin which is causing the issue. I haven't seen this issue with any other plugins before in developing this theme for the past 2 years, so my questions as the theme developer to the plugin developer, do you have any ideas or clues what might be causing this from your end? Any tips or ideas, if you've seen anything like this before, would be helpful.

Thanks!
Phong

EDIT : `WP_DEBUG` is enabled, and I've also checked PHP error logs and there's no sign of any errors happening. It seems just like something is potentially triggering a hard-exit.

**Comment by dannyvankooten** [comment]
HI @phongmedia ,

Sorry for the late reply, but it's a hard error to reproduce. A few questions:

- If the error log shows nothing, does the page source show anything (if you view-source that is)?
- Is this error happening with the same theme on other servers? Is this theme publicly accessible?

Without an error message this is very hard to debug, as there should be an error _somewhere_.
