### ISSUE TITLE
Send additional CF7 fields to MailChimp

### ISSUE THREAD

**Issue by virtualLast** [ibericode/mailchimp-for-wordpress#290]
This is no longer working, there are no errors being reported in the log either. I can see that the new subscribers are being added to the list, but the additional fields are not being populated.

`<label>Postcode<br />
    [text mc4wp-POSTCODE]</label>`

The above code is how I have added the fields to the form

**Comment by hchouhan** [comment]
Hello,
Please create a support ticket at https://wordpress.org/support/plugin/mailchimp-for-wp so we can assist you further. Please make sure to include a link to your website in the ticket so we can test the same.

**Comment by dannyvankooten** [comment]
Hi @virtualLast,

Did you manage to figure this one out already? As this is most likely not an issue in the plugin code, the WordPress.org forums would be a better place for this indeed.

A few pointers.

- Did this work before? If so, what changed?
- Is the corresponding MailChimp list field named `POSTCODE`?

**Comment by buchdag** [comment]
Seems like hitting "Renew Mailchimp lists" was all that was required to fix this. :sweat_smile:
