### ISSUE TITLE
Default sign-up form not updating subscribers 

### ISSUE THREAD

**Issue by awov** [ibericode/mailchimp-for-wordpress#291]
The signup form [mc4wp_form id="6093"] is not updating subscribers on mailchimp and my setup domain email account. What could be the problem?

Appreciate your help!
Elenah

**Comment by dannyvankooten** [comment]
Hi @awov ,

Please open a support topic on the [WordPress.org support forums](https://wordpress.org/support/plugin/mailchimp-for-wp) as that will most likely be a better place for this, as it's most likely not an issue in the code.

If you're seeing any error messages then please include those in your request. Also, take a look at **MailChimp for WP > Other** where there is a debug log at the bottom of the page, which could you give some more detailed error responses.

Hope that helps. If not, let me know!
