### ISSUE TITLE
No RSS items found

### ISSUE THREAD

**Issue by icx2** [ibericode/mailchimp-for-wordpress#292]
For the last 2 blog updates our subscibers received empty email that instead of the new post had "No RSS items found" in it. The plugin works for the last 6 months and usually it is ok, but recently it started to behave really weird. Two questions: 
1. Why it thinks there are no updates, when there are at least 2 posts that were published? The "No RSS item found email" was sent on Friday morning after Thursday publishing of the post and on Tuesday morning after a new post was published at midnight
3. Why if it thinks there are no RSS items it still generated an email to the subscribers? By logic if there are no new posts (and it thinks there are none), no email should be sent?
Please help with resolving these issues - needless to say this affects our business.
Thanks!

**Comment by dannyvankooten** [comment]
Hi @icx2,

Our plugin doesn't send any emails when you publish new posts so the issue is not with our plugin, it has to be something else.

How did you set-up the RSS to email campaign email? Or could it be that you're using another plugin, AutoChimp for example?

In any case, good luck!
