### ISSUE TITLE
Mailchimp form not always displaying well with WP twenty-sixteen

### ISSUE THREAD

**Issue by KA1FUN** [ibericode/mailchimp-for-wordpress#293]
I have five WP blogs using the twenty-sixteen theme. On four of these, the sign-up form looks great. On one, the form is misaligned. I have tried the following to resolve the issue, but without success.

Removed and readded the plug-in.
Changed the theme to another and back again.
Compared the non-working CSS with the working one. I could not detect and differences

The problem in is http://caminotips.com.

![ct signup form](https://cloud.githubusercontent.com/assets/18575379/14935451/17dd5524-0ea0-11e6-8b6f-9b751bbbaa1d.JPG)

For comparison, this screenshot is from http://walkingintohistory.com
![hw signup form](https://cloud.githubusercontent.com/assets/18575379/14935465/53617bfc-0ea0-11e6-9cdf-6b7b91d48009.JPG)

I believe there is some sort of width issue, not sure.

Thanks for your help.

**Comment by dannyvankooten** [comment]
Hi @KA1FUN ,

Adding the following CSS to your theme (for example using [Simple Custom CSS](https://wordpress.org/plugins/simple-custom-css/)) should place the checkboxes to a new line, which will make the form look much better.

```css
.mc4wp-form label {
    display: block;
}
```

Please note that you can also use the "Basic" stylesheet which is included in the plugin, you can select this from the "Appearance" tab on the edit form page.

Hope that helps. If not, let me know!

**Comment by KA1FUN** [comment]
Thank you. The form now displays correctly.


Jane Blanchard
941-726-6623

I am the author of the "Woman on Her Way" series and a blogger for authors.


Connect with me, click on the links below.

   <http://www.facebook.com/womanonherway/>
<https://twitter.com/womenoftheway> <http://pinterest.com/janevblanchard/>

Writer's Blog: Providing strategies and support for the indie writer
<http://janevblanchard.com/>
Author's Webpage: Woman On Her Way <http://womanonherway.com/>

Women of the Way Website <http://womenoftheway2011.com>
Hadrian's Wall Path Website <http://walkingintohistory.com>
Camino Tips <http://caminotips.com>


<http://womanonherway.com>
