### ISSUE TITLE
form submission on iphone

### ISSUE THREAD

**Issue by enigmaverse** [ibericode/mailchimp-for-wordpress#294]
When submitting form on Iphone, page does not redirect to thank you page.

http://www.floliving.com/monthly-flo-webinar

this does not appear to affect andriod products or browsers. Private browsing is disabled

**Comment by dannyvankooten** [comment]
Hi @enigmaverse,

I just did some testing but as I don't have an Apple phone at hand, was unable to reproduce the issue. Were you able to replicate it across different Apple devices, or does it just affect one single device?

Thanks in advance!

**Comment by dannyvankooten** [comment]
Hi @enigmaverse,

Another thing comes to mind: is your Redirect URL an absolute url (including `http://` etc.) or a relative URL?
