### ISSUE TITLE
Problem with sidebar form

### ISSUE THREAD

**Issue by skyscorcher** [ibericode/mailchimp-for-wordpress#298]
Hello, I have implemented your form on the sidebar, in order to collect emails, but I face a problem. Although the visitor uses his email he gets an error message of either "Oops something went wrong" or "Please fill in the required fields."

URL: 99wines.net

I am not sure, what is going on here.

Thanks

![screen shot 2016-05-16 at 18 20 36](https://cloud.githubusercontent.com/assets/19391634/15294031/47188ac0-1b93-11e6-9248-238f1eefd2de.png)

**Comment by dannyvankooten** [comment]
Hi @skyscorcher ,

Could you go into the settings of your form and just hit the "Save Changes" button one time. That will reset the settings of the form where it will recalculate the required fields. Could you check to see if that fixes your issue?

THanks in advance!

**Comment by skyscorcher** [comment]
Hi and thanks for the fast reply. I did that, but didn’t solve the problem.

Anything else please?

Thanks

**Comment by andreanam** [comment]
having the same issue -- users just started reporting it yesterday with a chrome update. seems to be working on my older version of chrome so that may be related?

**Comment by skyscorcher** [comment]
Hi, no, this is not the case. The problem I got is happening while I am on Safari.

•••••••••••••••••••••••
Roberto Zanon
zanon.robert@gmail.com
