### ISSUE TITLE
Form is left aligned but submit button is centered!?!?

### ISSUE THREAD

**Issue by ljordahl** [ibericode/mailchimp-for-wordpress#301]
Hello,

I have a sign up form on my homepage but where the users add their name and email is left aligned while the submit button is centered perfectly! I've attached a screenshot of the issue.

Help!

Thanks,

Lindsey

![screen shot 2016-05-26 at 5 07 43 pm](https://cloud.githubusercontent.com/assets/19599802/15593859/c94ff590-2364-11e6-8510-0382638f92a9.png)

**Comment by ljordahl** [comment]
Also, here is the code for the Mailchimp for Wordpress plugin I'm using:

<p>
    <input type="text" name="FNAME" value="Name" />
</p>

<p>
	<input type="email" name="EMAIL" placeholder="Your email address" required />
</p>

<p>
	<input type="submit" value="Yep, I'm in" />
</p>

**Comment by hchouhan** [comment]
Hello @ljordahl,

I would request you to create a support issue at https://wordpress.org/support/plugin/mailchimp-for-wp using the form at the bottom of our website. When you do so please also share with us the link to your website so we can test the form and it's CSS.
