### ISSUE TITLE
Hidden groupings with comma in name not working.

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/mailchimp-for-wordpress#302]
```
<input type="hidden" name="GROUPINGS[14589]" value="Love, Marriage and Evolution E-Book Download">
```

And could do with some overall UX improvements anyway.

**Comment by hchouhan** [comment]
The issue seems to be due to the comma. The value is submitted if there are no comma in the field value.

**Comment by dannyvankooten** [comment]
We can't really change the delimiter to something else and do this properly without breaking backwards compatibility for all people using `,` as a delimiter, so I'm thinking of introducing a new delimiting character `|` in version 4.0 (since that updates GROUPINGS to INTERESTS anyway).

#108
