### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by iktareen** [ibericode/mailchimp-for-wordpress#308]
Hello, 

I have integrated the mailchimp plugin and put it in this page 

http://www.isofleet.com/isocollect

when we click on subscribe button after entering the fields and when it give us a success or error message. The page scrolls up to the upper section. Can anyone help me whats going wrong there?

**Comment by dannyvankooten** [comment]
Hi @iktareen,

In which browser is this occuring for you? I just tested your form but after the page reloads, the window scrolls down back to the form element for me.

Thanks in advance!
