### ISSUE TITLE
Cannot Create New Forms

### ISSUE THREAD

**Issue by CLBeckmann** [ibericode/mailchimp-for-wordpress#311]
Every time I try to create a new form the page refreshes on the first form I created. I cannot get it to go back to http://www.cyw.academy/wp-admin/admin.php?page=mailchimp-for-wp-forms page.

**Comment by dannyvankooten** [comment]
Hi @CLBeckmann,

How are you getting to the "Add form" page? The free version of the plugin can only create 1 form because multiple forms is one of our [premium features](https://mc4wp.com/features/). The free version lacks required functionality to make that work, sorry.
