### ISSUE TITLE
Issue : Can't access form list cause it always output one form's editor instead

### ISSUE THREAD

**Issue by Bisent0** [ibericode/mailchimp-for-wordpress#323]
Hi,
I am having troubles accessing my form list after I imported all wordpress content on another wordpress hosted somewhere else. This Wordpress B uses same WP version, same theme, same plugins, same everything as Wordpress A. My forms were created on Wordpress A and are well imported on B.

The only problem is, when I click on Forms, even if the link shows it points on :
wp-admin/admin.php?page=mailchimp-for-wp-forms
It actually goes to :
wp-admin/admin.php?page=mailchimp-for-wp-forms&view=edit-form&form_id=9784
I don't know if it's really a problem related to MC4WP or something else.

Another thing is, if I delete all mc4wp forms by deleting posts in the database with post_type = mc4wp-form (I do it this way because I can't access the form list in the admin to delete theme), and if I add a new one, the issue is still the same, it outputs the edit page for this new form.
Hoping to find some help here :)
Thanks,

**Comment by dannyvankooten** [comment]
Hi @Bisent0,

How did you create the additional forms? Are you sure you have the Premium add-on plugin installed on the website you are importing to?

Multiple forms is a feature that is enabled by the Premium add-on, which includes the necessary code for creating the forms overview etc. Without the Premium add-on, the plugin will simply open up the form editor for your "default form".

Hope that helps. If not, let me know!

**Comment by Bisent0** [comment]
Thanks for the fast answer @dannyvankooten !
Looks like it's simple as that, I thought Premium add-on was only for the style builder.
Sorry for the wrong issue.

**Comment by dannyvankooten** [comment]
No worries at all @Bisent0, glad that helped and thanks for chiming in here. Now I want to improve the plugin by detecting the redirect and showing a notice when someone has multiple forms, to prevent others from running into the same thing. :-)
