### ISSUE TITLE
Subscribe form fields too small

### ISSUE THREAD

**Issue by doogie16** [ibericode/mailchimp-for-wordpress#326]
Hi

I have a subscribe form set up in a widget using Organic Themes 'Adventure' theme in Wordpress and the input fields for the email address and first name are only half the width of the widget.  I've tried changing the placeholder size in the form setup page but that doesn't work.  This is what's in the form page in the Plugin;

    <label>Email Address:</label>
    <input name="EMAIL" required="required" type="email" placeholder="Your email address" size="500">

    <label>First Name:</label>
    <input name="FNAME" type="text" placeholder="Your first name" size="500">

    <input type="submit" value="Subscribe">

 and this is how the widget appears on the page;

![image](https://cloud.githubusercontent.com/assets/20788230/17319098/9aa7a982-58ce-11e6-9cab-e3787b655c43.png)

Any assistance would be appreciated.

Craig

**Comment by doogie16** [comment]
<label>Email Address:</label>
    <input name="EMAIL" required="required" type="email" placeholder="Your email address" size="500">
</p><p>
    <label>First Name:</label>
    <input name="FNAME" type="text" placeholder="Your first name" size="500">
</p><p>
    <input type="submit" value="Subscribe">

**Comment by dannyvankooten** [comment]
Hi Craig,

Sorry for the late reply. If this is not sorted by now, please go into your form settings and open up the **Appearance** tab. Loading any of the available form styles should fix this.

If not, please post a link to your site as then your theme CSS is not playing nice.
