### ISSUE TITLE
Blank date is send in as 01/01/1970 

### ISSUE THREAD

**Issue by arnelap** [ibericode/mailchimp-for-wordpress#343]
when you have a not required date field in a MC4WP form and you don't touch the value during submit it will set the date to 01/01/1970  instead of blank.

At least in Chrome, did not test other browsers.

**Comment by dannyvankooten** [comment]
@arnelap Do you have any detailed steps to reproduce this? Leaving a date field untouched in Chrome does not send it to MailChimp as 01/01/1970... May be dependent on PHP version though?
