### ISSUE TITLE
Getting old and new form after re-installing

### ISSUE THREAD

**Issue by herbigt** [ibericode/mailchimp-for-wordpress#345]
Hi there,

I just re-installed the plugin after using it already a couple of weeks ago. Now, after finishing up the settings and copy, I get the new and the old form above each other. Presumably, it still uses the same id for the form and didn't delete the old content? How to get rid of this double form?

<img width="838" alt="screenshot 2016-08-27 14 41 24" src="https://cloud.githubusercontent.com/assets/2519222/18027472/7463a0a6-6c64-11e6-8d46-eb9ae99cbc9d.png">

Thanks a lot,
Tim

**Comment by dannyvankooten** [comment]
Hi @herbigt ,

How are you showing this form in your theme? Are you positive that you're not calling the shortcode or function twice, but with different ID parameters?

**Comment by herbigt** [comment]
Hey @dannyvankooten,

I'm using the shortcode embedded in my post to display the form.
In the concrete example it's: [mc4wp_form id="2804"]

When I delete this line of text, no form is shown at all. When I add it, the double-form is back. So, afaik no double calling the function or similar.

Cheers,
Tim

**Comment by dannyvankooten** [comment]
Hi @herbigt ,

That is super weird. Can you please post your form code for the older form here? Could it be that your new form contains the shortcode for the older form perhaps? Or maybe even the plain HTML for the old form?

**Comment by herbigt** [comment]
Hey @dannyvankooten,

I actually don't use the code of the old form anywhere in my blog. After deleting the plugin a couple of months ago, I removed all short codes as well.
It just started to appear below the new one after re-installing the plugin (cleared cache and all as well).

Anyways, here's the plain html code I get from inspecting the form(s) in a blog post of mine:
<img width="1440" alt="screenshot 2016-09-27 21 32 25" src="https://cloud.githubusercontent.com/assets/2519222/18888776/0efb9468-84fa-11e6-9b6d-eb217ec5114b.png">

Any idea? The old form (the one below) just seems to appear with the one above...

Cheers,
Tim
