### ISSUE TITLE
Not receiving confirmation e-mail

### ISSUE THREAD

**Issue by GarryOne** [ibericode/mailchimp-for-wordpress#346]
When someone tries to subscribe, he don't receive the confirmation e-mail, neither got subscribed. The problem occurs just with a certain account of mailchimp, and with this plugin, in all other cases, it's working, this means that this account works with other plugins (for example: Easy Peasy MailChimp Ajax Form) and other accounts work with this plugin (Mailchimp for WP). 
Another point to take into account is that the account with problems, got disabled all single opt-in methods, due to an abuse rate, however, I configured plugin to use double opt-in. Even more than that, I analyzed the report from Mailchimp account, regarding API calls and it's fine, exactly the same compared to another account which works.
Also, I checked debug log of this plugin, inside wp-admin, and it says "Successfully subscribed".
I will leave below the API key for investigation.

**Comment by DorothyKBiz** [comment]
I'm having the same issue. The sidebar sign up form just doesn't work, while the top bar form subscribes to list, but doesn't send confirmation email. http://pregnancybirthandparenting.com/

**Comment by dannyvankooten** [comment]
Hi @GarryOne ,

That is weird, what does your setting for "update existing subscribers" look like? Are you sure that the person is not already on the list, and therefore not getting the confirmation email?

This email is sent out by MailChimp, so please do also check if the email is not ending up in your SPAM folders.

Additionally, can you please install / upload the following file to your `/wp-content/plugins/` folder to enable verbose log debugging?

https://github.com/ibericode/mc4wp-snippets/blob/master/misc/enable-log-debugging.php

This will show all sign-up attempts in the debug log, along with their results.

PS. I removed your API key from your post. This key gives access to your entire MailChimp account, allowing anyone to do anything. Please don't ever share it on public forums like this. :)

**Comment by GarryOne** [comment]
@dannyvankooten
It was because of "update existing subscribers" setting, which was set to "Yes", but had to be "No". 
Thank you.

**Comment by nxtlvlgr** [comment]
Hello all, I'm having a similar issue with not receiving the confirmation emails. I've managed to work it out that I have the latest version of WordPress and a previous website that has the exact form on is still working but on the previous version of WordPress. 

So with that said, the plugin shows the option to send a confirmation email and on the new version it doesn't give me that option (see screenshot link for older opt-in) do you have any ideas around this, please.

[](http://www.problemtoparadise.com/wp-content/uploads/2016/10/Screen-Shot-2016-10-06-at-12.29.00.png)

Thank you.
