### ISSUE TITLE
Can't switch of reCAPCHA

### ISSUE THREAD

**Issue by simonkibalo** [ibericode/mailchimp-for-wordpress#347]
Hey guys,
I want to ask subscribers for double-verification. But it's should be without reCAPTCHA. 
How can I do it.

Thanks for your help

**Comment by dannyvankooten** [comment]
Hi @simonkibalo ,

I would use the [WPBruiser plugin](https://wordpress.org/plugins/goodbye-captcha/) for this.

Good luck!
