### ISSUE TITLE
Sort order of Lists in MailChimp not reflected in the plugin.

### ISSUE THREAD

**Issue by hchouhan** [ibericode/mailchimp-for-wordpress#350]
The order of the lists in the plugin is not same as the order of the lists in MailChimp.

**Comment by dannyvankooten** [comment]
cfeef6f932aa504c15bdb261b3da88786169a45d bumps the list limit to a 1000 lists.

**Comment by dannyvankooten** [comment]
Bumping the limit to a 1000 lists works, but makes the initial admin page load _very_ slow. I've created #353 to tackle this.
