### ISSUE TITLE
Confusion while upgrading to premium causes wp_option to never be set.

### ISSUE THREAD

**Issue by willhaynes** [ibericode/mailchimp-for-wordpress#354]
I admittedly performed a weird workflow.

Not realizing premium is an additional plugin, I deactivated mailchimp-for-wordpress before activating premium.

As a result my calls to `mc4wp_get_form();` returned the error below. Opening and saving the 'upgraded' form resolved the error.

I'm assuming by deactivating the main plugin the default form wp_option was never set on install.

```
Fatal error: Uncaught exception 'Exception' with message 'There is no form with ID 0, perhaps it was deleted?' in /var/www/wp/wp-content/plugins/mailchimp-for-wp/includes/forms/class-form.php:134 Stack trace: #0 /var/www/wp/wp-content/plugins/mailchimp-for-wp/includes/forms/class-form.php(44): MC4WP_Form->__construct(0) #1 /var/www/wp/wp-content/plugins/mailchimp-for-wp/includes/forms/functions.php(13): MC4WP_Form::get_instance(0) #2 /var/www/wp/wp-content/themes/hexa/inc/functions/header-charm.php(9): mc4wp_get_form() #3 [internal function]: {closure}('') #4 /var/www/wp/wp-includes/plugin.php(524): call_user_func_array(Object(Closure), Array) #5 /var/www/wp/wp-content/themes/exa/inc/containers/header.php(25): do_action('exa_header_char...') #6 /var/www/wp/wp-includes/template.php(574): require('/var/www/wp/wp-...') #7 /var/www/wp/wp-includes/template.php(531): load_template('/var/www/wp/wp-...', false) #8 /var/www/wp/wp-includes/general-template.php(167): locate_template(Array, true, false) #9 /var/www/wp/wp-content/them in /var/www/wp/wp-content/plugins/mailchimp-for-wp/includes/forms/class-form.php on line 134
```

**Comment by dannyvankooten** [comment]
Hey @willhaynes ,

Thanks for the bug report! Ugh, sorry to hear this happened.

The default form ID is actually stored upon saving _any_ form. The plugin checks if there's a default form ID already, and if not stores the ID of the form that's about to be saved. 

Did you ever save your form in the last ~6 months or did you go with the default form + settings? Looking into the code logic, it seems our "set default form ID" logic only kicks in when editing a form, so going with the default form without ever hitting the "Save Form" button would bypass the logic.... I'll get that fixed!

Let me know please.

**Comment by yadavji83** [comment]
I am facing the same error after updating to premium. Plugin versions are: 4.1.8 and 3.3.18 for premium. I was using the free version first and made a form already after updating to premium i created new form but it redirected me to the same old form after trying to add new form. When i clicked again to check all forms it is giving me this error:
-------------
Warning: array_map(): An error occurred while invoking the map callback in /home/ev23sq72/public_html/wp-content/plugins/mailchimp-for-wp/includes/forms/functions.php on line 34

Fatal error: Uncaught exception 'Exception' with message 'There is no form with ID 0, perhaps it was deleted?' in /home/ev23sq72/public_html/wp-content/plugins/mailchimp-for-wp/includes/forms/class-form.php:134 Stack trace: #0 /home/ev23sq72/public_html/wp-content/plugins/mailchimp-for-wp/includes/forms/class-form.php(44): MC4WP_Form->__construct(0) #1 /home/ev23sq72/public_html/wp-content/plugins/mailchimp-for-wp/includes/forms/functions.php(13): MC4WP_Form::get_instance(Object(WP_Post)) #2 [internal function]: mc4wp_get_form(Object(WP_Post)) #3 /home/ev23sq72/public_html/wp-content/plugins/mailchimp-for-wp/includes/forms/functions.php(34): array_map('mc4wp_get_form', Array) #4 /home/ev23sq72/public_html/wp-content/plugins/mc4wp-premium/multiple-forms/includes/class-forms-table.php(144): mc4wp_get_forms(Array) #5 /home/ev23sq72/public_html/wp-content/plugins/mc4wp-premium/multiple-forms/includes/class-forms-table.php(47): MC4WP_Forms_Table->get_items() #6 /home/ev23sq72/public_html/wp-content/plugins/mc4wp-premium/multip in /home/ev23sq72/public_html/wp-content/plugins/mailchimp-for-wp/includes/forms/class-form.php on line 134
-------------
