### ISSUE TITLE
Form inserted twice when called as function via Timber/Twig

### ISSUE THREAD

**Issue by j-greig** [ibericode/mailchimp-for-wordpress#360]
I'm inserting a form using the mc4wp_show_form() function, but called in a [Timber](http://timber.github.io/timber/#functions) template. 

It displays the form twice in my footer when I do this... is this a bug?

`		{% block footer %}
    			<footer class="mw5-ns mw7-ns center tc">
    				{{function("mc4wp_show_form" , '516')}}
    			</footer>
    			{{ function('wp_footer') }}
		{% endblock %}`

PS. Am running WP 4.6.1, MC4WP 4.0.4, Timber 1.1.6

**Comment by dannyvankooten** [comment]
Hi @j-greig,

That is most likely because the `mc4wp_show_form` function already echoes the form, and if I recall correctly then Timber uses Twig, which echoes stuff by wrapping it in `{{` and `}}`. 

What happens if you surround it in code tags instead? I believe they are `{% ... %}`.

**Comment by j-greig** [comment]
That throws an error — I have switched to the function wrapper but it's still duplicated... I will ask on the Timber repo for help... thanks!
`$context['newsletter_signup'] = TimberHelper::function_wrapper( 'mc4wp_show_form', array('516') );
`

**Comment by dannyvankooten** [comment]
Hi @j-greig ,

Another option is to simply use the `mc4wp_get_form` function like this.

```php
{{ mc4wp_get_form( 516 ) }}
```

This function returns the actual Form object, which is then cast to a string by Timber / Twig and outputted.

Hope that helps. If not, let me know!
