### ISSUE TITLE
Plugin Not Activating with wpcom_vip_load_plugin in VIP environment

### ISSUE THREAD

**Issue by kala725** [ibericode/mailchimp-for-wordpress#366]
Plugin Not Activating with wpcom_vip_load_plugin in VIP environment. How can I achieve the same. ?

On line 113 in mailchimp-for-wp.php , if I change the hook in the below line
add_action( 'plugins_loaded', '_mc4wp_load_plugin', 20 );
 to
add_action( 'init', '_mc4wp_load_plugin', 20 );

it works. Is this a correct way to do?

Added a pr also for the same https://github.com/ibericode/mailchimp-for-wordpress/pull/367/files

**Comment by dannyvankooten** [comment]
Hi @kala725 ,

That would load the entire plugin at the `init` hook, which is quite late in the lifecycle of a WordPress request and not ideal.

What exactly isn't working in a VIP environment? Are you seeing any specific error messages?

**Comment by dannyvankooten** [comment]
Hi @kala725 ,

Please let us know if you're still experiencing issues with the plugin in a WP VIP environment. I'm closing this issue for clarity.
