### ISSUE TITLE
Manual syncing sends opt in email from mailchimp

### ISSUE THREAD

**Issue by shayatik** [ibericode/mailchimp-for-wordpress#369]
In Mailchimp - I unsubscribed a user manually.

In Wordpress - I started manual synchronization. Mailchimp sends the unsubscribed email an Opt In Email ("Please confirm your subscription").

**Comment by dannyvankooten** [comment]
Hi @shayatik,

I replied to you in the correct repository for this, [mailchimp-user-sync](https://github.com/ibericode/mailchimp-user-sync/issues/81). Let's handle this there to keep things organised.
