### ISSUE TITLE
Duplicating a form fails to persist the original form's custom "Styles Builder" formatting

### ISSUE THREAD

**Issue by FirmPlay** [ibericode/mailchimp-for-wordpress#370]

**Comment by dannyvankooten** [comment]
Hi @FirmPlay,

The styles builder settings are stored separately from the actual form (behind the scenes). You can easily copy another form styles by going into the **Styles Builder**, opening the **Advanced** section and using the "Copy from other form" tool though.

We have no plans on copying the Styles Builder styles when duplicating a form right now as this is imposing some difficulties with the way things are set-up now. Sorry.
