### ISSUE TITLE
No option to default the user into one of the groups of the mailing list

### ISSUE THREAD

**Issue by inPhilly** [ibericode/mailchimp-for-wordpress#371]
In the Contact Form 7 integration, there is no option to default the user into one of the groups of the mailing list. Is this by design, or is it something you overlooked by mistake? It seems such an off thing that an actual MailChimp plugin would omit this selection, when other add-ons for MailChimp (such as the Give Donations plugin add-on) do give their users that choice.

**Comment by arnelap** [comment]
Hi,

For anyone coming across this git issue, here is the code to add a specific integration to a specific interest id (group).

https://github.com/ibericode/mc4wp-snippets/blob/master/integrations/wp-registration-form/add-to-grouping.php

That snippet is for the wp-registration-form. You can replace that slug with any of the other integrations:
https://github.com/ibericode/mc4wp-snippets/blob/master/integrations/integration-slugs.md

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp

Hope that helps! 

Kind regards,
