### ISSUE TITLE
Hidden Interest groups are not added to MC when using name instead of ID in the value

### ISSUE THREAD

**Issue by hchouhan** [ibericode/mailchimp-for-wordpress#374]
E.g. The code below does not work

`<input type="hidden" name="INTERESTS[a6cfe61ce1]" value="Interest Name|Name 2">`

But, this works:

`<input type="hidden" name="INTERESTS[a6cfe61ce1]" value="12dfdf34|3dvdg343">`

**Comment by dannyvankooten** [comment]
I just tried to replicate this but following that first syntax, everything worked as expected...

```html
<input type="hidden" name="INTERESTS[c755a548ed]" value="Group 1|Group 3">
```

Are you 100% sure that the names in the `value` attribute are an exact match of the interest names?

**Comment by dannyvankooten** [comment]
Closing this as it works  with the given details.
