### ISSUE TITLE
There is no "checkboxes" bar in mailchimp

### ISSUE THREAD

**Issue by rinpocse91** [ibericode/mailchimp-for-wordpress#378]
I installed MailChimp for WordPress 4.0.7. by ibericode.
On the wp admin bar, i cant  see the chechnoxer menu,
What is the problem? Thank you.

![dsds](https://cloud.githubusercontent.com/assets/23096289/19762045/976853b8-9c38-11e6-87b2-8effa0b9c6a0.png)

**Comment by dannyvankooten** [comment]
Hi @rinpocse91 ,

We renamed "checkboxes" to "integrations" when we launched version 3.0 of the plugin. Can you please let us know where you found this text. it sounds like we forgot to update a tutorial.
