### ISSUE TITLE
Split-up ADDRESS fields

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/mailchimp-for-wordpress#38]
Right now, address fields is just one field where MailChimp splits it up into `addr1, addr2, city, zip, country` fields.

**Comment by dannyvankooten** [comment]
Documentation on how to do it manually: https://mc4wp.com/kb/split-address-fields/

**Comment by cjrobe** [comment]
Thanks, the manual instructions worked perfect.

**Comment by cjrobe** [comment]
I just copy and pasted the manual fields over and the address was not transferred into Mailchimp for some reason.

**Comment by cjrobe** [comment]
I figured it out. "ADDRESS" under input name should be replaced with the field tag shown on MailChimp for Wordpress's main page.
![github](https://cloud.githubusercontent.com/assets/5606066/7774334/749dcda2-0078-11e5-9e24-7d562ed6d86b.png)

**Comment by dannyvankooten** [comment]
@cjrobe Glad you figured it out yet, was about to respond that. The varying "address field" name is also what makes it hard for the plugin to do this automatically, in case you were wondering. 

We'll figure something out eventually!

**Comment by cjrobe** [comment]
That makes sense. Thanks for the awesome plugin, works great!
