### ISSUE TITLE
Enabling Email causes the form to not submit

### ISSUE THREAD

**Issue by tina-inspiredenterprises** [ibericode/mailchimp-for-wordpress#380]
I've attempted to enable emails for a form. When I change it from No to Yes and attempt to submit my form, I get the error message every time that says "something went wrong...". If I change it back to no, the form works fine.

**Comment by dannyvankooten** [comment]
Hi @tina-inspiredenterprises ,

Can you please elaborate on what you mean by "enable emails"? Is this the double opt-in setting? Does the debug log on *MailChimp for WP > Other* show you anything?

**Comment by tina-inspiredenterprises** [comment]
In the settings it's the last tab where you can set up an email notification to get an email when someone fills out your form. So if I want to know when someone uses the form, I use that email notification setting. 
-------- Original message --------From: Danny van Kooten <notifications@github.com> Date: 11/10/16  9:18 AM  (GMT-06:00) To: ibericode/mailchimp-for-wordpress <mailchimp-for-wordpress@noreply.github.com> Cc: tina-inspiredenterprises <tina@inspiredenterprisesinc.com>, Mention <mention@noreply.github.com> Subject: Re: [ibericode/mailchimp-for-wordpress] Enabling Email causes the form to not submit (#380) 
Hi @tina-inspiredenterprises ,

Can you please elaborate on what you mean by "enable emails"? Is this the double opt-in setting? Does the debug log on MailChimp for WP > Other show you anything?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ibericode/mailchimp-for-wordpress","title":"ibericode/mailchimp-for-wordpress","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ibericode/mailchimp-for-wordpress"}},"updates":{"snippets":[{"icon":"PERSON","message":"@dannyvankooten in #380: Hi @tina-inspiredenterprises ,\r\n\r\nCan you please elaborate on what you mean by \"enable emails\"? Is this the double opt-in setting? Does the debug log on *MailChimp for WP \u003e Other* show you anything?"}],"action":{"name":"View Issue","url":"https://github.com/ibericode/mailchimp-for-wordpress/issues/380#issuecomment-259716666"}}}

**Comment by dannyvankooten** [comment]
Hi @tina-inspiredenterprises ,

Can you please contact us at support@mc4wp.com? That is a premium feature, meaning you have the rights to premium support. We'll get back to you within 24 hours (usually much sooner than that) and help you fix this.

Most likely, a PHP error is causing some issues. It would be super helpful if you could include PHP's error log (after trying to submit a form) so that we can take a look at the actual error. Your host should be able to provide this to you.

Let us know please.

(PS. I am closing this issue for clarity, as it is more than likely a server issue and not a plugin issue.)
