### ISSUE TITLE
Not adding Amazon Pay customers to list

### ISSUE THREAD

**Issue by harapad** [ibericode/mailchimp-for-wordpress#381]
I'm using MailChimp for WP and I have it working so that it automatically adds woocommerce customers to my mailing list.  It's working for all payment methods, but any time a customer uses Amazon Pay it does not add them. 

Store is located at harapad.com in case it's helpful.

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
