### ISSUE TITLE
Missing argument 3 for Mailchimp_API::get()

### ISSUE THREAD

**Issue by jeffceriello** [ibericode/mailchimp-for-wordpress#384]
Hi there,

I am getting this error

`Warning: Missing argument 3 for MailChimp_API::get(), called in /home/wardrob0/public_html/wp-content/plugins/mailchimp/mailchimp.php on line 841 and defined in /home/wardrob0/public_html/wp-content/plugins/mailchimp/lib/mailchimp/mailchimp.php on line 21`

Is there a way to fix it?

Thanks
Jeff

**Comment by dannyvankooten** [comment]
Hi Jeff,

That error is not coming from our plugin, we are "mailchimp-for-wp" whereas that error indicates you're using the "mailchimp" plugin. Please ask support with them.

Good luck!

**Comment by jeffceriello** [comment]
Oh right my bad, sorry about that! Thank you Danny!
