### ISSUE TITLE
make interest group mandatory in safari on iOS

### ISSUE THREAD

**Issue by arnelap** [ibericode/mailchimp-for-wordpress#394]
I am using the java script as shown in this support KB article:

https://mc4wp.com/kb/interest-groupings-required-field/

This works fine in Firefox on my laptop, but it doesn’t work with Safari on an iPhone.

https://wordpress.org/support/topic/make-interest-groupings-a-required-field-on-iphone/

**Comment by dannyvankooten** [comment]
This is probably due to Safari on mobile being outdated, even on the latest version it is pretty shitty and lacks HTML5 features. Chances are this fixed itself by now.
