### ISSUE TITLE
PHP7 Error: Extension 'mysql_' is deprecated

### ISSUE THREAD

**Issue by dabodude** [ibericode/mailchimp-for-wordpress#397]
Hello, I found this error while running a PHP7 compatibility test:

FILE: /wp-content/plugins/mc4wp-premium/logging/includes/class-dashboard-log-widget.php
---------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------------------------
 60 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
---------------------------------------------------------------------------------------------------------------------

FILE: /wp-content/plugins/mc4wp-premium/logging/includes/class-log-table.php
--------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------------------------------------
 170 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
--------------------------------------------------------------------------------------------------------------

FILE: /wp-content/plugins/mc4wp-premium/logging/views/admin-reports-log_item.php
--------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------------------------------------
 151 | ERROR | Extension 'mysql_' is deprecated since PHP 5.5 and removed since PHP 7.0 - use mysqli instead.
--------------------------------------------------------------------------------------------------------------

**Comment by dannyvankooten** [comment]
Hi @dabodude ,

Thanks for filing an issue here. This is a so-called false positive as it seems the PHP7 compatibility checker (the one by WP Engine by any chance) is lacking something crucial. We have a method (on our own class) called `mysql_datetime_to_local_datetime` which is a function we implemented ourselves, not of the MySQL extension. Therefore it is is safe to use this function, and it won't be affected by the deprecation of `mysql_`.

We'll take a look at their compatibility checker to see if we can submit a fix for this. Thanks for dropping by here, appreciate it!
