### ISSUE TITLE
Data did not match any of the schemas described in anyOf.

### ISSUE THREAD

**Issue by dscotese** [ibericode/mailchimp-for-wordpress#401]
This error can apparently be (inappropriately) created thus:
1. Have a form on MC that includes a field of type "Address".
2. Try to sign up by leaving the address field empty (this produces what I think is a VALID report of the error, which is fine.)
3. Edit the form on MailChimp by deleting the original field of type "Address" and adding a new one of type "Text", and set the "Put this tag in your content:" value to the same as the field you just deleted (this is the only way I could find to change the TYPE of a field) so that you don't have to edit your form.
4. Repeat #2, expecting it to work this time because there is no schema for text fields.

This may be a problem with Mailchimp itself, in case they cash validation of fields based on their merge-field number.  I got around it by making a NEW field with a NEW value for "Put this tag in your content:" but it was quite frustrating to have to abandon the original fieldname.

**Comment by dannyvankooten** [comment]
Hey @dscotese,

Ugh, that sounds weird yeah. What error were you getting exactly? The plugin is performing its own validation before sending the request off to MailChimp, so it could be that the plugin had yet to pick up on your changes to the list field in MailChimp.

You can re-fetch the latest list information by clicking the "Renew Lists" button on the **MailChimp for WordPress > MailChimp** page.

If that still produces the same error then it looks to be a bug in MailChimp where they indeed cache the validation rules based on the field name, but then not update it once that field is changed or deleted...

**Comment by dscotese** [comment]
The error was "Data did not match any of the schemas described in anyOf." I don't think there was any other error.  I *thought* I verified that the procedure I provided could be used again and again to produce the error.  If you tried it and didn't get the error, then no worries.  If you try it and do get that error, then you have something to work with.

**Comment by dannyvankooten** [comment]
Hi @stephengardner,

What does your address field look like in your form? Is it a single field?

**Comment by stephengardner** [comment]
You know what - I didn't realize this was not the official mailchimp github.

I'm passing in address correctly.  It's coming from Shopify users.  The data works for > 90% of users but some users don't have properly formatted addresses so they get an error.  My gripe is that I can't tell what is "bad" according to Mailchimp.  I'm passing in the correct addr1, addr2, etc, values - always as strings.

So for now I'm omitting the address field since I can't tell what's good or bad because Mailchimp doesn't have that documented (that I know of).
