### ISSUE TITLE
Checkbox too far left

### ISSUE THREAD

**Issue by Bankenmaerchen** [ibericode/mailchimp-for-wordpress#402]
Hi,

if i integrate the mailchimp checkbox in the comment-function of wordpress, the layout is suboptimal. The checkbox is too far to the left. The Blog adress is www.bankenmaerchen.de

What can i do?? Thanks for your help!

Sascha

![img_7757](https://cloud.githubusercontent.com/assets/24830366/21550858/7ac54300-cdfd-11e6-8ab6-9e81f176acdb.PNG)

**Comment by dannyvankooten** [comment]
Hi @Bankenmaerchen ,

Does this error persist if you go into your integration settings and enable the "Load some default CSS" option? Most likely your theme is applying some weird styling to checkbox inputs but our default CSS should fix that.
