### ISSUE TITLE
unsubscribe issue

### ISSUE THREAD

**Issue by mtomlin10000** [ibericode/mailchimp-for-wordpress#404]
The wrong response is returned when unsubscribing details that do not exist in the list, a success response is returned suggesting the details exist.

**Comment by dannyvankooten** [comment]
Hi @mtomlin10000,

I'm afraid that is a limitation by the MailChimp API, they are following RESTful principles pretty strictly so they want you to check if a resource exists (GET) before attempting to DELETE it.
