### ISSUE TITLE
Adding value="Sign up" to submit input duplicates the text

### ISSUE THREAD

**Issue by wellbeans** [ibericode/mailchimp-for-wordpress#405]
I have a simple form of:

`<input type="email" name="EMAIL" placeholder="Your e-mail address" required />
<input type="submit" value="Sign up">`

It outputs like this:

`<div class="ui-btn ui-input-btn ui-corner-all ui-shadow">Sign up<input type="submit" value="Sign up"></div>`

As you can see, 'Sign up' is outputted twice; once inside the div and once inside the input. I can't target the text inside the div without also affecting the input.

![capture](https://cloud.githubusercontent.com/assets/13420674/22020503/8d6ab64a-dcb0-11e6-8a4a-c96c2e40a088.JPG)

**Comment by wellbeans** [comment]
Turns out it was an issue with having jQuery mobile on the site as well.

**Comment by dannyvankooten** [comment]
Hey, thanks for the update @wellbeans. Will keep it in mind in case we run across it again.
