### ISSUE TITLE
Forms Not Generated From Reports

### ISSUE THREAD

**Issue by taastephens** [ibericode/mailchimp-for-wordpress#408]
Hello I ran a report to view all of the forms that have been selected over the course that I've been using MC for WP and all the submissions show but not which form.

I even exported the cvs file to get the link but the numbers don't seem to match up.

Please help.

![wp for mc](https://cloud.githubusercontent.com/assets/12161498/22715882/5051ca40-ed50-11e6-89ed-afedef464f31.png)

**Comment by dannyvankooten** [comment]
Hi @taastephens,

I was able to locally reproduce this issue, looking into it as we speak!

**Comment by dannyvankooten** [comment]
Hi @taastephens,

If you go to the "Log" tab on the *MailChimp for WP > Reports* page, what shows as the "Type" column for the sign-ups in that table?

**Comment by taastephens** [comment]
Thanks Danny,

‘Type’ is ‘form’

Tiffany Stephens
Marketing Specialist
Intelligent Software Solutions - A Polaris Alpha Company
5450 Tech Center Dr.
Colorado Springs, CO 80919
(Office)719.452.7622
www.polarisalpha.com<http://www.polarisalpha.com>

**Comment by taastephens** [comment]
Meant to send you a screenshot:

[cid:image001.jpg@01D28202.13B796F0]

Tiffany Stephens
Marketing Specialist
Intelligent Software Solutions - A Polaris Alpha Company
5450 Tech Center Dr.
Colorado Springs, CO 80919
(Office)719.452.7622
www.polarisalpha.com<http://www.polarisalpha.com>

From: Tiffany Stephens
Sent: Wednesday, February 08, 2017 11:54 AM
To: 'ibericode/mailchimp-for-wordpress' <reply@reply.github.com>; ibericode/mailchimp-for-wordpress <mailchimp-for-wordpress@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [ibericode/mailchimp-for-wordpress] Forms Not Generated From Reports (#408)

Thanks Danny,

‘Type’ is ‘form’

Tiffany Stephens
Marketing Specialist
Intelligent Software Solutions - A Polaris Alpha Company
5450 Tech Center Dr.
Colorado Springs, CO 80919
(Office)719.452.7622
www.polarisalpha.com<http://www.polarisalpha.com>

**Comment by dannyvankooten** [comment]
Hi @taastephens ,

The screenshot did not come through to GitHub, I'm guessing their email forwarding service does not take attachments into account. However, I think we may know what's going on here. Can you please try visiting the following page on your site?

/wp-admin/?mc4wp_run_log_migration=3.0

So if your site is polarisalpha.com, the following link should be it: www.polarisalpha.com/wp-admin/?mc4wp_run_log_migration=3.0

That will re-run all database migrations from version 3.0 and up, I think your site may have skipped one at some point therefore invalidating the data for your reports table. Technical talk, but visiting that URL should fix it.

Let me know please.

**Comment by taastephens** [comment]
Thanks Danny,

Didn’t work unfortunately. I visited the site, refreshed the page and visited the Reports tab again and 942 forms are submitted but doesn’t say which ones.

Tiffany Stephens
Marketing Specialist
Intelligent Software Solutions - A Polaris Alpha Company
5450 Tech Center Dr.
Colorado Springs, CO 80919
(Office)719.452.7622
www.polarisalpha.com<http://www.polarisalpha.com>

**Comment by dannyvankooten** [comment]
Hey @taastephens,

As this is related to a Premium feature, could you send us an email (support@mc4wp.com) with login details so we can take a closer look at this? It's hard to tell what's causing this from the outside.

Thanks in advance!
