### ISSUE TITLE
PHP error when saving form

### ISSUE THREAD

**Issue by citygirlsdesign** [ibericode/mailchimp-for-wordpress#410]
Hi!

I get this error whenever I try to save the form:

Warning: stripos() expects parameter 1 to be string, array given in /home/citygirl/public_html/lab/wp-includes/formatting.php on line 3774

Warning: Cannot modify header information - headers already sent by (output started at /home/citygirl/public_html/lab/wp-includes/formatting.php:3774) in /home/citygirl/public_html/lab/wp-includes/pluggable.php on line 1179

The changes do save, but something is wrong somewhere causing this issue...

Thanks!

**Comment by dannyvankooten** [comment]
Hi @citygirlsdesign ,

Did you manage to figure out what was causing this (as the issue is closed)? 

Let me know please.

**Comment by citygirlsdesign** [comment]
Hi!
Yes, it was a cache plugin issue, nothing to do with MC4WP :) I wasn't sure if I could delete the thread, so I just closed it!

Sorry about that!

Virginie

**Comment by dannyvankooten** [comment]
Phew, glad to hear it. Thanks for the update Virginie!
