### ISSUE TITLE
Make it more clear that multiple forms is a Premium feature.

### ISSUE THREAD

**Issue by tzookb** [ibericode/mailchimp-for-wordpress#411]
Installed the plugin it works great, connected MC.

But I can have only one form...

When I click on "forms" I get to that only single form...

No option to create another one....

Any ideas?

**Comment by dannyvankooten** [comment]
Hi @tzookb,

Yes, that's actually intended behavior but it sounds like we should be a little more clear about that. The free version allows for one single form to be created via the UX, while [the premium add-on allows you to create an unlimited number of forms](https://mc4wp.com/features/). 

It's our way to sustain development of the free plugin, as a single form usually suffices for over 90% of our users.

Does that help?

**Comment by tzookb** [comment]
Surely helps!

Just to clarify it, as I almost removed it :/

**Comment by dannyvankooten** [comment]
Sorry it wasn't more clear right away, we'll try to improve on that in the plugin!
