### ISSUE TITLE
Service Unavailable

### ISSUE THREAD

**Issue by atheeb** [ibericode/mailchimp-for-wordpress#413]
Hi,
I have integrated the mailchimp plugin to one of my sites but it is giving me below error - 
"**MailChimp returned the following error:
Service Unavailable**."

I have check with my host for the CURL version and the whitelisting of the domain. it is all fine. 
Do let me know what the issue is. 

thanks and regards,
Atheeb
![mailchimp-error](https://cloud.githubusercontent.com/assets/9332170/23391308/0f60043e-fd9a-11e6-9682-b4ce20d7d7aa.jpg)

**Comment by emmyla** [comment]
Hi, yes, I'm having the same issue.  
I've tried uninstalling and reinstalling and it's the same.
Please help.

Thanks,
Emmy

**Comment by dannyvankooten** [comment]
Hi both,

Sorry for being somewhat late reply but unfortunately this is not something the plugin can really do anything about. 

The error message usually means that your site's server is being blocked by the firewall service that MailChimp is using. GoDaddy is known for having these issues, and up until now the only way to get rid of them was by requesting to be moved to a new server or they just mysteriously vanished. For all we know, it's GoDaddy related...

I'd start out by emailing your webhost to ask for a new IP Address, which should be an easy thing to do for them. Most likely, that will get rid of the error messages right away.
