### ISSUE TITLE
Mailchimp Top Bar - Cramp

### ISSUE THREAD

**Issue by russ2204** [ibericode/mailchimp-for-wordpress#414]
The top bar is going over the top pf my website rather than above it.  Hence it is on top of the site menu!  How do I address this ?

**Comment by dannyvankooten** [comment]
Hi @russ2204,

This depends on the CSS of your site's theme. Do you have a link to your site so we can take a look? That way I might be able to provide a few pointers on how to get it fixed.

A simpler workaround may be to use the "bottom" position instead.

Let us know please.

PS. I'm marking this as closed as it is a compatibility issue with your site's theme, not an issue in the plugin itself.

**Comment by russ2204** [comment]
Thanks

Ukchoirfestival.com



Kind Regards,

Russell Scott


[https://www.dropbox.com/s/m70ldzz5saoi1df/twitter.png?raw=1]<https://twitter.com/RussellScottUK>               [https://www.dropbox.com/s/y4fjimqyzf44nwh/facebook.png?raw=1] <https://www.facebook.com/russellscottofficial/>                 [https://www.dropbox.com/s/aggwdz7lr2ika5a/youtube.png?raw=1] <http://www.youtube.com/c/russellscottentertainment>              [https://www.dropbox.com/s/80jhz1k45mwrv44/linkedin.png?raw=1] <https://uk.linkedin.com/in/russell-scott-a8b96b43>


Please note: I aim to respond to emails within 24hrs. For URGENT issues, please contact me by telephone.

[https://www.dropbox.com/s/wv4rhmp1ludl02e/Russel%20Scott%202.png?raw=1]<http://www.russellscottentertainment.com>


m.      07590 454606<tel:07590%20454606>

t.      08445 67 68 96<tel:08445%2067%2068%2096>

e.      russell.scott@russellscottentertainment.com<mailto:russell.scott@russellscottentertainment.com>

w.      www.russellscottentertainment.com<http://www.russellscottentertainment.com>


This message is for the named person's use only. It may contain confidential, proprietary or legally privileged information. No confidentiality or privilege is waived or lost by any mis-transmission. If you receive this message in error, please immediately delete it and all copies of it from your system, destroy any hard copies of it and notify the sender. You must not, directly or indirectly, use, disclose, distribute, print, or copy any part of this message if you are not the intended recipient. Russell Scott Entertainment Limited reserve the right to monitor all e-mail communications through its networks.

[https://www.dropbox.com/s/881mnhd289z1zw0/leaf.png?raw=1]Think before you print.

Russell Scott Entertainment Limited is a company registered in England & Wales. Registered number: 07081589<tel:07081589>. Registered office: 5 Elstree Gate, Elstree Way, Borehamwood, Herts. WD6 1JD (THIS IS NOT OUR MAILING ADDRESS).




On 9 Mar 2017, 08:55 +0000, Danny van Kooten <notifications@github.com>, wrote:

Hi @russ2204<https://github.com/russ2204>,

This depends on the CSS of your site's theme. Do you have a link to your site so we can take a look? That way I might be able to provide a few pointers on how to get it fixed.

A simpler workaround may be to use the "bottom" position instead.

Let us know please.

PS. I'm marking this as closed as it is a compatibility issue with your site's theme, not an issue in the plugin itself.
