### ISSUE TITLE
Please fill in the required fields

### ISSUE THREAD

**Issue by creation6910** [ibericode/mailchimp-for-wordpress#417]
all fields are completed with data and getting this message
"Please fill in the required fields"

**Comment by creation6910** [comment]
here si what we have:

<p>
    <label>First Name</label>
    <input type="text" name="FNAME" required>
</p>
<p>
    <label>Last Name</label>
    <input type="text" name="LNAME" required>
</p>
<p>
	<label>Email address: </label>
	<input type="email" name="EMAIL" placeholder="Your email address" required />
</p>
<p>
    <label>Phone Number</label>
    <input type="tel" name="MMERGE5" required>
</p>
<p>
    <label>Company</label>
    <input type="text" name="MMERGE4" required>
</p>
<p>
    <label>Street Address</label>
    <input type="text" name="MMERGE3[addr1]" required>
</p>
<p>
    <label>City</label>
    <input type="text" name="MMERGE3[city]">
</p>
<p>
    <label>State</label>
    <input type="text" name="MMERGE3[state]">
</p>
<p>
    <label>ZIP</label>
    <input type="text" name="MMERGE3[zip]">
</p>
<p>
    <label>Preferred Scheduling</label>
    <select name="MMERGE7" required>
        <option selected>ASAP</option>
        <option>AM Only</option>
        <option>PM Only</option>
        <option>Other</option>
    </select>
</p>
<p>
    <label>How may we help you?</label>
    <input type="text" name="MMERGE6" required>
</p>
<p>
    <label>Do you have a Managed Service Agreement with us?</label>
    <label>
</p>
<p>      
        <input name="MMERGE8" type="radio" value="Yes" checked required> <span>Yes</span>
    </label>
    <label>
           <input name="MMERGE8" type="radio" value="No" required> <span>No</span>
    </label>
</p>
<p>
	<input type="submit" value="Request Service" />
</p>

**Comment by creation6910** [comment]
still open

**Comment by dannyvankooten** [comment]
Hi @creation6910,

Do you have a link to your site? If you go to the page where you edit the form, is any of the "available fields" showing a red border? Does re-saving your form mark-up fix anything for you?

Thanks in advance!

**Comment by creation6910** [comment]
It is working now- needed to add country

thx

**Comment by dannyvankooten** [comment]
Great, glad to hear it!
