### ISSUE TITLE
Shortcode (in php) replicating twice

### ISSUE THREAD

**Issue by daveursillo** [ibericode/mailchimp-for-wordpress#419]
Hi there, 

I'm integrating a Mailchimp For Wordpress shortcode into my Footer (at DaveUrsillo.com) but it seems to be replicating (displaying twice). I can't really figure out why, but it may be somethign to do with my Wordpress theme. Is my code wrong?

I've tried using this code:  `<?php if( function_exists( 'mc4wp_show_form') ) { echo mc4wp_show_form( 22988 ); } ?>`

And this code: `<?php echo mc4wp_show_form( 22988 ); ?>`

I've styled the code using some PHP too, because I can't seem to get the shortcode to display properly without it, could that be the cause?:

```
<div class="readnext clearfix" style="margin-left:0px;">
  <input type="email" name="EMAIL" placeholder="Your email address..." required>
  <input type="hidden" name="SSOURCE" value="{current_url}" >
  <input type="hidden" name="LIST" value="du" >
  <button type="submit">SUBSCRIBE</button>
</div>
```

Any suggestions would be welcome!

**Comment by dannyvankooten** [comment]
Hi @daveursillo,

The `mc4wp_show_form` function already `echo`'s, so getting rid of that `echo` statement in front of the function call should fix it.

There's also a `mc4wp_get_form` function which simply returns the form HTML as a string, so if you need it as a variable before echoing then that can be used as well.

```php
<?php mc4wp_show_form( 22988 ); ?>
```

Or...

```
<?php echo mc4wp_get_form( 22988 ); ?>
```

Hope that helps!
