### ISSUE TITLE
Have set mailchimp newsletter sign up to hide after successful sign up…

### ISSUE THREAD

**Issue by copley1** [ibericode/mailchimp-for-wordpress#420]
see above – have set form to hide after sign up but STILL shows?

https://monosnap.com/file/T27jXQc7J2VK3xxVYR0anLySIhOPLc

**Comment by hchouhan** [comment]
Hello,

The feature within our plugin only hides the form after sign-up. If you refresh the page the form will reappear. If you wish to hide the form permanently from the users who already signed up using the same form then please use the code at https://github.com/ibericode/mc4wp-snippets/blob/master/forms/hide-form-for-people-that-subscribed.php.
