### ISSUE TITLE
Support proxies?

### ISSUE THREAD

**Issue by LaszloHont** [ibericode/mailchimp-for-wordpress#422]
Proxy support would be nice!

**Comment by arnelap** [comment]
For connecting to the MailChimp API? 
I think in most cases your hosting provider can set that up for you?

I suppose you want proxy support because of shared hosting IP being banned by Akamai?

**Comment by LaszloHont** [comment]
Yes. The proxy support is to get to the internet, there is a firewall blocking me so the request must go through the proxy.

**Comment by dannyvankooten** [comment]
Hi @LaszloHont,

The plugin uses the default WordPress HTTP API for all its remote requests, which by default uses CURL and if that's not available it falls back to HTTP Streams. 

If you're using CURL, proxy support should definitely be supported. I _think_ that you can enable this globally on your site by setting the following constants in your _wp-config.php_ file.

```php
define('WP_PROXY_HOST', '192.168.84.101');
define('WP_PROXY_PORT', '8080');
define('WP_PROXY_BYPASS_HOSTS', 'localhost,*.wordpress.org');
```

Source: https://developer.wordpress.org/reference/classes/wp_http_proxy/

There shouldn't be anything specific to the MailChimp for WordPress plugin itself you have to configure.
