### ISSUE TITLE
Button shows on top of field

### ISSUE THREAD

**Issue by balderoo** [ibericode/mailchimp-for-wordpress#425]
In my form the 'submit' button appears with a small overlap with the email entry field. 
![screen shot 2017-04-03 at 19 37 44](https://cloud.githubusercontent.com/assets/17065279/24622429/4b55cb38-18a5-11e7-877e-1117a447ebe2.png)
No custom css, just standard styles in the CSS Styles Builder.

Is this a bug or am I doing something wrong?

**Comment by arnelap** [comment]
Seems like your themes CSS is overwriting our CSS. If you have a paid license, please contact support so we can help you over-over-write your themes CSS that is conflicting with the form. 

I will close the issue here as it is not related to development. Thank you!
