### ISSUE TITLE
Improvements to list fetching for MailChimp accounts with many lists.

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/mailchimp-for-wordpress#429]
Right now, we increase the time limit to 600 seconds and fetch all lists at once. 

However, some hosts have different time limits set (eg on server level) making it so that the AJAX call to refresh all MailChimp lists always fails on accounts with a lot of MailChimp lists.

**Comment by dannyvankooten** [comment]
3d47556ac9ffb4505415a0cb5ceb51317906723d will check the return value of `set_time_limit` and use that to determine a sensible list limit. 

4d72e59293464c3dc6ade91cea07e56d5306c9de shows an error message when the AJAX call to refresh lists fails.

**Comment by arnelap** [comment]
"The v3 plugin has no issues - only v4."
please inform https://secure.helpscout.net/conversation/340661883/9974/?folderId=253123
