### ISSUE TITLE
Only load scripts and styles on pages that contain the form

### ISSUE THREAD

**Issue by senlin** [ibericode/mailchimp-for-wordpress#431]
Of course it is possible to dequeue and enqueue the lot in a function of the (child)theme, but in a time where everyone is looking to shave off loading times and not loading redundant scripts, it would be nice if plugins offer that by default.
Thanks!

**Comment by dannyvankooten** [comment]
Hi @senlin,

This should actually already be the plugin's behavior, except for stylesheets (which are disabled by default). JavaScript is only enqueued on pages that actually contain a form.

Are you seeing different behavior and if so, for which stylesheet or script specifically?

**Comment by senlin** [comment]
Hi @dannyvankooten 

The javascripts are enqueued all over the site. I have now added a function that dequeues the javascript and enqueues it again only on the pages I need it for.
And you are right, it is impossible to do the same for the stylesheets.

**Comment by senlin** [comment]
Hi @dannyvankooten 

Actually you are right. Sorry for that.

Is there a way to remove the stylesheets?

**Comment by dannyvankooten** [comment]
No worries @senlin! From the settings or with a filter? From the settings, the following should ensure that no stylesheet is loaded.

- For each of your forms, go to the **Appearance** tab and select "No" for the "Load styles?" setting.
- For each of your integrations, select "No" for the "Load some default CSS?" setting.

That should ensure no stylesheet is enqueued. Let me know if you're seeing other behaviour please.

**Comment by senlin** [comment]
Strange, in the Appearance tab there is no such thing as "Load styles?" and for integrations there is neither such thing.
I'm running latest version: 4.1.1

**Comment by dannyvankooten** [comment]
Hi @senlin,

Sorry, the setting is labeled "Form Style" nowadays. For integrations it is "Load some default CSS" though, but it is positioned on each individual integration's settings page. The following settings should ensure that no stylesheets are loaded by the plugin.

![screenshot from 2017-04-28 10-42-43](https://cloud.githubusercontent.com/assets/885856/25521337/730df1c4-2bff-11e7-86ab-f6fb95431cdf.png)

![screenshot from 2017-04-28 10-42-32](https://cloud.githubusercontent.com/assets/885856/25521345/75d19992-2bff-11e7-9357-568034c86e6c.png)
