### ISSUE TITLE
4.1.1 Ninja forms integration broken

### ISSUE THREAD

**Issue by drummergirlclaire** [ibericode/mailchimp-for-wordpress#432]
with 4.1.1 the Ninja forms integration has broken. The Mailchimp Action has disappeared and is no longer functioning.

**Comment by dannyvankooten** [comment]
Hi @drummergirlclaire,

Nice catch, can you please try the latest development version of the plugin to see if that fixes your issue? [You can download it here](https://github.com/ibericode/mailchimp-for-wordpress/archive/master.zip).

Thanks in advance!

**Comment by drummergirlclaire** [comment]
Works great with this version! Thanks!
Claire



On Friday, April 28, 2017, 4:40:53 AM EDT, Danny van Kooten <notifications@github.com> wrote:
Hi @drummergirlclaire,

Nice catch, can you please try the latest development version of the plugin to see if that fixes your issue? You can download it here.

Thanks in advance!
