### ISSUE TITLE
Problem with images

### ISSUE THREAD

**Issue by camo888** [ibericode/mailchimp-for-wordpress#433]
I can't receive the images in the newsletter, and I found something strange in the code:

> <description><![CDATA[<p><img class="wp-image-7930 size-full aligncenter" src="http://lisalindblad **cymbalta 60 mg** .com/wp-content/uploads/2016/11/Dscf2260-WG-e1479239613268.jpg” alt=”dscf2260-wg” width=”500″ height=”380″ /> I have a collection of shoes gathered over the course of many years from around the world. They are exotic, beautiful, charming, odd. That is part of their appeal, but they have a deeper meaning for me. They are a reminder that man was, originally,… Read more »</p>
> <p>The post Well Shod appeared first on Lisa Lindblad Travel Design.</p>
> ]]></description>>

What it the cymbalta 60mg and why is in there?? That thing is breaking the image line and don't let send any image.

Any idea??

**Comment by dannyvankooten** [comment]
Hi @camo888,

Where are you seeing this? On your website or on your newsletter? I have no idea what the "cymbalta 60 mg" line does there, I think you can just remove it. That said, I am not entirely sure if and why this is related to the MailChimp for WordPress plugin though.

**Comment by camo888** [comment]
Hi @dannyvankooten ,

You can see the code here http://lisalindblad.com/feed/

**Comment by dannyvankooten** [comment]
Hi @camo888,

It seems that your post content is broken. If you go to the actual post here, you will see the same issue: http://lisalindblad.com/blog/well-shod/ .

I think that if you edit the post and switch to "HTML" mode then you can remove the image and re-add it to fix this issue. It's not related to our plugin though, so I'm closing this issue.

Good luck!
