### ISSUE TITLE
Error Code 

### ISSUE THREAD

**Issue by mikeshook** [ibericode/mailchimp-for-wordpress#434]
I've installed the plugin and am pretty sure I have the right API code and everything set up clearly but I continue to get "oops...something went wrong" when trying subscribe through the bar. See www.hopefosterhome.com

**Comment by dannyvankooten** [comment]
Hi @mikeshook,

If you go to **MailChimp for WP > Other**, does the debug log on that page show any detailed error messages? Thanks in advance!

**Comment by mikeshook** [comment]
Hey solved the problem for me - it said no list selected (rookie error!)

Thanks,

**Comment by dannyvankooten** [comment]
Glad that helped @mikeshook! Thanks for letting us know.
