### ISSUE TITLE
Only load styles on pages that contain the form (2)

### ISSUE THREAD

**Issue by senlin** [ibericode/mailchimp-for-wordpress#435]
Not sure why [this issue](https://github.com/ibericode/mailchimp-for-wordpress/issues/431) was closed?

In hist last reply @dannyvankooten claims there is Form Style setting, but on my end I cannot find anything that even remotely resembles it:

![image](https://cloud.githubusercontent.com/assets/650066/25525181/2b1d47d6-2bfd-11e7-95d0-5913bfb41424.png)

Please do explain and it would be nice to not close a thread before the user has confirmed the issue is in fact solved...

**Comment by dannyvankooten** [comment]
Hi @senlin,

The setting is located on the "Appearance" tab.

**Comment by senlin** [comment]
On your screenshot in the other thread it is not and I'm afraid it is neither on the site I am taking the screenshot of:

![image](https://cloud.githubusercontent.com/assets/650066/25525292/a6e4f0a8-2bfd-11e7-89da-160f364ecd09.png)

**Comment by senlin** [comment]
and the dropdown menu has the following:
![image](https://cloud.githubusercontent.com/assets/650066/25525338/dc49e5d2-2bfd-11e7-816e-fd22ffb6c133.png)

**Comment by dannyvankooten** [comment]
Hi @senlin,

That setting is the one you're looking for. Setting the "Form Style" to "inherit from active theme" will make sure no special stylesheets are loaded.

**Comment by senlin** [comment]
Ah, phew, finally. Thanks, I'll try it out.
