### ISSUE TITLE
Mailchimp for WP Error "Service Unavailable"

### ISSUE THREAD

**Issue by Jake42989** [ibericode/mailchimp-for-wordpress#437]
Hello, 
I'm having issues getting my Mailchimp plugin to connect to my wordpress site using an API code. Any idea how to resolve this issue? See attached screenshot. 
<img width="1438" alt="screen shot 2017-05-04 at 8 12 56 am" src="https://cloud.githubusercontent.com/assets/28400060/25713642/3f547998-30aa-11e7-9ca8-ec924f45f79c.png">

**Comment by dannyvankooten** [comment]
Hi @Jake42989 ,

This usually means that the MailChimp firewall (Akamai) has blocked your requests and normally this should resolve itself automatically. Does your connected MailChimp account have a huge number of lists by any chance?

**Comment by Jake42989** [comment]
No. I just setup my mailchimp account. Haven't made any lists or anything
like that. Any ideas how to resolve the issue?

**Comment by dannyvankooten** [comment]
Thanks @Jake42989. Trying to figure out what exactly is causing this. Are you hosted with GoDaddy then?

**Comment by Jake42989** [comment]
Yes, I'm using Godaddy. Thank you very much for your help.

**Comment by dannyvankooten** [comment]
Hi @Jake42989,

Thank you. So far the only returning thing with this issue is that it only seems to happen on GoDaddy. We've had numerous users ask GoDaddy to to do some digging but nothing that yielded any results. The error returned by MailChimp usually means that the IP address that is making the request (your website) is (temporarily) blacklisted by the MailChimp firewall.

We've been unable to come up with a clear fix for this yet but I would ask GoDaddy if they can move you to a new server, as that would get your server a new IP address which hopefully won't be blacklisted by Akamai.

I wish this were easier but this really seems to be something on GoDaddy's side...

**Comment by cinchnz** [comment]
It's been ongoing issue for several days now. And it happened to me in the past too. This problem makes me feel that MailChimp is totally useless. I spoke to my hosting provider (Bluehost), and they said that when webmail works there is no issue with the server, so it is not coming from your hosting side. Server is sending request to MailChimp but it is failing to connect so it could be the failure of MailChimp. Their server is having a temporary hiccup or that you've been blocked by the firewall that MailChimp uses. The best option they  suggested is get get in touch with the MailChimp team to ask them to look into the account. Free MailChimp accounts do not have online support like email or chat, only KBs, but it is useless too in this case.
Seriously thinking of an alternative, too often this problem happens.

**Comment by Jake42989** [comment]
Thank you very much. I am thinking mailchimp is useless as well. I might
just look for an alternative at this point. Really appreciate your help.

**Comment by j-greig** [comment]
I'm also getting this error. I have a paid Mailchimp account, and my site is on MediaTemplate Wordpress hosting.

**Comment by dannyvankooten** [comment]
Hi @j-greig,

This usually means that your server is blacklisted by Akamai, the firewall service that MailChimp is using. We haven't heard conclusive results of how to fix it, but either of the following methods should work:

- Obtaining a new API key in your MailChimp account and using that to connect instead.
- Asking your webhost (MediaTemple in your case) to assign a new IP address to your server.

**Comment by j-greig** [comment]
Thanks for the super-fast response @dannyvankooten 👍 

I've switched to a new API key but still get the same error.

Just did the `curl -v https://usX.api.mailchimp.com/3.0/?apikey=test` thing, and can see my account details etc being successfully returned.

(Will also ask MediaTemple for new IP but not sure how long that will take)

**Comment by j-greig** [comment]
Update: I double check the curl query was being received by Mailchimp and all is good... they asked if the request could somehow be coming from a different server... and could I send them a verbose Curl request?

**Comment by arnelap** [comment]
Could this statement at the end of the cURL -v be related:

{"rel":"ping","href":"https://us6.api.mailchimp.com/3.0/ping","method":"GET","targetSchema":"https://us6.api.mailchimp.com/schema/3.0/Ping/Namespace.j-bash-4.2$ curl -v https://us6.api.mailchimp.com/3.0/?apikey=****************************cfpacket_write_wait: Connection to ********: Broken pipe

**Comment by dannyvankooten** [comment]
Hi @j-greig,

What I've sometimes seen is that hosters proxy all requests coming from PHP-CURL through a different server, probably to apply some security filtering. 

So it could very well be that the CURL (cli) command is coming from your actual server whereas the PHP-CURL command is proxied through another first, but only MediaTemple will know. GoDaddy does this as well, for example.

**Comment by j-greig** [comment]
Just checked with MT support and they said...

> On Managed Wordpress, Curl commands run directly to your Wordpress site, they are not proxied through another server.

**Comment by j-greig** [comment]
UPDATE: just tested MC4WP on the other website I have hosted on the same MT account, and it's connecting/working just fine. 

greig.cc / 166.62.108.22 / not working
cyclelove.cc / 45.40.155.145 / working

**Comment by dannyvankooten** [comment]
Thanks for the extensive testing @j-greig. I wish this were something we could do something about from in the plugin, but I'm afraid it really is due to your server IP / configuration hidden in one of the many layers that come to play when issuing a request to a remote server...

I guess the only thing left to test is try and issue a request to MailChimp's API server through PHP CURL (raw) and then another through the WP HTTP api. Are multiple IP's pointing to your server perhaps?

PHP CURL
```php
$curl = curl_init();
curl_setopt_array($curl, array(
    CURLOPT_RETURNTRANSFER => 1,
    CURLOPT_URL => 'https://usX.api.mailchimp.com/3.0/?apikey=test',
));
$resp = curl_exec($curl);
curl_close($curl);
var_dump($resp);
```

WP HTTP API
```php
$resp = wp_remote_get('https://usX.api.mailchimp.com/3.0/?apikey=test');
var_dump($resp);
```

**Comment by j-greig** [comment]
Thanks @dannyvankooten.

http://greig.cc/mc4wp_test_curl.php gives me a "Request Blocked" error message, which I've reported to MailChimp. 

Your `wp_remote_get` script gives me a http 500 error, which I haven't been able to fix yet...

**Comment by dannyvankooten** [comment]
Hi @j-greig,

The HTTP 500 error is the same error as our plugin is getting, so there you have it. The limited information is also why it's hard to pinpoint what exactly is causing it, but it's not in the plugin, that's for sure. :cry:

**Comment by j-greig** [comment]
And.. it's working again! No thanks to Mailchimp or MediaTemple. Super weird. Thanks for all the tips @dannyvankooten

**Comment by j-greig** [comment]
And... it's stopped working again :(

**Comment by j-greig** [comment]
Update: MC4WP works fine when I clone my site to a staging server. MediaTemple support say...

`At this time we have not heard of any wide spread issues with the use of MailChimp plugins on the WordPress Hosting service.  If it is working with the same theme and plugins on a staging site created on the WordPress Hosting service, it should work on the primary site. The staging site would send using the same IP as the primary instance on the site/installation, so it should be effected by any IP blocklisting of the server IP address.

You may need to remove and recreate the site on the WordPress Hosting service to provision a new site/installation on the service to resolve any errors that may have occurred when the site/installation was originally created.

To get a different IP address on a (mt) Media Temple service, you would need to look into one of the other hosting services like the Grid or DV Server offerings.  There is no way to have a new IP address applied to the WordPress Hosting service sites.`

**Comment by dannyvankooten** [comment]
@j-greig :cry: 

Could it be that MediaTemple is rotating IP Addresses on the hosting plan you're on? I have no clue what it could be, but it's definitely something on their end unfortunately, either in the connection to MailChimp being established or in the connection to MailChimp being blocked because of firewalls (and thus IP addresses). I wish it weren't...

**Comment by j-greig** [comment]
@dannyvankooten I think you could be right... for the record it's been working fine again for the past month :)

**Comment by arnelap** [comment]
We've been working on adding more detailed error messages for these problems. In the next version you will see what is blocking the connection and even get a reference number to contact MailChimp support with.

**Comment by amouratoglou** [comment]
same happens to me... any solution? I'm on bluehost... used to work fine ... not anymore. which alternative exists to manage email newsletters? free mc no support, that makes it hard to debug.

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp

**Comment by Somebodyxhere** [comment]
I am also facing the same issue .

@dannyvankooten can Akamai be notified about the issue and they can take care of it so it doesn't happen to whole the wordpress community.. :/
