### ISSUE TITLE
[input type="email"] Unable to type text on mobile 

### ISSUE THREAD

**Issue by Acapucho** [ibericode/mailchimp-for-wordpress#438]
Hello, I just noticed a small problem. For some reason it is impossible to type his mail on mobile. I select the "your e-mail" field, my keyboard appears, I type but nothing is displayed. Can someone help me ?

Here is the form code : 
```
<div class="row">
<div class="col span_12">
<p>
    <label>Ton e-mail :</label>
    <input type="email" name="EMAIL" required="">
</p>
</div>
</div>
<div class="row">
<div class="col span_8" style="padding-top: 10px;">
<p>    
    <label>
        <input name="MMERGE3" type="checkbox" value="beta"> <span style="font-size: 14px;">inscrivez-moi aussi pour participer aux premiers béta-tests du jeu.</span>
    </label>
</p>
</div>
<div class="col span_4">
	<input type="submit" value="Suivre l'actu de Qolonis" />
</div>
</div>
```

and here is the form : https://qolonis.com/fr/

**Comment by Acapucho** [comment]
Fix the problem happens on mobile and tablet ios and safari

**Comment by dannyvankooten** [comment]
Hi @Acapucho,

Is the field white on your mobile or does it have a transparent background? Are you sure that the text isn't just invisible, you can test this by typing a valid email address and seeing if the form submits properly.

**Comment by Acapucho** [comment]
Hi @dannyvankooten the backgrounf is transparent. I've try to type some texte and validate but the field is empty and validation is impossible whithout email.

**Comment by arnelap** [comment]
Hi,

We use Git issues only for bugs and feature requests.

Please create a support ticket here: https://wordpress.org/support/plugin/mailchimp-for-wp
Please include a link to a live website where we can test the form. 

Thank you!
