### ISSUE TITLE
Interest Groups for Ninja Forms

### ISSUE THREAD

**Issue by stevenkellow** [ibericode/mailchimp-for-wordpress#439]
The interest groups container for the MailChimp action of my Ninja Forms displays nothing. My list has an active interest category with two options inside it.

Form is here: [http://www.obair.stevenkellow.com/newsletter/](http://www.obair.stevenkellow.com/newsletter/) with the "Language" field being the one I want to map to an interest category.

MailChimp for WordPress version: 4.1.2
Ninja Forms version: 3.1.2
PHP version: 5.6.29
WordPress version: 4.7.5

**Comment by arnelap** [comment]
you can use this code snippet: https://github.com/ibericode/mc4wp-snippets/blob/master/integrations/wp-registration-form/add-to-grouping.php

Don't forget to change the integration slug to ninja forms: https://github.com/ibericode/mc4wp-snippets/blob/master/integrations/integration-slugs.md

Hope that helps. If you have any questions, please let us know!
