### ISSUE TITLE
Mailchimp for WP not redirecting to URL unless signed in

### ISSUE THREAD

**Issue by DecoMeOut** [ibericode/mailchimp-for-wordpress#440]
I just relaunched the website www.rawbeautytalks.com with a bunch of updates. One of the major ones involved using Mailchimp for WP Premium and Boxzilla to capture email sign ups and then redirect to a URL where users can download a free ebook. This system was working perfectly in all my tests. But then I signed out of WP and the "sign up" button doesn't do anything; it doesn't have a success message, error message, or redirect anywhere. I have removed the popup for now so users are sent directly to the download page without any email capture (not at all ideal). Please advise how to make this system work for users who aren't signed into Wordpress (i.e. everyone!)

**Comment by DecoMeOut** [comment]
This turned out to be the plugin Boxzilla that was causing the issue.

**Comment by dannyvankooten** [comment]
Thanks @DecoMeOut. That plugin is actually also built by us so I'd still love to see if it's an issue we can do anything about. How are you showing the form inside your Boxzilla box?
