### ISSUE TITLE
Oops. Something went wrong. Please try again later.

### ISSUE THREAD

**Issue by cindyhangelo** [ibericode/mailchimp-for-wordpress#448]
Get a error message when someone tries to sign up to the newsletter. All of the settings in the mailchimp plugin are correct and it is activated.

![error](https://user-images.githubusercontent.com/29524156/27263875-dab3d954-546a-11e7-83fa-bf3b3b532238.png)

**Comment by dannyvankooten** [comment]
Hi @cindyhangelo,

Does the debug log on the MailChimp for WP > Other page show you any more detailed error message? Our [knowledge base](https://kb.mc4wp.com/fix-the-oops-something-went-wrong-error/) should contain some helpful pointers on how to fix this error.
