### ISSUE TITLE
Form Submission Takes User to Blank Page

### ISSUE THREAD

**Issue by joeyhendrickson** [ibericode/mailchimp-for-wordpress#450]
It was working... now it's not. After submission, the user gets a confirmation. However, they don't get access to the link the form is supposed to redirect to (tried mailchimp link, mediafire.com link, etc.)

I've been through the settings on the plug-in several times and everything looks normal (screen shots attached).

<img width="1041" alt="screen shot 2017-06-29 at 4 26 19 am" src="https://user-images.githubusercontent.com/15669463/27679742-9559d71c-5c87-11e7-96fb-45f405c43c63.png">
<img width="960" alt="screen shot 2017-06-29 at 4 57 56 am" src="https://user-images.githubusercontent.com/15669463/27679743-955a5962-5c87-11e7-9500-c8f863a266f1.png">
<img width="921" alt="screen shot 2017-06-29 at 4 58 09 am" src="https://user-images.githubusercontent.com/15669463/27679744-955ab5a6-5c87-11e7-8542-dfad07603805.png">

**Comment by joeyhendrickson** [comment]
Albeit, there is domain forwarding happening... mostproductionbangfromeverybuck.com and productionbangfromeverybuck.com both point to a landing page with the same mailchimp plugin.

**Comment by arnelap** [comment]
Hi,

Everything seems to be working as it should, when the user submits the form they are forwarded to 
 eepurl.com/cPhaiP wich seems to contain another MailChimp form.

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp

Hope that helps! 

Kind regards,
