### ISSUE TITLE
Subscription form - reload page after sign-up

### ISSUE THREAD

**Issue by agispas** [ibericode/mailchimp-for-wordpress#451]
Hi there, 

I have integrated a subscription form but after I subscribe the page gets reloaded. Is there any way to not reload the page and to this via AJAX? 

Thanks!

**Comment by dannyvankooten** [comment]
Hi @agispas,

Yes, definitely. This is actually one of our [premium features](https://mc4wp.com/premium-features/), which you can get for a small fee. It's how we are able to sustain development of the free plugin.

That said, the plugin is built in such a way that everything can be coded with the free plugin as well, it's just gonna take some code. The Premium plugin is just an add-on plugin that provides this code for you, but any developer should be able to write this part for you.

Cheers!
