### ISSUE TITLE
MailChimp for WP Plugin Widget in Footer NOT working

### ISSUE THREAD

**Issue by BLUX88** [ibericode/mailchimp-for-wordpress#453]
HELP PLEASE!

I installed MailChimp for WP and put it in a widget in the footer of my site (Wordpress- Highend Theme). I have connected the API, chosen a valid list and am still unable to enter an email into the widget form and have it subscribe. Error message reads "Please select at least one list" even though I have already selected a list. Any ideas? 

THANKS!

**Comment by dannyvankooten** [comment]
Hi Blux,

Do you have a link to your site? And are you sure that you selected a list on the **MailChimp for WP > Forms > Your form > Settings** page?

**Comment by BLUX88** [comment]
Hi Dannyvankooten,

Thank you for the help. I'm positive I selected a list on the MailChimp for WP > Forms > Your form > Settings. Here is the link to my site:
http://breyasdevelopmentsite.com/

**Comment by dannyvankooten** [comment]
Hi @BLUX88,

That is strange. Do you have any other plugins activated on your site that could be modifying our plugin's behavior in any way? It could be that another plugin is filtering (overriding) the list setting that the plugin is fetching for your form.

A search through your codebase for `mc4wp_lists` would reveal this.

**Comment by BLUX88** [comment]
Hi @dannyvankooten 

Thank you for your input and help! I ended up going with another plugin in the end that works much better and looks more professional.
