### ISSUE TITLE
Fields filled up but registration does not work

### ISSUE THREAD

**Issue by ciaojep** [ibericode/mailchimp-for-wordpress#455]
Hi,
We have an issue. The fields are all compilated but when submitted the form show the "compile all required fields".

**Comment by dannyvankooten** [comment]
@ciaojep Do you have a link to your website?

**Comment by ciaojep** [comment]
Hi, thanks for the answer. The site is this http://www.chiarasinchetto.com/blog-education-finanziaria/ form is in the sidebar.

Thank you

**Comment by dannyvankooten** [comment]
Hi @ciaojep,

If you go to the page where you edit your form, are you sure that you've added all fields which are required in MailChimp to your form? You can recognise these by the red border, and the plugin should be showing you an error that your form is missing required fields.

**Comment by ciaojep** [comment]
Of course, I only have mail as a required field. Until yesterday it worked, only with email field, today I added the name not mandatory and does not work while compiling it. I attach screenshots.
Thank you
![schermata 2017-07-21 alle 12 39 03](https://user-images.githubusercontent.com/2039949/28460276-a0c2596c-6e11-11e7-934f-5a46833b86a7.png)

**Comment by dannyvankooten** [comment]
@ciaojep I think this has to do with the "required" attribute on your interest grouping. Can you please try removing that  & then re-saving the form to see if that solves the issue? Not as a permanent solution but just to confirm my theory.

**Comment by ciaojep** [comment]
@dannyvankooten ok, so it works. How do I set the required checkbox field?

**Comment by ciaojep** [comment]
Ok, I do with 2 radio buttons and I fix it. No problem, and thanks for the support.
g.
