### ISSUE TITLE
Cropped field and layout issue

### ISSUE THREAD

**Issue by wallerspace** [ibericode/mailchimp-for-wordpress#456]
My website URL: 
http://www.wallerspace.com/waiting-list/?preview_id=9365&preview_nonce=999f0ca28e&_thumbnail_id=-1&preview=true

### The issue
Last field that says "Guests" is cropped for whatever reason. Also, my styles do not apply to that one either. Can't scroll either.

### How can we reproduce this issue?
1. Map your form like your MailChimp list
2. Create a form
3. Work on your layout

(See screenshot)
![mailchimp](https://user-images.githubusercontent.com/30358319/28484711-996d5d4c-6e39-11e7-98a7-642c355988ea.jpeg)

Thanks!

**Comment by dannyvankooten** [comment]
Hi @wallerspace,

This looks to be some issue with your theme CSS. Adding the following CSS to your website should fix this.

```css
.mc4wp-form select {
    height: auto;
}
```

A plugin like "Simple Custom CSS" could be of help here, or you can simply add it to your theme stylesheet through the **Appearance > Editor** page.
