### ISSUE TITLE
Support AMP 

### ISSUE THREAD

**Issue by arnelap** [ibericode/mailchimp-for-wordpress#457]
MC4WP gives errors on AMP compatibility: https://search.google.com/test/amp

Please inform: 
https://secure.helpscout.net/conversation/401579136/11203/?folderId=253120
https://wordpress.org/support/topic/amp-error-invalid-value-for-html-attribute-style-in-tag-label/

**Comment by arnelap** [comment]
https://wordpress.org/support/topic/amp-validation-error-because-of-no-action-xhr-attribute-in-the-form-tag/

**Comment by westonruter** [comment]
@arnelap Hi there. I lead development of the [official AMP plugin for WordPress](https://github.com/ampproject/amp-wp). A support topic regarding your plugin was added to the AMP plugin forum which I was helping to troubleshoot: https://wordpress.org/support/topic/form-error-on-2-pages/

I'd be happy to assist you with adding AMP compatibility for your plugin.

**Comment by claudiulodro** [comment]
@arnelap I have a PR to add AMP-compatibility to MC4WP at https://github.com/Automattic/newspack-plugin/pull/402/. We would definitely prefer to have this enhancement upstream so that the wider community benefits from it. Do you want the improvement in this plugin? I can open a PR if so.

**Comment by dannyvankooten** [comment]
Hey @claudiulodro,

That'd be very welcome, I'd love to take a look and have this in the plugin. Already went through your code real quick and it looks good to me at first sight.
