### ISSUE TITLE
Additional Fields Won't Add to Form

### ISSUE THREAD

**Issue by jmattj** [ibericode/mailchimp-for-wordpress#459]
My website URL: 
http://yodega.com/seller-policy/

### The issue
Hi, the additional fields (beyond email address) that I add don't seem to show up in the form. Any recommendations?

This is displayed as a widget.

Thanks

### Technical info
* WordPress version: 4.8
* MailChimp for WordPress version: 1.5.7

<img width="1028" alt="screen shot 2017-07-25 at 10 15 42 pm" src="https://user-images.githubusercontent.com/17982408/28601892-d72993d8-7188-11e7-8e65-95b8c6e0f183.png">
<img width="514" alt="screen shot 2017-07-25 at 10 15 22 pm" src="https://user-images.githubusercontent.com/17982408/28601891-d7289c80-7188-11e7-91ab-ac32939d871f.png">

**Comment by dannyvankooten** [comment]
Related to #458
