### ISSUE TITLE
[2017-08-02 11:05:11] ERROR: Form 411 > MailChimp API error: 404 Not Found. The requested resource could not be found.

### ISSUE THREAD

**Issue by hdsears1** [ibericode/mailchimp-for-wordpress#462]
My website URL:  awellpacedlife.com

### How can we reproduce this issue?
1.
2.
3.

**Comment by dannyvankooten** [comment]
Hi @hdsears1,

Can you please try going to **MailChimp for WP > MailChimp** and then click the "Renew Lists" button there. Then, go to your form settings and re-select the list to subscribe. After saving your form settings, the error should be resolved.
