### ISSUE TITLE
Style in Mail Chimp changes in transition

### ISSUE THREAD

**Issue by jevanow2017** [ibericode/mailchimp-for-wordpress#463]
My website URL: [https://www.kristystarr.com] (https://www.kristystarr.com)

### The issue
The changes that I am making in Mail Chimp are also not coming across to the MC to WP plugin. I click on the particular list I am referring to and it doesn't make a difference on style, colors, etc.

### How can we reproduce this issue?
1. Go into the plugin on WP Dashboard
2. Access the Mail Chimp account to make sure I am not missing something
3.

### Technical info
* WordPress version: 4.8.1
* MailChimp for WordPress version: Version 4.1.6
* Relevant plugins in case of a bug: Mail Chimp for Wordpress, Page Builder
<img width="1329" alt="mail chimp starr 1" src="https://user-images.githubusercontent.com/30781726/29007100-26b71e8a-7ab1-11e7-8859-143c5ed47389.png">
<img width="950" alt="mail chimp starr 2" src="https://user-images.githubusercontent.com/30781726/29007101-26c4e1e6-7ab1-11e7-8b37-c439354617e9.png">

**Comment by jevanow2017** [comment]
The top image is the style I want, the bottom image is what is loading into the Page Builder widget.

**Comment by dannyvankooten** [comment]
Hi @jevanow2017,

Our plugin caches your MailChimp information for a few days as not to slow down your website. After making some changes in your MailChimp account, please go to the **MailChimp for WP > MailChimp** page and click the "Renew Lists" button there to fetch your latest account info.

Hope that helps!
