### ISSUE TITLE
Submit button's position

### ISSUE THREAD

**Issue by LysaRich8348** [ibericode/mailchimp-for-wordpress#464]
My website URL: http://lysarich.com/freegift/

### The issue
I can't change the position of the submit button in the MailChimp for WP form. Now this button is above far right and on the right corner of the first list entry field of my form. I tried several options like adding <div> or <button>, but nothing helped so far, to get it at the bottom of my form.

### How can we reproduce this issue?
1. Open plugin MailChimp for Wordpress
2. Choose the option "Forms" 
3. Click on the option "Submit button"
4. Save changes and look at the result
5. 

### Technical info
* WordPress version: 4.8.1
* MailChimp for WordPress version: 4.1.6
* Relevant plugins in case of a bug: not relevant

**Comment by dannyvankooten** [comment]
Hi @LysaRich8348,

Unfortunately the position of this submitt button is mostly determined by your active theme. I tried looking at your site but it seems that the "freegift" page is not yet published, so I can't access it.

Have you tried going into the "Appearance" tab of your form settings where you can choose one of several form styles? It _could_ be that selecting one of these form styles will get the form to look like what you want it to already.
