### ISSUE TITLE
Unsubscribe automatically?

### ISSUE THREAD

**Issue by BBarbadoSS** [ibericode/mailchimp-for-wordpress#465]
When changing my name in my Wordpress profile, it changes too in MailChimp but unsubscribes me automatically.

**Comment by dannyvankooten** [comment]
Hi @BBarbadoSS,

Is this using our other plugin MailChimp User Sync? What are your settings like? Does your user account still fit the selected role criteria? DId you change just your name or also your email address? What does the debug log on the **MailChimp for WP > Other** page state?

**Comment by BBarbadoSS** [comment]
Hi there,

Yes. It's the User Sync plugin.
Settings: http://imgur.com/a/pN276
Debug log: Nothing on there

Only changed my first name.

**Comment by BBarbadoSS** [comment]
Hi Danny,

Can you fix this one, please?

**Comment by dannyvankooten** [comment]
Hi @BBarbadoSS,

Sorry for my late reply. Can you please try enabling all debug logging on the **MailChimp for WP > Other** page (by selecting the "Everything" option) and then keeping an eye on when the various actions are getting triggered? I have been unable to replicate this issue myself..

**Comment by arnelap** [comment]
If you can confirm a bug in UserSync you may post that here: https://github.com/ibericode/mailchimp-user-sync/issues

For any other support issues I'm sorry to tell you we no longer provide free support for this add-on, but you can always ask other users for help here: https://wordpress.org/support/plugin/mailchimp-sync/

Thanks!
