### ISSUE TITLE
Mailchimp & contact form 7 problem

### ISSUE THREAD

**Issue by vinolio** [ibericode/mailchimp-for-wordpress#466]
My website URL: vinolio.gr

### The issue
Senders from contact form 7, does not getting into the connecting mailchimp list. I tried to renew but nothing! Only 1 saved...

### How can we reproduce this issue?
1.
2.
3.

### Technical info
* WordPress version:
* MailChimp for WordPress version:
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
Hi,

Please make a ticket on the wordpress.org forum. If you can include screenshots of your MailChimp for WP > Integrations > Contact Form 7 screen that would be helpful. 

- Is the integration set to implicit? I don't see a checkbox on the form. 
- Did you search the list for the email? The displayed totals are not always up to date in MailChimp
- Any error in the log on the "Other" page of our plugins settings? 
- Any required fields for the list besides email?
- Did you test with opt in on as well as off?

Please note we use Github for technical issues. For faster customer support you can make a topic at wordpress.org/support/plugin/mailchimp-for-wp

Hope that helps!

Kind regards,
