### ISSUE TITLE
NOT ABLE TO CREATE A FORM

### ISSUE THREAD

**Issue by hablandodelmir** [ibericode/mailchimp-for-wordpress#468]
My website URL: www.hablandodelmir.com

### The issue
I´m trying to integrate my mail list with wordpress using your plugin, but when I try to create it, the buttons doesn`t work (for example, I try to add the field "Name" and when I customize it and hit the "add to form" button, it doesn´t work

### How can we reproduce this issue?
1.
2.
3.

### Technical info
* WordPress version: latest
* MailChimp for WordPress version: latest
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
Please make sure you have a list selected under the form settings, and that the list has fields. 
You can check your connection with the MailChimp API in the MailChimp for WP > MailChimp screen. 

You can also click "renew lists" there and see if the lists and the fields are pulled successfully. 

Please note we use Github for technical issues. For customer support you can make a topic at wordpress.org/support/plugin/mailchimp-for-wp

Hope that helps! 

Kind regards,
