### ISSUE TITLE
Frontsnames disappear from list

### ISSUE THREAD

**Issue by BSchieke** [ibericode/mailchimp-for-wordpress#471]
My website URL: www.moedmoeders.nl

### How can we reproduce this issue?
1. sign in for 'Chillax' on moedmoeders.nl/chillax
2. check the list Chillax in mailchimp
3.

### Technical info
* WordPress version: 4.8.1
* MailChimp for WordPress version: 4.1.6 (updated today, could the problem be the older version I used? But how can I get back te names?)
* Relevant plugins in case of a bug:

**Comment by dannyvankooten** [comment]
Hi @BSchieke,

Are you using any other plugins that integrate with MailChimp that could be modifying the information?

**Comment by arnelap** [comment]
I suppose it's another plugin overwriting it. 

We use Git issues only for bugs and feature requests.

Please create a support ticket here: https://wordpress.org/support/plugin/mailchimp-for-wp if you still need help on this.

Thank you!
