### ISSUE TITLE
Redirect to URL after successful sign-ups not working properly, redirect to /undefined/ url

### ISSUE THREAD

**Issue by rohitchaudhary701** [ibericode/mailchimp-for-wordpress#472]
My website URL: http://www.memoryhopkinsrealestate.com/zillow-offer/

### The issue
When i submit the popup form this should redirect to a thank you page. I am using "Redirect to URL after successful sign-ups" settings to redirect to this URL http://www.memoryhopkinsrealestate.com/zillow-offer-thank-you/ 
but it takes me here http://www.memoryhopkinsrealestate.com/zillow-offer/undefined

### How can we reproduce this issue?
1. since last update it is happening with me. I have updated the plugin.
2.
3.

### Technical info
* WordPress version: 4.8.1
* MailChimp for WordPress version: 4.1.6
* Relevant plugins in case of a bug:

**Comment by dannyvankooten** [comment]
Hi @rohitchaudhary701,

Are you using our Premium add-on plugin with AJAX setting enabled by any chance? What does your "redirect to URL" setting look like?
