### ISSUE TITLE
MailChimp Form Disappears

### ISSUE THREAD

**Issue by BaderSherbaji** [ibericode/mailchimp-for-wordpress#475]
My website URL: www.generationp.com (coming soon mode activated)

MailChimp Form Keeps on Disappearing from Page

Hello,

Hope you guys are doing well! I've created a form with MailChimp for WP - and I've added the shortcode into my page. The form shows and seems to be fine, however when I check later on (a day or so) it disappears. It's completely gone from the page. I am adding it in Classic Mode (Visual) and not (Text), and I also haven't set up an account for MailChimp as I just want it for show for now. 

Could either of those reasons be why it's disappearing, or is there something else? Please help me out! 

EDIT: When I click sign up, it takes me to a page that does not exist even though I have written in the plugin settings that there must not be any redirections. I do not get the message that says I have successfully signed up or anything, however I do get an email asking me to confirm subscription.

### Technical info
* WordPress version: Latest Version
* MailChimp for WordPress version: Latest Version
* Relevant plugins in case of a bug:

**Comment by dannyvankooten** [comment]
Hi @BaderSherbaji,

That is very weird, as long as you are using the shortcode then it shouldn't matter whether you are using Visual or Text mode.

Do you have any caching plugins enabled by any chance? Could you post a list of your active plugins here so I can take a look at possible culprits?

**Comment by BaderSherbaji** [comment]
Hello! Thank you so much for your reply. Please be advised I have the following caching plugin enabled; Artbees Themes Captcha

Do you think this has anything to do with it? I've noticed that whenever I do any edits to the page, the shortcode disappears. Otherwise, the shortcode does not disappear.

**Comment by dannyvankooten** [comment]
Hi @BaderSherbaji,

That seems to be a "captcha" plugin (to stop spam), not a caching plugin, right?

Could you post a list of all your active plugins here? It must be one of your plugins stripping out the shortcode whenever you try to edit the page.

An alternative method of testing is to disable all of your other plugins and then keep re-activating them one by one while editing your page in between each one. This way you can tell which plugin is triggering the issue.
