### ISSUE TITLE
Clicking Forms Takes Directly to One Form not Form list

### ISSUE THREAD

**Issue by megamorphg** [ibericode/mailchimp-for-wordpress#477]
My website URL: 

### The issue
When I click the form link on the navigation pane or any link to take me there, it just takes me to one of the forms in the system. I want to see the form list so I can make a new form.

### How can we reproduce this issue?
1. Click "Forms" link on navigation pane.
2. It will go directly to one of the forms after URL seems to redirect there.

### Technical info
* WordPress version:4.8.1
* MailChimp for WordPress version:4.1.8
* Relevant plugins in case of a bug:

**Comment by dannyvankooten** [comment]
Hi @megamorphg,

I'm afraid this is default behavior if you are not running [our Premium add-on plugin](https://mc4wp.com/premium-features/). The free plugin only allows for one single form whereas the Premium plugin allows you to have as many forms as you want to.
