### ISSUE TITLE
Can't get subscriber email ids

### ISSUE THREAD

**Issue by galluadmin** [ibericode/mailchimp-for-wordpress#478]
My website URL: www.agapeless.com

### How can we reproduce this issue?
1.
2.
3.

### Technical info
* WordPress version:
* MailChimp for WordPress version:
* Relevant plugins in case of a bug:

**Comment by dannyvankooten** [comment]
Hi @galluadmin,

Do you see any error messages when you go to **WP Admin > MailChimp for WP > Other** and check the debug log on that page? Or do you see an error when submitting the form?

**Comment by arnelap** [comment]
Hi,

We use Git issues only for bugs and feature requests. 

Please create a support ticket here: https://wordpress.org/support/plugin/mailchimp-for-wp

Thank you!
