### ISSUE TITLE
Only see one list/form from list of forms

### ISSUE THREAD

**Issue by Mak-Donuts** [ibericode/mailchimp-for-wordpress#481]
My website URL: johnaleslieparentcouncil.ca

### How can we reproduce this issue?
1.
2.
3.

### Technical info
* WordPress version: 4.8.2
* MailChimp for WordPress version: 4.1.9
* Relevant plugins in case of a bug: ithemes security and backup buddy

**Comment by dannyvankooten** [comment]
Hey @Mak-Donuts 

Do you have [the Premium version of MailChimp for WordPress](https://mc4wp.com/premium-features/) installed and activated? 

The free version only allows for one single form, but I see how the plural "Forms" menu item can be misleading. I have attempted to make that more clear in cfc766ff58bc6139fa4105436e7a1305b17c6eff .

Please know that you can definitely use the single form to subscribe to multiple MailChimp lists at once though.
