### ISSUE TITLE
Integration with AffiliateWP

### ISSUE THREAD

**Issue by arnelap** [ibericode/mailchimp-for-wordpress#484]
Feature request by Florian - https://github.com/AffiliateWP/AffiliateWP
via
https://secure.helpscout.net/conversation/441210809/11761/?folderId=253120

Custom integration should work already.

**Comment by flowdee** [comment]
Would be awesome! :)

**Comment by flowdee** [comment]
Woop woop! Thanks @dannyvankooten  👍
