### ISSUE TITLE
Plugin not working anymore

### ISSUE THREAD

**Issue by cindytremblay** [ibericode/mailchimp-for-wordpress#485]
My website URL: 
Hi, I have been using your plugin for a while and everything was working. But now, it doesn't work anymore. People can't subscribe in the widget.
When I go see in the dashbord, it says it's not connected. I don't understand because I put the API key.

My website is supercardio.ca

### Technical info
* WordPress version: the latest
* MailChimp for WordPress version: the latest
* Relevant plugins in case of a bug:

**Comment by dannyvankooten** [comment]
Hi @cindytremblay,

If you're seeing the "not connected" status on your **MailChimp for WP > MailChimp** settings page then there should also be an error message. What is yours saying?

**Comment by cindytremblay** [comment]
I talked to mailchimp and everything is ok now
ᐧ


N.B. Nous vous invitons à vous inscrire à notre infolettre mensuelle
SuperCardio en cliquant sur ce lien : INFOLETTRE SUPERCARDIO
<http://eepurl.com/bV8nV9>.  En plus de recevoir des séances gratuites
d'entrainement "Supercardio 10Dix, cette infolettre vous informera des
nouveaux articles de notre site SuperCardio, des dates de sortie des
nouveaux programmes, ainsi que des rabais et promotions du mois.

*L'équipe Supercardio*
*supercardio.ca <http://supercardio.ca/>*
Tél. : 514-880-1477

<http://supercardio.ca/>

Cindy Tremblay et Patrick Laserra
Supercardio inc.
C.P. 45 Mercier
Mercier, Qc
J6R 2K6

Si vous ne voulez plus recevoir de message de notre part, n'hésitez pas à
nous en glisser un courriel.


------------------------------
*MISE EN GARDE CONCERNANT LA CONFIDENTIALITÉ **– La présente communication
est confidentielle. Si vous n’êtes pas le destinataire visé, vous êtes par
la présente informé qu’il est expressément interdit d’en dévoiler la
teneur, de la copier, de la distribuer ou de prendre quelque mesure fondée
sur l’information qui y est contenue. Si vous avez reçu cette communication
par erreur, veuillez nous en informer immédiatement par téléphone ou par
courriel et détruire l’original, sans tirer ni conserver de copie. *
------------------------------



2017-10-18 7:13 GMT-04:00 Danny van Kooten <notifications@github.com>:

**Comment by arnelap** [comment]
Thanks for letting us know it was solved after talking with MailChimp support.
