### ISSUE TITLE
Old mail chimp list showing up on website

### ISSUE THREAD

**Issue by bobzules** [ibericode/mailchimp-for-wordpress#486]
My website URL: www.zulescustoms.com

### The issue
When scrolling down to the bottom of my website it shows my area on the right where people can subscribe. The issue is that the list selected shoudl say news and updates not Nick Test email.

### How can we reproduce this issue?
1. I have it clicked on my dashboard as news and updates so its a plugin issue i think
2.
3.

### Technical info
* WordPress version:
* MailChimp for WordPress version:
* Relevant plugins in case of a bug:

**Comment by dannyvankooten** [comment]
Hi @bobzules,

This doesn't sound like an issue in the plugin. You can go to your WP Admin and then visit the **MailChimp for WP > MailChimp** page to view your MailChimp information.

On the **MailChimp for WP > Forms** page you can select the MailChimp list you want to subscribe people to.

Good luck!
