### ISSUE TITLE
Javascript Event not firing in Firefox

### ISSUE THREAD

**Issue by tb9jen** [ibericode/mailchimp-for-wordpress#487]
My website URL: 

http://toolrack9.com/vestly/wp/

I am using the on success javascript event found here:
https://kb.mc4wp.com/javascript-form-events/
 to make a modal pop up after signup, and it works in all browsers except Firefox. 

### How can we reproduce this issue?
1. Try to subscribe via one of the forms. 
2. Check console log, if you don't see "success" or see a modal pop up, it didn't work. 

### Technical info
* WordPress version: 4.7.6
* MailChimp for WordPress version: 4.1.9
* Relevant plugins in case of a bug: Gravity Forms, ACF Pro

**Comment by dannyvankooten** [comment]
Hi @tb9jen,

That is strange, as we removed that option in 6c14a4798fa0c6fba1c6188305750e972836ab27 . Are you sure you're on the latest version of the plugin and that your caches are all emptied?

**Comment by tb9jen** [comment]
Weird, well for whatever reason when I downloaded the master zip on Oct 3 that line was still in there. I just downloaded it again and it's not now, so I'm not sure what's up with that, but I'll see if it fixes my issue.
