### ISSUE TITLE
Pop-Up not working in wordpress

### ISSUE THREAD

**Issue by LOVEKSZ** [ibericode/mailchimp-for-wordpress#488]
My website URL: www.loveksz.com

### The issue

Hello,

I just created my subscriber pop-up in Mailchimp. Then i embedded the code in the 'insert headers and footers' plugin on my wordpress website. However, the pop-up isn't working. Can you please help?

### How can we reproduce this issue?
1. go to loveksz.com to see that the popup isn't working.
2. please contact me so that i can share my screen with you and walk you through the problem
3.

### Technical info
* WordPress version: 4.82
* MailChimp for WordPress version: 
* Relevant plugins in case of a bug: Insert Headers and Footers

**Comment by dannyvankooten** [comment]
Hi @LOVEKSZ,

This doesn't sound like an issue with our plugin as we don't allow for pop-ups in MailChimp for WordPress. Most likely you are referring to the MailChimp pop-up, which is not created or managed by us so unfortunately we can't help you with that. Sorry. :(
