### ISSUE TITLE
Custom Form integration not working

### ISSUE THREAD

**Issue by casserlyprogramming** [ibericode/mailchimp-for-wordpress#489]
### The issue
I have created a custom form for a client that posts to itself with custom fields and pushes to a custom post type. All very custom. the issue is that when I post I also want to sign them up to mailchimp if a checkbox is selected. The check box has the name of mc4wp-subscribe and I have a email, firstname and lastname field on the form too. The post works nicely but there is literally nothing coming through to me from the plugin despite me having the setting all set up in the dashboard. there is not even anything logged despite having logging set to all

### How can we reproduce this issue?
1. create a simple form on a template with a firstname, lastname, email and mc4wp-subscribe fields on the form to post to itself
2. Test that the form actually creates a subscriber on the mailchimp plugin 
3. check logs

### Technical info
* WordPress version: 4.8.1
* MailChimp for WordPress version: 4.1.9
* Relevant plugins in case of a bug: Also using contact form 7 (I am using some classes from that in the form but not in the name fields)

**Comment by dannyvankooten** [comment]
Hi @casserlyprogramming,

Is this custom form created using Contact Form 7? Do you have a link to your site where I can test this form? Does the debug log on the **MailChimp for WP > Other** page state any errors? Do you have a list selected on the **MailChimp for WP > Integrations > Custom** page?

Thanks in advance!

**Comment by casserlyprogramming** [comment]
Hi @dannyvankooten ,

thanks for getting back. I have a list selected on the Integrations->Custom page. The form is created manually but I am putting the classes from contact form 7 in the inputs just to keep consistant formatting without recreating the CSS classes (lazy I know but effective). However, the names on the inputs are all fairly standard and don't include the contact form 7 names. 

There is nothing getting logged at all in the Other tab which is why I feel like I am not hitting the code at all for this plugin (otherwise I'm sure I would get some message logged). 

The site that I am working on is a private client's site. I wouldn't mind sending you the link in a private message if possible? 

Daniel

**Comment by casserlyprogramming** [comment]
Hi @dannyvankooten  - and anyone else who has this problem. I found the issue was that I hadn't added the value="1" to my checkbox input in the html. Although I was getting the posted value correctly the value thing is an important thing to remember. All sorted now - Thanks!

**Comment by dannyvankooten** [comment]
Glad to hear it @casserlyprogramming, thanks for coming back here with the heads up!
