### ISSUE TITLE
Use woocommerce customer data to pre-fill the subscription form

### ISSUE THREAD

**Issue by lvl99** [ibericode/mailchimp-for-wordpress#490]
I want to create a newsletter subscription form which also acts as an update subscription form on my website.

Is it possible to use a customer's existing WooCommerce (or WP user data) to pre-fill the fields? e.g.
```
<div class="form-row">
  <label>City of residence</label>
  <input type="text" name="CITY" value="{user property='billing_city'}">
</div>
```

**Comment by dannyvankooten** [comment]
Hi @lvl99,

Actually, the piece of HTML you posted should already do the trick if the currently logged-in user really has a meta field named "billing_city".

`
{user property='billing_city'}
`

Perhaps in your testing you are attempting this with a user that's not a WooCommerce customer?

**Comment by arnelap** [comment]
Since there have been no replies for awhile I will now close this issue.

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
