### ISSUE TITLE
NOT CONNECTED

### ISSUE THREAD

**Issue by iBrandPazar** [ibericode/mailchimp-for-wordpress#491]
My website URL: china@iBrandPazar.com

Hello,
when i'm putting my mailchimp API i'm getting this message 
Error connecting to MailChimp: 503 Service Unavailable 
Looks like your server is blocked by MailChimp's firewall. Please contact MailChimp support and include the following reference number: Reference Number: 00.1adcf180.1508496054.11541a14

### Technical info
* WordPress version:
* MailChimp for WordPress version:
* Relevant plugins in case of a bug:

**Comment by dannyvankooten** [comment]
Hi @iBrandPazar,

This error means that your server is being blocked by MailChimp's firewall. You can contact MailChimp support and include the following reference number: Reference Number: 00.1adcf180.1508496054.11541a14 

This will allow them to look into things on their end and perhaps unblock your server.

Alternatively, switching to a new webhost or changing IP Address should also do the trick.

Good luck!
