### ISSUE TITLE
top bar doesn't sit on the top on every page

### ISSUE THREAD

**Issue by chrishartmann1** [ibericode/mailchimp-for-wordpress#492]
My website URL: 

As you will see from the attached images, the mailchimp topbar sits perfectly on my homepage but on any other page it drops down over the top menu bar. 

Please advise 

![image](https://user-images.githubusercontent.com/32970660/31845369-d89d8e5c-b5b4-11e7-9a9f-aa817dd5a5e1.png)

![image](https://user-images.githubusercontent.com/32970660/31845374-e172ad1e-b5b4-11e7-83d4-2a08879b9aab.png)

### How can we reproduce this issue?
1.
2.
3.

### Technical info
* WordPress version:
* MailChimp for WordPress version:
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
Hi,

We use Git issues only for bugs and feature requests. 

Please create a support ticket here: https://wordpress.org/support/plugin/mailchimp-top-bar

Please include a link to the website once it is live so we can look into this for you. It's most likely some compatibility issue with your theme's CSS code. 

Thanks!
