### ISSUE TITLE
error when syncing a subscription renewal (Woocommerce subscriptions)

### ISSUE THREAD

**Issue by v2lam** [ibericode/mailchimp-for-wordpress#494]
My website URL: https://aufildureel.com

### The issue
ERROR: E-Commerce: Error adding order #16821. Bad Request. We were unable to process the request. An order with the provided ID already exists in the account.

### How can we reproduce this issue?
1. woocommerce subscriptions installed
2. when a subscription is renewed
3. and order tracking enabled + Include all order statuses

### Technical info
* WordPress version: 4.8.2
* MailChimp for WordPress version: 4.1.10 + premium 3.3.20
* Relevant plugins in case of a bug: MC User Sync 1.5.4 
Woocommerce subscriptions 2.2.13

thanks

**Comment by arnelap** [comment]
I've created a copy of this issue in our private repository of the Premium add-on. Thank you!
