### ISSUE TITLE
Success Message Isn't Appearing After Submission in MailChimp for WP

### ISSUE THREAD

**Issue by Orbkl** [ibericode/mailchimp-for-wordpress#496]
My website URL: https://thebeautyadviser.com/sephora-card-giveaway/

### The issue
Success Message Isn't Appearing After Submission in MailChimp for WP

### How can we reproduce this issue?
1. just fill in the form, the first 2 boxes with your name and email adress. you will see there is no response for succes. I have to mention the double opt in activated.
2.
3.

### Technical info
* WordPress version: 4.8.3
* MailChimp for WordPress version: 4.1.11 
* Relevant plugins in case of a bug:

**Comment by dannyvankooten** [comment]
Hi @Orbkl,

Whenever you submit the form on your site, _something_ is performing a redirect meaning the actual form request is lost in the redirect.

It's hard to say what exactly is causing this redirect, but it is most likely another activated plugin on your site. You could try disabling your plugins one by one to see which one is doing it.

Good luck!

**Comment by Orbkl** [comment]
Hi Danny,

Thanks a lot for your reply!
I forgot to mention: It seemes that some other response messages are working, only the succes message is not working...

**Comment by dannyvankooten** [comment]
Hi @Orbkl,

If you go to your form settings and open up the "Settings" tab, did you enter something in the "Redirect on success" field?

**Comment by Orbkl** [comment]
Yes @dannyvankooten I have entered the same url as the page where the form is located.

**Comment by dannyvankooten** [comment]
Hi @Orbkl,

That's it then. If you want to stay on the same page then you can leave that setting empty. Right now, the plugin is redirect to the same page after each successful submission, therefore not showing a success message.

As a rule of thumb, you should only redirect to "thank you" pages that make it clear the form was properly submitted.

So, emptying that setting will get your success message to appear! Cheers!

**Comment by Orbkl** [comment]
@dannyvankooten HUGE THANKS!!!!!!

I spent the entire night thinking what might be the problem. You're great! 

Have a great day Danny!
Vlad
