### ISSUE TITLE
CF7 integrations not working properly

### ISSUE THREAD

**Issue by CeuxDruman** [ibericode/mailchimp-for-wordpress#497]
My website URL: http://CeuxDruman.com

### The issue
Quite often, when an user submit a CF7 form with mailchimp checkbox included and checked, the plugin throws the next error:
`ERROR: Contact Form 7 > MailChimp API Error: cURL error 6: name lookup timed out.`
Futhermore, that error is also present in the plugin documentation several times (with the DESCONNECTED tag).

It shouldn't be a problem, but it is, because the form shows a green message indicating it was sent correctly. But the suscription wasn't done and, even more, the form data from cf7 wasn't sent...

I don't know if it is a error related to this plugin or to CF7 plugin, but it need to be solved or to throw an error for the user when catching it.

### How can we reproduce this issue?
1. Make a form with contact form 7
2. Add a mailchimp checkbox
3. Send it, it will fail several times (Meaby when the admin didn't logged-in in a while?)
4. You will see the error in the log, but you have not been suscribed and you won't receive the form data.

### Technical info
* WordPress version: 4.8.3
* MailChimp for WordPress version: 4.1.11
* Relevant plugins in case of a bug: Contact Form 7 (4.9.1)

**Comment by arnelap** [comment]
Hi,

The error is saying the DNS lookup failed, meaning there is an issue with your hosting server DNS setup. You can ask your hosting provider about this. 

Using our integrations we can't pass the MailChimp for Wordpress errors back to CF7 as it's all happening in the background. 
For the form data not being send you will have to contact CF7 as that should be a separate process from our integration.

We use Git issues only for bugs and feature requests and are usually not able to respond to support requests posted as Git Issue in a timely manner.

Please create a support ticket here if you need further assistance: https://wordpress.org/support/plugin/mailchimp-for-wp

Thank you!
