### ISSUE TITLE
Mailchimp webhooks not working

### ISSUE THREAD

**Issue by harkirat10** [ibericode/mailchimp-for-wordpress#500]
My website URL: NA

### The issue
Mailchimp User Sync plugin does not reflect email changes from mailchimp. 
When I edit a user email in mailchimp I keep getting a message in the log that says
"INFO: Webhook: No user found for MailChimp ID: c3b507acc6". Apparently if I change the email in mailchimp the id it sends can not be found by the user sync plugin. However if I keep the email the same as in Wordpress and change just the first name/last name in mailchimp the user is found.

### How can we reproduce this issue?
1. Configure webhook for mailchimp list as described here https://kb.mc4wp.com/configure-webhook-for-2-way-synchronizing/.
2.  Edit an email for a user
3. Notice the error show up in the log "INFO: Webhook: No user found for MailChimp ID" (Turn on Logging to 'Everything' in the debug log for User Sync plugin to see the INFO messages)

### Technical info
* WordPress version: Version 4.8.3
* MailChimp for WordPress version: Version 4.1.11
* MailChimp User Sync for WordPress version: Version 1.6 
* Relevant plugins in case of a bug: MailChimp User Sync

**Comment by arnelap** [comment]
Please post it here: https://github.com/ibericode/mailchimp-user-sync/issues
