### ISSUE TITLE
Populate merge tags from WooCommerce registration

### ISSUE THREAD

**Issue by Moorst** [ibericode/mailchimp-for-wordpress#502]
I'm trying to populate some merge tags when a user registers to the site using the woocommerce registration form. I've enabled the integration on the form, and users are subscribed successfully but only with their email address and first name (which  for some reason is being populated by the username).

I found here https://kb.mc4wp.com/fix-the-oops-something-went-wrong-error/ that any merge tags should be prefixed with "mc4wp-", so I've added them as so;

`<input type="text" id="mc4wp-FNAME" name="mc4wp-FNAME">`
`<input type="text" id="mc4wp-LNAME" name="mc4wp-LNAME">`
`<input type="text" id="mc4wp-FULLNAME" name="mc4wp-FULLNAME">`
`<input type="text" id="mc4wp-USERNAME" name="mc4wp-USERNAME">`

but they're not being posted. I still just get the email and incorrect first name coming through.

Am I doing something wrong?

**Comment by Moorst** [comment]
I've since found this https://github.com/ibericode/mc4wp-snippets/blob/master/integrations/woocommerce/send-billing-fields.php, but this isn't working for me either.

I'm posting the same fields as above, with the following in my functions;

`add_filter( 'mc4wp_integration_woocommerce_data', function( $data ) { `
`    // Grab MailChimp field values from the current request`
`    $data['FNAME'] = sanitize_text_field( $_POST['mc4wp-FNAME'] ); `	
 `   $data['LNAME'] = sanitize_text_field( $_POST['mc4wp-LNAME'] ); `
`    $data['FULLNAME'] = sanitize_text_field( $_POST['mc4wp-FULLNAME'] ); `
`    $data['USERNAME'] = sanitize_text_field( $_POST['mc4wp-USERNAME'] ); `
`    // Return the fields so the plugin knows to send them to MailChimp`
`    return $data; `
`});`

**Comment by dannyvankooten** [comment]
Hi @Moorst,

The `mc4wp-` prefix is only supposed to work when you are integrating with custom (HTML) forms, not when using a more specific integration like the WooCommerce registration one. 

The latter filter hook should work but since you are hooking into the "registration" form and not into the "woocommerce checkout" form the hook name is different then what you'd expect.

```php
add_filter( 'mc4wp_integration_wp-registration-form_data', function( $data ) {
   // Grab MailChimp field values from the current request
   $data['FNAME'] = sanitize_text_field( $_POST['mc4wp-FNAME'] );
   $data['LNAME'] = sanitize_text_field( $_POST['mc4wp-LNAME'] );
   $data['FULLNAME'] = sanitize_text_field( $_POST['mc4wp-FULLNAME'] );
   $data['USERNAME'] = sanitize_text_field( $_POST['mc4wp-USERNAME'] );
   // Return the fields so the plugin knows to send them to MailChimp
   return $data;
});
```

Most likely, you will also have to change the `$_POST['mc4wp-FIELDNAME']` references to the correct field names but that part is hard for me to tell without seeing your actual registration form.
