### ISSUE TITLE
Manual sync ignores user starting with Y.

### ISSUE THREAD

**Issue by petergroenewegen** [ibericode/mailchimp-for-wordpress#503]
I've done several manual syncs. It appears that all user with an email address starting with Y are not synced. I don't have users with a Z, but maybe the manual sync just stops at X?

**Comment by dannyvankooten** [comment]
Hi @petergroenewegen,

If you go to the **MailChimp > User Sync** settings page halfway down the page there should be a "Status" heading followed by the user count. Does that count look correct to you?

**Comment by petergroenewegen** [comment]
Hi Danny,

Yes the amount is correct. So yes all users have been synced before. It’s just that when I add an extra field to be synced from wp to mailchimp, and then do a manual sync. Then all users starting with a y don’t get synced. They don’t get the new field data in mail chimp.

**Comment by dannyvankooten** [comment]
Hi @petergroenewegen,

Thank you. I am asking because I am trying to figure out the source of the issue. One more question: if you start the manual sync process the plugin will first print the number of users it was able to retrieve. Do these numbers match up to your actual number of users too?

![image](https://user-images.githubusercontent.com/885856/33552269-a391f532-d8f4-11e7-8643-c403a7598213.png)

**Comment by petergroenewegen** [comment]
No it fetches batches of 100 users. I have 620 users to sync.
Op ma 4 dec. 2017 om 13:11 schreef Danny van Kooten <
notifications@github.com>

**Comment by dannyvankooten** [comment]
Do the users which seem to be skipped show up in the log at all when doing the manual sync?

**Comment by petergroenewegen** [comment]
No, all users up to w are synced. I have 3 users with y. They are not in de
log. I don’t have users with z.



Op ma 4 dec. 2017 om 13:16 schreef Danny van Kooten <
notifications@github.com>

**Comment by dannyvankooten** [comment]
Hi @petergroenewegen,

Thank you for that. I think the plugin is somehow cutting off the list of users it retrieves but am not yet sure how or why it's doing this for you.

Could you post a screenshot of your User Sync settings? I'm especially interested in whether you are filtering on any user role and whether you allowed users to opt-out from their profile page.

**Comment by petergroenewegen** [comment]
I’m on mobile at the moment. So a few mobile screenshots attached...


Op ma 4 dec. 2017 om 13:26 schreef Danny van Kooten <
notifications@github.com>

**Comment by dannyvankooten** [comment]
Hi @petergroenewegen,

Unfortunately, replying to a GitHub issue over email does not include the email attachments.

**Comment by petergroenewegen** [comment]
In that case: I’m syncing all roles and opt-out is off. (I’m not a
commercial website but a community with members)
Op ma 4 dec. 2017 om 13:41 schreef Danny van Kooten <
notifications@github.com>

**Comment by dannyvankooten** [comment]
Probably fixed in commit [ibericode/mailchimp-user-sync#46c6ab2e5f3a7f7bfc3d5d03c136a7e953c9e97c](https://github.com/ibericode/mailchimp-user-sync/commit/46c6ab2e5f3a7f7bfc3d5d03c136a7e953c9e97c)
