### ISSUE TITLE
Soft 404 on form submit

### ISSUE THREAD

**Issue by mattyvee** [ibericode/mailchimp-for-wordpress#504]
My website URL: 
www.bampproject.com
### The issue
Filling out form soft 404s instead of redirecting to the listed redirect page on thank you

### How can we reproduce this issue?
1. go to www.bampproject.com
2. scroll to bottom and fill out form
3. receive 404 from homepage on submit

### Technical info
* WordPress version: most recent
* MailChimp for WordPress version: most recent
* Relevant plugins in case of a bug: none that I know

**Comment by dannyvankooten** [comment]
Hi @mattyvee,

Does your form include a field with a lowercased `name="name"` field by any chance?

**Comment by dannyvankooten** [comment]
Sorry, just realised I could just check this myself since you posted your site URL so it seems like you do. Replacing the following line in your form:

```html
<input type="name" name="name" placeholder="Name" required="">
```

With

```
<input type="name" name="NAME" placeholder="Name" required="">
```

Will solve this. :smiley: Cheers!

**Comment by mattyvee** [comment]
Thanks Danny!

Thanks,

Matthew Vandewouwer
(805) 907-9943
