### ISSUE TITLE
Issue with Tooltip with the WP plugin "MailChimp for WP"

### ISSUE THREAD

**Issue by Julfra** [ibericode/mailchimp-for-wordpress#505]
My website URL: http://business.altertox.be/subscribe/

As you can see on my Mailchimp subscription form, if you check the tooltip, the text is in French ! And I have no idea how to change that. Is it connected to the plugin MailChimp for WP ?
All my website, my theme and my plugins are in English. So why these tooltips in French ?
Thank you in advance for your answer, i'm becoming crazy!

### How can we reproduce this issue?
1.
2.
3.

### Technical info
* WordPress version:Version 4.9.1
* MailChimp for WordPress version:Version 4.1.12
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
For me it's English. Can you try in another browser?

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
