### ISSUE TITLE
Mailchimp sign-up form "unexpected error has occured"

### ISSUE THREAD

**Issue by ciaprior** [ibericode/mailchimp-for-wordpress#507]
My website URL: theblogofalicia.com

### The issue
My mailchimp is integrated, and I received the 'connected' message on my plug in, but when i intert the short code to a widget on my side bar, and try to test it (and other people have tried and emailed me about the issue), it just says 'an unexpected error has occurred" 

### How can we reproduce this issue?
1. go to my home page 
2. type in my email and press submit
3. see the are

### Technical info
* WordPress version: most current 
* MailChimp for WordPress version: 4.1.12
![screen shot 2017-12-17 at 11 56 26 am](https://user-images.githubusercontent.com/18053832/34082201-fd9988aa-e327-11e7-8847-c367e2e6ec0e.png)

* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
That error message does not sound familiar, is it the exact text of the message?

We only use git for development related issues, that is why we were not able to reply to you request here in time and the form seems already deleted from your site. by now.

 For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp

Thank you!

**Comment by ciaprior** [comment]
it is in the sidebar of my site.

[image: Inline image 1]

When I put in an email, this is what I get:

[image: Inline image 2]



This is what my code in my widget is:

[image: Inline image 3]

**Comment by arnelap** [comment]
please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
Thank you.
