### ISSUE TITLE
Button style changes to 'pill style' on mobile for some reason. And field spacing breaks form. 

### ISSUE THREAD

**Issue by amaryana** [ibericode/mailchimp-for-wordpress#508]
My website URL: https://dev.evolutionaryeducation.org/

### The issues
- There two forms on the page, first one 'get connected' opt-in button and at the bottom 'stay connected' bar.
- I've tried to change the spacing between the fields and the button a number of ways but every way 'breaks the form'. Is there a workaround?
- The button style changes from 'stroke' to 'pill' for no reason when compressed on mobile. 

thanks for helping! I've tried everything I can to fix both but nothing I can do. The theme support team said this isn't their problem. Hosting said the same thing. Both sent me to you guys. 

I'll give a 5-star review if you guys can help me here. I'm happy with the plugin other than these two issues. 

### How can we reproduce this issue?
1. Click on the get connected button look at the lack of spacing 
2. Button changes as soon as it’s compressed on the mobile site.

### Technical info
* WordPress version: latest
* MailChimp for WordPress version: 4.1.12 
* Relevant plugins in case of a bug: MailChimp For WP

**Comment by amaryana** [comment]
Fixed the margain-bottom issue with css. 

still need help with the 'pill' button shows up on mobile

**Comment by arnelap** [comment]
These things depend on your theme (in in some cases, on your phone). It's best to ask the theme provider / developer for help directly first, they will know best how to change settings in their theme. If they can't help you you can always get back to us or maybe decide to go for another theme that fits your needs better. 

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp

**Comment by amaryana** [comment]
I fixed it myself.
