### ISSUE TITLE
Array to string conversion in wp-includes\formatting.php on line 1045

### ISSUE THREAD

**Issue by picklaa** [ibericode/mailchimp-for-wordpress#511]
My website URL: -

### The issue
https://i.imgur.com/iTZDZmv.png

### How can we reproduce this issue?
1. create a form then go to "messages"

### Technical info
* WordPress version: latest
* MailChimp for WordPress version: latest
* Relevant plugins in case of a bug: -

**Comment by dannyvankooten** [comment]
Fixed in 77a3755cbe919fba59ad3e7f578598a7d6fb9c0c, we're pushing out an update for this in a few hours!
