### ISSUE TITLE
Gravity Forms Integration Required Field

### ISSUE THREAD

**Issue by arnelap** [ibericode/mailchimp-for-wordpress#513]
a way of making the Gravity Forms ‘Mailchimp’ field ‘required’? The option doesn’t appear when I add the field to my form.
https://wordpress.org/support/topic/gravity-forms-integration-required-field/

**Comment by dannyvankooten** [comment]
Hmm, should be added in b51debfbe7b8615bb02d675c774b41e166e50cf8

**Comment by dannyvankooten** [comment]
![image](https://user-images.githubusercontent.com/885856/34663647-0d91f7d8-f458-11e7-94b8-f67001a66d18.png)

You on the latest version?
