### ISSUE TITLE
Required select field (since 4.1.13)

### ISSUE THREAD

**Issue by arnelap** [ibericode/mailchimp-for-wordpress#516]
Since version 4.1.13, if you have a required interest group of the type SELECT you get the message "Please fill in the required fields marked *" if the interest group is set to be required. Even when an option is selected.

https://secure.helpscout.net/conversation/500085402/12780?folderId=253120

Confirmed on t24356 (lapzor test server).

Removing the required tag will "solve" the issue.

**Comment by hchouhan** [comment]
@dannyvankooten I tested it and still face the same issue.

**Comment by dannyvankooten** [comment]
Fixed in b8dfbfa17fb1351aee245fdf2b7956bcc59b4147, nice catch!

**Comment by arnelap** [comment]
Tested, still same issue;

        <input name="INTERESTS[61e4068e16][]" type="checkbox" value="3670d01bc7"
         required="required"> Will return after post with "Please fill all required fields"

**Comment by dannyvankooten** [comment]
@arnelap Resaving your form should fix the issue.
