### ISSUE TITLE
GitHub vulnerability warning

### ISSUE THREAD

**Issue by moley001** [ibericode/mailchimp-for-wordpress#519]
### The issue
Currently working on a Wordpress project that includes your plugin. After the latest commit I have received a warning email from GitHub about the file "package-lock.json"

The warning is as follows, "We found a potential security vulnerability in one of your dependencies.
The semver dependency defined in package-lock.json has a known high severity security vulnerability in version range < 4.3.2 and should be updated."

### How can we reproduce this issue?
1. Upload to GitHub
2. Allow GitHub to scan files for vulnerabilities 

### Technical info
* WordPress version: 4.9.1
* MailChimp for WordPress version: 4.1.14

**Comment by dannyvankooten** [comment]
Hey @moley001,

We're aware of the issue, it's about a vulnerability in one of the dependencies of our Gulp task workflow so it's really not a big deal and not even relevant if you're only including the plugin in your project yourself.

You can disable these vulnerability reports in your repository settings.

Cheers!
