### ISSUE TITLE
ERRO 28

### ISSUE THREAD

**Issue by xobozi** [ibericode/mailchimp-for-wordpress#520]
My website URL: 

### The issue
I'm having a connection problem "Error connecting to MailChimp: 0 cURL error 28: Connection timed out after 10000 milliseconds"

Image: http://prntscr.com/i0ustd

### Technical info
* WordPress version: last version
* MailChimp for WordPress version: last version
* Relevant plugins in case of a bug: cache, cdn maybe

**Comment by arnelap** [comment]
Most likely a network issue anywhere between your hosting server and MailChimp.

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
