### ISSUE TITLE
Creating a custom response upon submission

### ISSUE THREAD

**Issue by WPMMDEV** [ibericode/mailchimp-for-wordpress#521]
How can I create a custom response upon form submission?

I came across the developer docs, and am trying to make use of the `mc4wp_form_success` action available.

So I'm trying something like:

```
function action_mc4wp( $form ) { 
    echo '<h1>123</h1>';
}; 

// add the action 
add_action( 'mc4wp_form_success', 'action_mc4wp', 10, 1 ); 
```
But I'm not able to get the `<h1>123</h1>` to appear. I'm using ajax submission if that helps.

**Comment by arnelap** [comment]
Why not use the messages you can set under MailChimp for WP > Form > Messages?

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
