### ISSUE TITLE
Redirect ONLY on success

### ISSUE THREAD

**Issue by arnelap** [ibericode/mailchimp-for-wordpress#523]
Right now I'm redirected also when there is the warning "already signed up" and update subscriber is set to no. , that might be intentional but would be nice feature is that's a setting. 

With MailChimp API error: 400 Bad Request. Invalid Resource Your merge fields were invalid.
- FNAME : Please enter a value it also still redirects to success url!

**Comment by arnelap** [comment]
https://secure.helpscout.net/conversation/511017508/12976/?folderId=253125

**Comment by dannyvankooten** [comment]
Duplicate of #518, fixed in d0bb375d9d50192df33f152bf3013bb8e172aa68
