### ISSUE TITLE
Mailchimp For Wordpress - Top Bar - not working. Please help!

### ISSUE THREAD

**Issue by theoutdoorsoul** [ibericode/mailchimp-for-wordpress#525]
My website URL: https://theoutdoorsoul.net

### The issue
The mailchimp top bar is showing up at the top of my website. However, whenever any email address is entered, there is an error as the top bar states "Oops. Something went wrong."

### How can we reproduce this issue?
1. Go to the website https://theoutdoorsoul.net
2. Type in any email address in the top bar
3. Click "Send Me Adventures"

### Technical info
* WordPress version: Version 4.9.2
* MailChimp for WordPress version: Version 4.1.14
* Relevant plugins in case of a bug: MailChimp for WordPress - Top Bar

**Comment by arnelap** [comment]
Please see https://kb.mc4wp.com/fix-the-oops-something-went-wrong-error/

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-top-bar
