### ISSUE TITLE
How to record user consent?

### ISSUE THREAD

**Issue by Mishef** [ibericode/mailchimp-for-wordpress#526]
My website URL: https://www.oil-med.com/petrochemical/en/

### The issue

GDPR is near and I put checkbox button that users need to checked to give us their consent to get emails. How can we record that they subscribe to us. We need proof of that - IP, time/date, etc. in some logs.

### How can we reproduce this issue?
1. Go near the bottom of URL and see subscribe form.
2. When user subscribe where to find that data of his action?

Here is what MailChimp says about that: "You should also ensure that you are keeping accurate records, especially of your subscribers’ and contacts’ consent permitting you to send them marketing emails, store and use their personal data, and any other processing activities which you are undertaking. MailChimp can help you obtain proof of consent and will store a record of your subscribers’/contacts’ consent in your MailChimp account. When you use a MailChimp signup form to add subscribers and contacts to your account, MailChimp records the email address, IP address, and timestamp associated with every subscriber or contact who completes and submits the form, providing you with easy-to-access proof of consent."

I place this code in the bottom of subscribe form code: "
<p>
    <label>
        <input name="_mc4wp_action" type="checkbox" value="subscribe" required=""
        > <span>I would like to subscribe to news and advertising messages from OIL MED.</span>
    </label>
</p>"

### Technical info
* WordPress version: 4.8.5
* MailChimp for WordPress version: 4.1.10

**Comment by arnelap** [comment]
You can either create an interest group and insert that as checkbox, or just create a checkbox that is required (and don't record it as nobody could submit the form without checking it anyway).

If you need more information on how to do this, please created a support request. 

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp

**Comment by Mishef** [comment]
My checkbox is required, but GDPR requires proof of consent in my datebase.
Required data is: when did it happen (date), from which IP and at what time.

How can I achieve that?

**Comment by dannyvankooten** [comment]
Hi @Mishef,

A tad late but as I am working on this now, I just wanted to get back to you on this after all. Our plugin sends the email address, IP address and timestamp to MailChimp which then stores it. This should act as a written record of the explicit consent provided that you are using clear language in your forms.

**Comment by Mishef** [comment]
Hello, @dannyvankooten.
It is necessary to have a record of consent and what the consumer has agreed to at that time.
I have a required checkbox with the following text in my websites "I want to subscribe to news from COMPANY". This is not enough for GDPR, because I need to have information in the database that the user has agreed exactly with this statement on that time of entering his data.

**Comment by dannyvankooten** [comment]
Hi @Mishef,

We send the timestamp, email address and IP address of the user to MailChimp whenever the form is submitted where they store this and belief this should provide a large enough legal basis, but I am not a lawyer so I might be wrong.

If we were to implement a "save consent" feature in the plugin, what would it ideally look like to you? 

A checkbox that has to be ticket and then stores a number of fields in the database? What fields? Should it include the terms that were agreed to and if so, in what format?

Thanks for thinking along here!

**Comment by Mishef** [comment]
In Caldera Forms (plugin I've using for contact and inquiry forms), each field and information is saved in the plugin database. When I create a checkbox, the custom text that the user agrees with is recorded in the database.
