### ISSUE TITLE
reCaptcha not reset / can't show error if redirected to success page

### ISSUE THREAD

**Issue by processguy** [ibericode/mailchimp-for-wordpress#530]
My website URL: actionmap.com

### The issue

The reCaptcha does not reset on successful form submission.  
It requires an F5.  This is not obvious to the user, if they want to submit again, what to do.
If I redirect to a success page, then the user cannot see that there is an error, e.g. email already submitted.
How to resolve the need to reset the reCaptcha, but also be able to show errors.

### How can we reproduce this issue?
1.  Try it on your site
2.
3.

### Technical info
* WordPress version:  updated by WPEnging last week
* MailChimp for WordPress version:  purchased last week
* Relevant plugins in case of a bug:

**Comment by dannyvankooten** [comment]
Hi @processguy,

Are you using our [captcha plugin](https://wordpress.org/plugins/mc4wp-captcha/) to render this reCaptcha field along with AJAX forms in our Premium plugin?

**Comment by processguy** [comment]
Hi,

Thanks for the response.

In response to your question, yes, both.  Please see attachments for
settings.

The form does not reset the reCaptcha on "success", and does not accept the
reCaptcha for a second submit with new data if it is not reset.

/Jim



Jim Johnson
ActionMap Inc.
jim@actionmap.com

**Comment by dannyvankooten** [comment]
Hey Jim,

Nice catch! I just pushed out version 1.1.2 of [MC4WP Captcha](https://wordpress.org/plugins/mc4wp-captcha/#description) where this is fixed.

Cheers!

**Comment by processguy** [comment]
Sweet, works, thanks!

Jim Johnson
ActionMap Inc.
jim@actionmap.com

**Comment by dannyvankooten** [comment]
Glad to hear it Jim! Thanks for letting us know.

If you have a minute to spare, please consider [leaving us a plugin review on WordPress.org](https://wordpress.org/support/plugin/mailchimp-for-wp/reviews/#new-post). It'd be much appreciated!

Have a great weekend.
