### ISSUE TITLE
Broken link to KB article.

### ISSUE THREAD

**Issue by marcomarsala** [ibericode/mailchimp-for-wordpress#532]
My website URL: www.laboratoriocanevari.it

### The issue
When you select a list in any integration, the plug-in tells you to follow this KB article, but the link is broken: https://kb.mc4wp.com/send-additional-fields-from-integrations/

### How can we reproduce this issue?
1. In any integration, for ex. WooCommerce Checkout integration, select a MailChimp List
2. Hit "Save"
3. The infobox shows you the broken link.

**Comment by arnelap** [comment]
https://wordpress.org/support/topic/broken-kb-article/

Hi,

What is the dead link exactly? I just tested all from that screen in the latest version of our plugin and they all worked. Maybe I overlooked this one link? 

You mean the infobox on top, or on the right, or somewhere else?

​Thanks for letting us know!

**Comment by dannyvankooten** [comment]
Hey @marcomarsala,

Thanks for the heads up, you're absolutely right! Please check out [this article](https://kb.mc4wp.com/send-more-woocommerce-fields-to-list/) for now, we'll get that link fixed!
