### ISSUE TITLE
Impossibility to see all the forms in mailchimp for WP

### ISSUE THREAD

**Issue by Jiris5** [ibericode/mailchimp-for-wordpress#534]
My website URL: acomobase.com

### The issue 
**Impossibility to see all the forms in Mailchimp for WP**

### How can we reproduce this issue?
1. Please check as I need to see all the forms, not the one just for newsletter related to Mailchimp.

### Technical info
* WordPress version: 4.8.2
* MailChimp for WordPress version: sorry I can't find
* Relevant plugins in case of a bug:

**Comment by dannyvankooten** [comment]
Hi @Jiris5,

Are you using our Premium plugin? The free plugin can only handle 1 form, whereas the Premium form handles as many forms as you like.

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
