### ISSUE TITLE
Screen goes white when I create a form

### ISSUE THREAD

**Issue by Samazonsmith** [ibericode/mailchimp-for-wordpress#539]
My website URL: www.vishionary.com

### The issue
Now that i've upgraded, the screen goes white when I add a form to a widget or through HTML. Honestly, I could have found a work around for the free version that would't have given me this much trouble. Our theme is Voux.  If this can't be fixed I would like a refund. 
<img width="1336" alt="screen shot 2018-03-02 at 5 43 09 am" src="https://user-images.githubusercontent.com/36988102/36895522-22386812-1ddd-11e8-8a71-b4666ab6e57b.png">

### How can we reproduce this issue?
1. 
2.
3.

### Technical info
* WordPress version:
* MailChimp for WordPress version:
* Relevant plugins in case of a bug:

**Comment by dannyvankooten** [comment]
Hi @Samazonsmith,

Is this after creating a form or or what exactly are you doing when this error occurs? Could you please check what version of MailChimp for WordPress you are on?

Your webhost should have an error log available for you that contains the exact error message of what is going wrong. With that error, this should be a very easy fix.

Let us know please.

**Comment by arnelap** [comment]
Since there have been no replies for awhile I will now mark this ticket as "resolved". If you are still experiencing this issue or you have a similar problem, please create a ticket on the Wordpress forum or via Premium support.

https://wordpress.org/support/plugin/mailchimp-for-wp

 Thank you!
