### ISSUE TITLE
"Unexpected Character in Input" Error Message Appears

### ISSUE THREAD

**Issue by dzyngrl** [ibericode/mailchimp-for-wordpress#542]
My website URL: 

HarrisburgBeerWeek.com

This line of text appears at the top of my website when the latest version of the Mailchimp wordpress plugin is activated. 

"Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /home2/harrisg0/public_html/wp-content/plugins/mailchimp-for-wp/includes/forms/class-form-previewer.php on line 16"

I currently have the plugin turned off so the error won't show.

### How can we reproduce this issue?
1. by activating the Mailchimp wordpress plugin
2.
3.

### Technical info
* WordPress version: 4.9.4
* MailChimp for WordPress version: 4.2
* Relevant plugins in case of a bug: Mailchimp

**Comment by dannyvankooten** [comment]
Hi @dzyngrl,

Are you on a very old PHP version by any chance, version 5.2?
