### ISSUE TITLE
No Sync with WooCommerce/Ecommerce from premium.

### ISSUE THREAD

**Issue by OliverHarbour** [ibericode/mailchimp-for-wordpress#543]
My website URL: Oliverharbour.com

### The issue

Hey
Awesome Plugin btw!

I have an issue syncing WooCommerce with MailChimp. I'm using the following plugins:
- **MailChimp for WooCommerce V2.1.5**
- **MailChimp for WordPress V4.2**
- **MailChimp for WordPress - Premium V3.3.29**

As far as I can tell, all three plugins are connected with the right API, as mailchimp is showing the mailing list. Although the '**List settings**' option, in the MailChimp connected sites area just keeps on spinning. 

I have tried just running the MC4WP on its own and still no confirmation emails come through from orders etc.
I have synced the store with the 'Ecommerce" part of the premium plugin thinking that was the issue, but alas not.

Dammit Jim.

I have also spoken to MailChimp, but it like speaking to a Vogon. All they could recommend was that I speak to you guys, and that I was using the recommended plugin of MC4WC V2.1.5 which I am, so that didn't help.

I have synced my products and orders with the Ecommerce part of the premium plugin, and it said its a green light - all synced, ready to go, but mailchimp is saying nothing has synced. You'll see what I mean by the pictures. if I go to WPAdmin>Settings>MailChimp Settings>sync, it says there are no orders or products. And no option to re-sync?

Also another thing to note is in the Ecommerce part, where you have the option to "**load MC.js?**", It wont stay on yes. I can click yes, and save changes but it won't save changes.

It may well be something I am doing my end, but as I'm utterly useless at these thing you are getting my plea for help!

My Suspicion is that its an issue with the 'Recommended' Mailchimp for WooCommerce Plugin, that seems to have people reeling at the moment. If there is a workaround, I would love you forever.
Thank you in advance for your help and patience! ;)

### How can we reproduce this issue?
1. pour your hopes and dreams into wordpress
2. _watch them melt before your eyes_
3. get all three plugins to try and talk to each other, so that mailchimp is able to see the store and products.

### Technical info
* WordPress version: 4.9.4
* MailChimp for WordPress version: 4.2
* Relevant plugins in case of a bug:
- WooCommerce Version 3.3.3
- WooCommerce PayPal Express Checkout Gateway Version 1.5.2
- WooCommerce Services Version 1.12.1
- WooCommerce Smart Coupons Version 3.3.11
- WooCommerce Stripe Gateway Version 4.0.7
- YITH WooCommerce Wishlist Version 2.2.1

![screenshot 2018-03-15 13 33 32](https://user-images.githubusercontent.com/37407546/37471031-c6f86bee-2860-11e8-8374-0db9430a4dfd.jpg)

![screenshot 2018-03-15 13 59 58](https://user-images.githubusercontent.com/37407546/37471138-f988cf9a-2860-11e8-81df-54761b7e2e4a.jpg)

![screenshot 2018-03-15 13 34 17](https://user-images.githubusercontent.com/37407546/37471172-09f4881a-2861-11e8-9cf5-c1e619dd9de9.png)

![screenshot 2018-03-15 13 33 46](https://user-images.githubusercontent.com/37407546/37471193-1567fb78-2861-11e8-85c1-eda76214ecca.png)

**Comment by dannyvankooten** [comment]
Hi @OliverHarbour,

Sorry to hear about your melted dreams. Let's see if we can put them back together! 

First things first: if you are running our **MailChimp for WordPress Premium** plugin and using that to connect your WooCommerce store to MailChimp then the "MailChimp for WooCommerce" plugin is obsolete and it might even conflict if both plugins are connecting your store to the same list. So I would deactivate that one first.

Then, the spinning "List settings" icon in your MailChimp account indicates that we haven't told your MailChimp account yet that we are done importing your orders and product (initially).

If you go to the **MailChimp for WP > E-Commerce** page in your WP Admin and scroll down a bit, there should be a line saying:

> Your store is currently connected to Store list in MailChimp as WooCommerce store.. (edit)

Clicking that "edit" link will take you to a page where you have the following setting:

![image](https://user-images.githubusercontent.com/885856/37511385-e5feedf8-28fe-11e8-9581-5862367d89f2.png)

Can you please let us know what that setting looks like for you? For any emails to be sent out, it should be set to "Yes".

Cheers, Danny

**Comment by OliverHarbour** [comment]
Hi Danny

Thank you for the quick response - it would seem my faith was misplaced in the Mailchimp version of mail chimp for WooCommerce, you were right, it was causing a conflict. So after Deleting this and refreshing the premium plugin, my mail listing synced! so we have progress!

However (don’t hit your head on the desk) when I make an order in my store, I don’t get mail chimp order notifications, even though they are on - new order, shipping confirmation etc.
They will send, although not from mail chimp but from the woo commerce module itself if I have them ticked in the woo commerce plugin. I have turned these off to stop duplicates, as I read it was cause this. now I don’t get any. 

Thoughts?

Oh and yes the Enable automations is ticked yes. :)


Kind Regards
Oliver


Oliver Harbour
07949 234643
oliverharbour.artstation.com
Instagram @oliver.harbour

**Comment by dannyvankooten** [comment]
Hi @OliverHarbour,

Progress, good! :smiley: 

For order notifications to be sent, please ensure that you are sending all orders (regardless of order status) to MailChimp.

![image](https://user-images.githubusercontent.com/885856/37516158-8478b9ce-290d-11e8-97b4-27156bff98ef.png)

Also, please note that the plugin does not send the order to MailChimp right away to prevent unnecessarily slowing down your website during checkout (the important part is closing the sale, after all). It will send the order to MailChimp with a slight delay, with a maximum delay of one hour.

If you check your **MailChimp for WP > E-Commerce** page, do you see any pending background jobs there?

![image](https://user-images.githubusercontent.com/885856/37516210-acdb5e62-290d-11e8-900d-c0470b70ff8e.png)

Thanks in advance!

**Comment by OliverHarbour** [comment]
Hey

I have checked the Include all Order Statuses, and its on ‘yes’. Also when I complete a new order, I refresh the Commerce page and nothing is showing as a Queued background job?
Underneath that box where it says Products and Orders, I have refreshed the orders and still nothing is queued for a background job? Oddly nothing even shows in my Debug log (it’s set to show everything) but all it shows is this:


And as you can see, that log was from when I first downloaded this plugin.


Kind Regards
Oliver


Oliver Harbour
07949 234643
oliverharbour.artstation.com
Instagram @oliver.harbour

**Comment by dannyvankooten** [comment]
Hi @OliverHarbour,

Sorry for the late reply. Could you please send us an email at support@mc4wp.com so that I can look at this in more detail? It's weird that the background jobs aren't properly queued up. Adding a new or update an existing order should definitely do that...

As for coupons, we are finalising the work on that as we speak and hope to add support for it in next week's plugin update.

**Comment by OliverHarbour** [comment]
Hey

How did you get on? I did see that an automated email was sent through mail chimp for a test order, but i had no notification of the order - I’m assuming you disabled this for the test? 

Does this mean you had a breakthrough with the automation? It would be great with Easter coming up, as I have an easter offer in place and a campaign now running :)

I look forward to hearing from you!

Kind Regards
Oliver


Oliver Harbour
07949 234643

oliverharbour.com

Instagram:
@oliver.harbour
Twitter: 
twitter.com/oliverharbour
Facebook: facebook.com/OliverHarbourArt
