### ISSUE TITLE
Order sync errors after premium extension updates when using woocommerce

### ISSUE THREAD

**Issue by dclprogramming** [ibericode/mailchimp-for-wordpress#544]
My website URL: 

We use woocommerce and the mailchimp for wordpress plugin plus the mailchim for wordpress premium extension plugin. It appears that each time we install an update for the premium plugin our orders begin to fail to sync and throw up errors like "Error adding order 106160: Bad Request. A product with the provided variant ID does not exist in the account for this list.”

### How can we reproduce this issue?
1. start with mc for wordpress v 4.2 and mc for wordpress premium v 3.3.27
2. sync up all your info to mailchimp
3. update the premium plugin to v 3.3.30 (problem occurs with each update not specifically this one-but this one caused it for us most recently)
4. add a new order to you woocommerce system for a product that has variations.

### Technical info
* WordPress version: 4.9.4
* MailChimp for WordPress version: 4.2
* Relevant plugins in case of a bug: Premium Extension v 3.3.30

**Comment by arnelap** [comment]
Hi, 

Please contact us at support@mc4wp.com and refer to this issue. 

Thank you!
