### ISSUE TITLE
Merges Field Issue

### ISSUE THREAD

**Issue by thebait** [ibericode/mailchimp-for-wordpress#545]
My website URL: 

### The issue
I am trying your free version of the Mailchimp to WordPress addon.  We are not doing anything fancy, just trying to get data to flow.  

This is a copy and paste of the debug log:
[2018-04-02 13:06:26] ERROR: Registration Form > MailChimp API Error: Bad Request. Invalid Resource. Your merge fields were invalid.
- LNAME : Please enter a value
Request: PUT https://us12.api.mailchimp.com/3.0/lists/20b0ba5394/members/efb8ead6c90bc50710e07cb14ae55740 - {"email_address":"theb***@ms*.com","interests":{},"merge_fields":{"FNAME":"thebait7415"},"status":"pending","email_type":"html","ip_signup":"173.25.224.35"}
Response: 400 Bad Request - {"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"Invalid Resource","status":400,"detail":"Your merge fields were invalid.","instance":"d147399a-19a7-4ee4-9e0f-50d5101740f1","errors":[{"field":"LNAME","message":"Please enter a value"}]}

### How can we reproduce this issue?
1.
2.
3.

### Technical info
* WordPress version: 4.9.4
* MailChimp for WordPress version: 4.2
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
The error means the field LNAME is set to be required in your MailChimp list settings, but not included in the form. Best solution is to set the LNAME to not be required. 

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
