### ISSUE TITLE
RSS Newsletter Campaign never sent Weekly Newsletter 

### ISSUE THREAD

**Issue by Dandelionchandelier** [ibericode/mailchimp-for-wordpress#550]
My website URL: https://dandelionchandelier.com

### The issue
RSS Newsletter Campaign never sent Weekly Newsletter on Sunday 4/15/18 at 10am. We have never had this issue before. I spoke to Mailchimp.com and they recommended reaching out to feed host and asking if they can whitelist our outbound IP's that Mailchimp uses to Connect RSS feeds. Those Google Cloud Engine IP's would be 35.185.87.110 35.196.158.45 35.196.109.224 

It appears from his findings that when MC attempted to connect to our RSS feed at the time of the send, the connection failed and the feed was unavailable. He wasn't able to offer really any more specific details other than that the RSS feed wasn't available when they attempted to connect. 

I have since upgraded. Could this have solved the issue? 

### How can we reproduce this issue?
1. Ensure this never happens again
2. Whitelist outbound IP's that MC uses to connect to RSS feed 
3. Make sure our weekly newsletter is sent out this Sunday and every Sunday moving forward. 

### Technical info
* WordPress version: https://dandelionchandelier.com/wp-admin/
* MailChimp for WordPress version: Version 4.2.1
* Relevant plugins in case of a bug: Scheduled Post Trigger, Version 2.21

**Comment by arnelap** [comment]
Please note we are not affiliated with MailChimp.com. We are a different company "ibericode" that develops plugins such as "MailChimp for WordPress". I'm sorry to tell you I am not able to help you with this question as it is not related to our plugin. My advice to you is to contact MailChimp.com as they would be the best people to answer any query related to your MailChimp.com account. 

You can contact MailChimp.com trough https://mailchimp.com/contact/support/

I hope that helps. If you have any queries specific to our plugin please let us know!
