### ISSUE TITLE
Response Email Disabled but STILL Sending

### ISSUE THREAD

**Issue by ghost** [ibericode/mailchimp-for-wordpress#552]
My website URL: 

### When user opts in on page:
https://mindlightgroup.com/promaxgames/
A response email is sent automatically even though this has been turned off here:

<img width="1234" alt="mlg config" src="https://user-images.githubusercontent.com/38674351/39159517-cd7f2b1e-471a-11e8-92b8-efaf6e4f11e8.png">

I do not want an auto email to be sent when someone opts in and if one is sent I would like to be able to modify what that email says. Can you please help?

### How can we reproduce this issue?
1.
2.
3.

### Technical info
* WordPress version:
* MailChimp for WordPress version:
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
Hi,

That screenshot does not look like our plugin, so I can't help you with that.
