### ISSUE TITLE
Mailchimp Popup

### ISSUE THREAD

**Issue by Spacinsider** [ibericode/mailchimp-for-wordpress#555]
My website URL: https://spacinsider.com

### How can we reproduce this issue?
1. try to add a mailchimp subscriber popup to any page and see if it works?
![mailchimp after](https://user-images.githubusercontent.com/38963361/39604740-6e40deb6-4efb-11e8-847e-d918ed7aea97.png)
![mailchimp before](https://user-images.githubusercontent.com/38963361/39604741-6e50423e-4efb-11e8-8a96-6059cdac8fdb.png)

2.
3.

### Technical info
* WordPress version: 4.9.5
* MailChimp for WordPress version: 4.2.1. Jetpack version 6.1
* Relevant plugins in case of a bug: Mailchimp for Wordpress

**Comment by arnelap** [comment]
That code is not related to our plugin.

If you want to make a popup with our plugin I suggest to put the shortcode to a Mailchimp for Wordpress form in a Boxzilla box. Boxzilla is made by us as well and works well with Mailchimp for Wordpress.

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
