### ISSUE TITLE
GDPR

### ISSUE THREAD

**Issue by Nyazhari** [ibericode/mailchimp-for-wordpress#556]
My website URL: www.optimumcs.com

### The issue
We have enabled GDPR on our MailChip list but it's showing the options on the wordpress form that we have created on our website using your plug-in. How do we enable GDPR on our website forms?

### How can we reproduce this issue?
1.Submit a test entry on the form at the bottom of this page: https://www.optimumcs.com/business-work-automation/
2.
3.

### Technical info
* WordPress version:
* MailChimp for WordPress version:
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
The plugin already has everything you would need to be GDPR compliant, but we will add some features to make it easier for you in the next update, like warnings with certain settings and an easier way to include a required checkbox to confirm data is saved at MailChimp. Keep an eye on this article for more information: https://kb.mc4wp.com/gdpr-compliance/

For now, if you like to add that checkbox you can use this code in the form builder: https://gist.github.com/dannyvankooten/c6ac57e734348fdf7ce1b3b65e4ecdd7

MailChimp does not let us set those GDPR fields via the API, but instead advised us and our users to use normal interest groups. You can include those in the form as checkboxes and it will be saved in MailChimp and let you create segments based on what boxes someone checked.
If you add new interest groups it can take awhile before the button to insert them into the forms show in our plugin, to speed that up go to Mailchimp for WP > Mailchimp after creating the interest groups and click the "Renew MailChimp Lists" button to directly pull in the latest fields and lists.

**We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp**

**Comment by f4w-pwharton** [comment]
FYI, MailChimp now has the GDPR fields ('marketing_permissions') accessible via the API - https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/
