### ISSUE TITLE
Add More Form?

### ISSUE THREAD

**Issue by Uranbold** [ibericode/mailchimp-for-wordpress#557]
How do i add more Form?

1. I tried to add 2 Form and can't do this?

### Technical info
* WordPress version: latest
* MailChimp for WordPress version: latest

**Comment by arnelap** [comment]
The free version of our plugin only allows for 1 form. With the Premium add-on you can create unlimited forms.

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
