### ISSUE TITLE
Different lists for different CF7 forms

### ISSUE THREAD

**Issue by fpaneque** [ibericode/mailchimp-for-wordpress#562]
My website URL: https://www.jeanleon.com/enoturismo/formulario-de-reserva/

### The issue
In my contact form 7 I'm trying to link it to an id as it says in the documentation, but I don't know why it doesn't add the address to the list.
The code I put in is the following:
`<input name="_mc4wp_lists[]" type="checkbox" value="8f1b4aa5e9" />`
But it doesn't work. I have not created any groups, nor subgroups. I just want to add it directly to the list.

Thank you very much

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
