### ISSUE TITLE
Error loading 'Form' page

### ISSUE THREAD

**Issue by alexandracleopatras** [ibericode/mailchimp-for-wordpress#563]
My website URL: cleopatrasworldwide.com

### The issue
Cannot get onto the 'Form' page on wordpress plugin, to edit the subscriber form. Get the below error messages:

Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'discwid_admin_menu' not found or invalid function name in /homepages/35/d737098262/htdocs/app737098548/wp-includes/class-wp-hook.php on line 286

Warning: Cannot modify header information - headers already sent by (output started at /homepages/35/d737098262/htdocs/app737098548/wp-includes/class-wp-hook.php:286) in /homepages/35/d737098262/htdocs/app737098548/wp-admin/includes/misc.php on line 1116

Warning: Cannot modify header information - headers already sent by (output started at /homepages/35/d737098262/htdocs/app737098548/wp-includes/class-wp-hook.php:286) in /homepages/35/d737098262/htdocs/app737098548/wp-includes/pluggable.php on line 1216

### How can we reproduce this issue?
1. Dashboard
2. MailChimp for WP
3. Form

### Technical info
* WordPress version: WordPress 4.9.6
* MailChimp for WordPress version:  MailChimp for WordPress, 4.2.2.
* Relevant plugins in case of a bug: Ashe theme, MailChimp for Wordpress

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp

I'm not sure if this is related to our plugin as the error does not sound familiar and non if the functions or files named in the error are from our plugin. Maybe it's a compatibility issue with another plugin?
