### ISSUE TITLE
List field buttons missing on form

### ISSUE THREAD

**Issue by wolfman6601** [ibericode/mailchimp-for-wordpress#564]
My website URL: www.webdesignz.co.nz

### The issue
List field buttons are not pulling through to the form in the plugin. Only form fields are available. I opened a ticket previously but this issue still persists. I have tried multiple times to renew lists, which I had done in the first instance. This does not fix the issue. I use the same theme on a different website with all the same plugins - no issues. Luckily, I was able to copy the form fields from this other website, but it would be nice to have the buttons there, as they should be. I hope you will be able to look into this.  PS. I have also tried completely uninstalling the plugin and re-installing, without any success.

### How can we reproduce this issue?
1. Activate plugin on website
2. Go to "Form"
3. No list field. This has been set up in Mail Chimp properly.

### Technical info
* WordPress version: 4.9.7
* MailChimp for WordPress version: 4.2.2
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
