### ISSUE TITLE
NAME field styling problems

### ISSUE THREAD

**Issue by Ignas1** [ibericode/mailchimp-for-wordpress#565]
My website URL: 
coachingenious.com

### The issue
If I add the NAME field, it appears aligned left and in a different styling than the EMAIL field (at the bottom of the page).

### Technical info
* WordPress version: 4.9.6
* MailChimp for WordPress version: Latest

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
