### ISSUE TITLE
Form button for mailchimp in Wordpress not working

### ISSUE THREAD

**Issue by ClifMilton** [ibericode/mailchimp-for-wordpress#566]
My website URL: bksconsultancy.co.uk

### The issue
I cannot get the form section within wordpress to work, it just defaults to the wordpress dashboard. I want to update my form but cannot!! please can you help. have been trying for 2 weeks now.

### How can we reproduce this issue?
1.
2.
3.

### Technical info
* WordPress version:
* MailChimp for WordPress version:Version 4.2.2
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
Did you already try clearing your browser cache? 
Can you try in another browser?

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
