### ISSUE TITLE
user info won't auto sync to mailchimp but will manually sync

### ISSUE THREAD

**Issue by ericdstoltz** [ibericode/mailchimp-for-wordpress#569]
My website URL: http://www.pwyc.org

### The issue
User changes seem to be stacking up in background processes.  After performing a successful manual synchronization whenever a change was made the background process numbers would increment but they never got processed.  No changes beyond the manual sync occurred.  We did set to auto sync.

### How can we reproduce this issue?
1. perform a manual sync.  Once complete make a change to one of the users in the particular Role
2.
3.

### Technical info
* WordPress version: 4.9.6
* MailChimp for WordPress version: 4.2.2
* Relevant plugins in case of a bug: WP user sync v1.7.4 and also running Ultimate Member which created the user role.

**Comment by ericdstoltz** [comment]
Disregard.  I guess it takes a while.  Any info on how often the background processes are handled and some info on how they are processed?

**Comment by arnelap** [comment]
You can use a plugin like Advanced Cron Manager and look for mc4wp.

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
