### ISSUE TITLE
Error connecting to MailChimp

### ISSUE THREAD

**Issue by brilliant-keti2015** [ibericode/mailchimp-for-wordpress#570]
My website URL: 3dobj.ru

### The issue
How can I solve the problem with you?
Error connecting to MailChimp: 0 cURL error 6: Couldn't resolve host '************291831b9b97f.api.mailchimp.com' 
### How can we reproduce this issue?
1. Go to the administrative control panel and fix
2.
3.

### Technical info
* WordPress version: 4.9.6 
* MailChimp for WordPress version: 4.2.2
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
Fill a MailChimp API key under MailChimp for WP > Mailchimp.
The license key for the plugin goes under MailChimp for Wp > other. 

Hope that helps. If you have any questions, please let us know!
