### ISSUE TITLE
Error adding order: Bad Request. A product with the provided variant ID does not exist in the account for this list.

### ISSUE THREAD

**Issue by DerekBess** [ibericode/mailchimp-for-wordpress#571]
### The issue
When syncing orders I get the following error:

Bad Request. A product with the provided variant ID does not exist in the account for this list.

Example of one of the orders:

Error adding order 19733: Bad Request. A product with the provided variant ID does not exist in the account for this list. Request: POST https://us6.api.mailchimp.com/3.0/ecommerce/stores/98bbbd22375e1e1c8be57ee155f29885/orders - {"id":"19733","customer":{"id":"d2a569a943a566f40b07a6649664e8c3"},"order_total":0,"tax_total":0,"shipping_total":0,"currency_code":"USD","lines":[{"id":"1818","product_id":"15488","product_variant_id":"17305","quantity":1,"price":0}],"billing_address":{"name":"*** ***","company":"","phone":"","address1":"","address2":"","city":"","province":"","postal_code":"","country":"US"},"financial_status":"paid","fulfillment_status":"shipped","processed_at_foreign":"2018-06-12 01:20:05","landing_site":"https:\/\/wherever.tv\/blog\/one-america-news\/","order_url":"https:\/\/wherever.tv\/my-account\/view-order\/19733"} Response: 400 Bad Request - {"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"Bad Request","status":400,"detail":"A product with the provided variant ID does not exist in the account for this list.","instance":"37c1afd6-0729-46df-8b5a-1ba6922acbb5"}

### How can we reproduce this issue?
1. Synchronize orders

### Technical info
* WordPress version: 4.9.1
* MailChimp for WordPress version: 4.2.2

**Comment by arnelap** [comment]
We only use git for development related issues. For Premium support please email support @ mc4wp.com

Thanks!
