### ISSUE TITLE
CF7 Integration: option '(don't) Replace grouping' don't works

### ISSUE THREAD

**Issue by Bebobox** [ibericode/mailchimp-for-wordpress#572]
Hi, my CF7 integration work's, but my form replace groups interest everytime. Obviously I have checked "no" in Replace Interest Groups option. 

This is my form code (only the integration part of this):
```
[mc4wp_checkbox]
<label><input name="mc4wp-INTERESTS[a6c62a855f][]" type="hidden" type="checkbox" value="e2abddddd6" checked="true"></label> 
```

In my Mailchimp lIst I have other option in the same interest grup list. The previous preferences are deleted after sending, I would like this choice to be added to the others

**Comment by Bebobox** [comment]
toc toc

**Comment by dannyvankooten** [comment]
Hi @Bebobox,

Your form inputs have `type="hidden" type="checkbox` in them, which means that the interests will always be sent to the server as "selected".

If you want to offer your users the choice for an interest group then you should use the following HTML:

```html
<label><input name="mc4wp-INTERESTS[a6c62a855f][]" type="checkbox" value="e2abddddd6" checked="true"></label>
```

If you don't want to offer a choice and want to add everyone using that form to a specific interest group, then you should use the following HTML:

```html
<label><input name="mc4wp-INTERESTS[a6c62a855f][]" type="hidden" value="e2abddddd6"></label> 
```

Hope that helps, good luck!

**Comment by Bebobox** [comment]
Hi, don't works. I have to explain better.

I have 4 options in my Mailchimp Interest Group. They are 4 different events. 
When an user submit info from a form, I need that Mailchimp **ADD** this interest, but DON'T REMOVE/replace other previous interests. Now, if an user fill the form, Mailchimp changes all and the user become interested to only an event.

Replace Interest Groups option in the plugin control panel don't works

**Comment by Bebobox** [comment]
toc toc

**Comment by Bebobox** [comment]
Plz, can you help me?
