### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by TheSteve19** [ibericode/mailchimp-for-wordpress#573]
My website URL: 
thechicagoriverwalk.com
### The issue
Error connecting to MailChimp: 503 Service Unavailable 

[2018-06-20 17:02:57] ERROR: Form 618 > MailChimp API error: 503 Service Unavailable. akamai_503.
Request: GET https://us18.api.mailchimp.com/3.0/lists/0b45d77c23/members/8c4e46fab3c688664559efa023ef612d
Response: 503 Service Unavailable - {"type":"akamai_error_message","title":"akamai_503","status":503,"ref_no":"Reference Number: 00.54f2f33f.1529514177.af3649e"}
[2018-06-20 17:03:11] ERROR: Form 693 > MailChimp API error: 503 Service Unavailable. akamai_503.
Request: GET https://us18.api.mailchimp.com/3.0/lists/dc1a8c90f3/members/8c4e46fab3c688664559efa023ef612d
Response: 503 Service Unavailable - {"type":"akamai_error_message","title":"akamai_503","status":503,"ref_no":"Reference Number: 00.b094dc17.1529514191.5426f0af"} 

### How can we reproduce this issue?
1. Try to sign up for any form at thechicagoriverwalk.com
2."Oops an error occured"
3.

### Technical info
* WordPress version: 4.9.6
* MailChimp for WordPress version: PREMIUM Version 4.4.2
* Relevant plugins in case of a bug: Using AVADA theme

**Comment by arnelap** [comment]
https://kb.mc4wp.com/solving-connectivity-issues/

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
