### ISSUE TITLE
Style Builder Not Working

### ISSUE THREAD

**Issue by corilee13** [ibericode/mailchimp-for-wordpress#574]
Hello,

I have been using Mailchimp For Wordpress to manage email signups. No matter what I do, the style builder is not making any changes to the form's style. If I use the presets it works just fine and changes color, but any changes I make in the style builder don't show and I just see the basic gray form.

What gives?

**Comment by arnelap** [comment]
Make sure you've set Style to "Use Styles Builder" under MailChimp for WP > Forms > Appearance.

We only use git for development related issues. For Premium support please email support @ mc4wp.com

**Comment by corilee13** [comment]
I did that of course or else I would not have asked for help. I'm not that daft thank you.

On Jun 25, 2018 6:53 AM, Arne Lap <notifications@github.com> wrote:

Closed #574<https://github.com/ibericode/mailchimp-for-wordpress/issues/574>.
