### ISSUE TITLE
Class 'ComposerAutoloaderInit...' not found in ...\mailchimp-for-wp\vendor\autoload_52.php:7

### ISSUE THREAD

**Issue by tobiv** [ibericode/mailchimp-for-wordpress#575]
My website URL: 
https://bpluse.ch

### The issue
I updated the plugin to 4.2.3 from the WP dashboard, now I'm getting this fatal error:

```
Fatal error: Uncaught Error: Class 'ComposerAutoloaderInita077e77aed35665d3812cf40b026e93e' not found in ...\plugins\mailchimp-for-wp\vendor\autoload_52.php:7
```

I tried deleting the plugin folder and manually uploaded 4.2.3 (downloaded from wp.org), which didn't help. I also tried uploading the older 4.2 from github. Still the same error; only the hash after `ComposerAutoloaderInit` changes. I assume some composer build error?

### Technical info
* WordPress version: 4.9.6
* MailChimp for WordPress version: 4.2, 4.2.3
* Relevant plugins in case of a bug:

**Comment by tobiv** [comment]
Downloaded `composer.json` and ran `composer update`. This fixed the issue.

**Comment by arnelap** [comment]
​Thanks for letting us know.
