### ISSUE TITLE
includes/forms/views/add-form.php line 46, wrong use of selected() instead of checked()

### ISSUE THREAD

**Issue by morloi** [ibericode/mailchimp-for-wordpress#576]
### The issue
When you have only 1 list, creating a new form the system does not precheck the list. There is a code to do this, but is wrong:

`<input type="checkbox" name="mc4wp_form[settings][lists][<?php echo esc_attr( $list->id ); ?>]" value="<?php echo esc_attr( $list->id ); ?>" <?php selected( $number_of_lists, 1 ); ?> >`

to be changed in 

`<input type="checkbox" name="mc4wp_form[settings][lists][<?php echo esc_attr( $list->id ); ?>]" value="<?php echo esc_attr( $list->id ); ?>" <?php checked( $number_of_lists, 1 ); ?> >`

### How can we reproduce this issue?
Use a single list mailchimp account
Create a new form

**Comment by arnelap** [comment]
​Thanks for letting us know.
