### ISSUE TITLE
Validate API key format when entering

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/mailchimp-for-wordpress#578]
To prevent people from entering other kinds of key (eg plugin license key).

**Comment by mmarypcarney** [comment]
My mailchimp API key is giving error message while connecting my website along with mailchimp account. It shows the error message;
“Not Acceptable. Request: GET https://us20.api.mailchimp.com/3.0/?fields=account_id Response: 406 Not Acceptable -”
