### ISSUE TITLE
Conflict with MailChimp for WooCommerce

### ISSUE THREAD

**Issue by JCSol0628** [ibericode/mailchimp-for-wordpress#581]
### The issue
There is a problem when I use this plugin alongside MailChimp for WooCommerce. None of my notification emails send out. Please advise.

### Technical info
* WordPress version: 4.9.7
* MailChimp for WordPress version: 4.2.4
* Relevant plugins in case of a bug: MailChimp for WooCommerce and MailChimp for WordPress

**Comment by arnelap** [comment]
If currently you've setup MailChimp for WooCommerce to send out (order) notifications you can contact them about any problems with that or switch to Mailchimp for Wordpress Premium to sync your WooCommerce data. 

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp

Thank you.
