### ISSUE TITLE
MailChimp for WordPress: 503 Service Unavailable 

### ISSUE THREAD

**Issue by josipmarkus** [ibericode/mailchimp-for-wordpress#587]
My website URL: Not launched yet because I can't get this plug-in working.

### The issue

I'm receiving the error message "503 Service Unavailable", even though a few days ago it was working fine. I'm not sure what's changed. I've exhausted all of the suggestions I've found online to no avail. 

### Technical info
* WordPress version: 4.9.8
* MailChimp for WordPress version: 4.2.4

**Comment by arnelap** [comment]
It means your hosting IP is blocked by Akamai firewall, please see https://kb.mc4wp.com/solving-connectivity-issues/

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp

**Comment by josipmarkus** [comment]
Yes, I read that article before posting on here and went through all of the checks other than the SSH command. I had my hosting company check to see if the IP was being blocked by Akamai. They said they checked and that it's not. Is that the only possible issue?
