### ISSUE TITLE
If form is used within Boxzilla, the hash tag is added to the redirect URL

### ISSUE THREAD

**Issue by hchouhan** [ibericode/mailchimp-for-wordpress#589]
How to replicate:

1. Create a MC4WP form and disable Ajax.
2. Set a redirect something like "https://danny.test/thank-you/"
3. Create a BoxZilla pop-up (make it to not show automatically) and add the above form to this pop-up.
4. Access the pop-up with something like "https://danny.test/#boxzilla-314".
5. When the form is submitted, it's redirected to "https://danny.test/thank-you/#boxzilla-314" instead of just "https://danny.test/thank-you" causing the pop-up to show up again.

**Comment by dannyvankooten** [comment]
This is a browser "feature", it can be disabled by setting a hash explicitly in the redirect URL. 

For example: 

**Redirect to: ** http://my-website.com/#
