### ISSUE TITLE
Not connected 

### ISSUE THREAD

**Issue by lba-perrine** [ibericode/mailchimp-for-wordpress#590]
My website URL: http://www.poma.net/

I'm adding the API Key in Mailchimp "General Settings" page, but it remains "Not connected" despite a correct API key that is verified in the mailchimp account.

* WordPress version: 4.8.2
* MailChimp for WordPress version: 4.2.5
* Relevant plugins in case of a bug:

**Comment by dannyvankooten** [comment]
Hi @lba-perrine,

There should be a more detailed error message at the top of the screen (**WP Admin > MailChimp for WP > MailChimp** telling you more about what exactly goes wrong. Can you share what it says please?

**Comment by arnelap** [comment]
I did not see the screenshot, ut either way, we only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
