### ISSUE TITLE
Not Connected - This account has been deactivated.

### ISSUE THREAD

**Issue by dr-thomas64** [ibericode/mailchimp-for-wordpress#591]
My website URL: lpv-technology.com

### The issue
MailChimp returned the following error:
Forbidden. User Disabled. This account has been deactivated. Request: GET https://us13.api.mailchimp.com/3.0/ Response: 403 Forbidden - {"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"User Disabled","status":403,"detail":"This account has been deactivated.","instance":"0141b85e-2e9b-4652-9e5b-a6c194841d75"}

### How can we reproduce this issue?
1. I don't know - I can still log into and manage my mailchimp account at mailchimp.com but today the WP plugin says that the account has been deactivated. 
2.
3.

### Technical info
* WordPress version:
* MailChimp for WordPress version:
* Relevant plugins in case of a bug:

**Comment by dr-thomas64** [comment]
Actually - just created a new API key and pasted that in - and it's connected again. So maybe not a problem at all.

**Comment by arnelap** [comment]
thanks for letting us know.

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
