### ISSUE TITLE
Hide success message if redirect is set

### ISSUE THREAD

**Issue by hchouhan** [ibericode/mailchimp-for-wordpress#592]
Currently, depending on a browser, the success message is displayed even if a redirect is set. CSS is now the only option to hide this message. It would be nice if the message is not displayed at all if redirect is set.

**Comment by dannyvankooten** [comment]
Hmm, weird. This should have been handled in 41527568b12d390e16ea31ab75d17965bb8a0324

**Comment by dannyvankooten** [comment]
Ahh, it was reverted in acb6cf5d1cde76c0e83b1cc96d58cba2a4499d91. If only I knew why...

**Comment by arnelap** [comment]
I recommend making it so you can set the success message to nothing / empty (without throwing an error). That way it's optional either way. Showing a message on redirect can be handy on slow sites/connections.
