### ISSUE TITLE
GDPR Marketing Permissions

### ISSUE THREAD

**Issue by willminsight** [ibericode/mailchimp-for-wordpress#593]
My website URL: 

insightforliving.org.uk

### The issue/enhancement request

MailChimp now has the GDPR fields ('marketing_permissions') accessible via the API - https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/

It would be nice to see in the admin area if a list has marketing permissions (e.g: GDPR) enabled. https://developer.mailchimp.com/documentation/mailchimp/reference/lists/

It would be nice to integrate in mc4wp front-end forms the ability to pull in the specific list's marketing preferences as checkboxes to allow subscribers to check these boxes similar to how mailchimp's forms allow subscribers to do this. https://mailchimp.com/help/collect-consent-with-gdpr-forms/ 

I am assuming that this would require the form to be used only for one specific list so the list specific permission ids could be displayed to the user and used by the api.

As a mc4wp premium license subscriber, I would be willing to have this feature added to the premium version of the plugin.

Thanks in Advance,
Will Murphy

**Comment by arnelap** [comment]
We are working on including these fields.

**Comment by mateuszpohl** [comment]
They do work the same "visually", but if you have lists with GDPR fields enabled in MailChimp there's no way to update those marketing agreements in other way than manually updating each subscriber or calling the API with own webhook callback. I've bought premium version recently and I was sure it has proper GDPR support and after that I've realised that in your KB it's done via interest groups, which is completely not acceptable with my lists (using MailChimp GDPR support).

Workaround with interest groups is simple, but requires additional agreement migration after switching to MailChimp's native GDPR support in future.

I've gone through your source code and MailChimp API docs and it looks like not very hard to implement.

I think this is kind of a priority feature, especially for your EU-based customers. For me (as an example) lack of native GDPR fields support is a blocker in two projects :(

I'm counting on you guys! :D

**Comment by VABELHAVT** [comment]
> 
> 
> We are working on including these fields. In the meantime you can use interest groups, aas they work just the same as the GDPR fields.

Any update for this Issue? We'd need these fields as well.

**Comment by arnelap** [comment]
@dannyvankooten 'GDPR fields are now available in the API: https://mailchimp.com/help/gdpr-faq/#API

**Comment by arnelap** [comment]
https://secure.helpscout.net/conversation/1132054256/22706?folderId=253120

**Comment by hchouhan** [comment]
https://wordpress.org/support/topic/agree-terms-doest-work-always/

**Comment by hchouhan** [comment]
https://wordpress.org/support/topic/gdpr-dsgvo-saving-agreement-at-mailchimp/

**Comment by arnelap** [comment]
https://wordpress.org/support/topic/gdpr-marketing-fields-api-update/

**Comment by federiconeri** [comment]
> https://wordpress.org/support/topic/gdpr-marketing-fields-api-update/

Hi, is there any news on this issue? Although you guys still mention the workaround with "Groups", I've noticed that **subscribers via MC4WP are added in Mailchimp as _Opted-out of "Direct Email"**_ (or whatever option you use as GDPR preferences). 

In the latest reply @lapzor mentioned _"There is also a checkbox you can easily add to our forms that will simply not allow the form to be submitted if the box isn’t checked. With that added to your form you can be sure that any contact that is added in MailChimp did agree / check that box."_ and that's ok, but as you can see it's pretty clear that users are added as "Opted-out" for the specific GDPR field inside your list.

**Comment by josymoyer** [comment]
Just setting up a new website using MC4WP & having same problem as federiconeri 10/20/20 - did you find a way to set GDPR fields?

**Comment by dannyvankooten** [comment]
a4cdd08504eac2054f3fd8027c98fbd7fecbdf2d now retrieves the marketing permissions and stores them locally, but this only works if the list has at least 1 (pending or confirmed) subscriber. 

Next up is allowing to specify which marketing permissions to enable from the form and integration settings pages.

**Comment by ITedInnovator** [comment]
> They do work the same "visually", but if you have lists with GDPR fields enabled in MailChimp there's no way to update those marketing agreements in other way than manually updating each subscriber or calling the API with own webhook callback. I've bought premium version recently and I was sure it has proper GDPR support and after that I've realised that in your KB it's done via interest groups, which is completely not acceptable with my lists (using MailChimp GDPR support).
> 
> Workaround with interest groups is simple, but requires additional agreement migration after switching to MailChimp's native GDPR support in future.
> 
> I've gone through your source code and MailChimp API docs and it looks like not very hard to implement.
> 
> I think this is kind of a priority feature, especially for your EU-based customers. For me (as an example) lack of native GDPR fields support is a blocker in two projects :(
> 
> I'm counting on you guys! :D

Exactly. It's no good just having interest groups because someone could withdraw permission and would still get emails because it's not updating the preferences in Mailchimp.

**Comment by dannyvankooten** [comment]
For anyone reading this, as of Mailchimp for WordPress version 4.9.2 (released earlier this week) you can now include a field named `MARKETING_PERMISSIONS` in your forms. The `value` attribute of this field should be a comma-separated list of permission names or ID's (you can find these in the list overview on the **Mailchimp for WP > General** settings page).

#### Checkboxes

By ID:

```html 
<label><input type="checkbox" name="MARKETING_PERMISSIONS[]" value="38e6f999cf" /> Email</label>
<label><input type="checkbox" name="MARKETING_PERMISSIONS[]" value="1283a73736" /> Direct</label>
```

By name(s):

```html 
<label><input type="checkbox" name="MARKETING_PERMISSIONS[]" value="Email" /> Email</label>
<label><input type="checkbox" name="MARKETING_PERMISSIONS[]" value="Direct" /> Direct</label>
```

Note that if referring to permissions by their name that the `value` attribute has to be an exact match of whatever the name of the permission is in Mailchimp.

#### Hidden field

By name(s):

```html
<input type="hidden" name="MARKETING_PERMISSIONS" value="Customized Online Advertising,Email" />
```

By ID:

```html
<input type="hidden" name="MARKETING_PERMISSIONS" value="38e6f999cf" />
```
