### ISSUE TITLE
Something changed in the mailchimp clock?

### ISSUE THREAD

**Issue by JanetAW** [ibericode/mailchimp-for-wordpress#594]
My website URL: https://janetwertman.com

### The issue. Was there a change to mailchimp recently? My last post was made at 6:46 pm on October 4 - but mailchimp did not send out the rss email until 4am October 6

I know there is an issue in that my blog is set to UTC+0 - which means that my new day begins at 5pm. But this was never a problem until 9/21 - when I posted at 22:02 pm PST and got "RSS feed not found" (a month earlier I had posted at 23:45 pm PST and it went out just fine). 

I would be happy to update everything so all use the same timezone - but will that solve the problem? Why did Mailchimp wait for 30 hours before sending the email??

### How can we reproduce this issue?
1. I have no idea - other than waiting until the next time it happens
2.
3.

### Technical info
* WordPress version: 4.9.8
* MailChimp for WordPress version: 4.2.5
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
