### ISSUE TITLE
Support for MailChimp Tags

### ISSUE THREAD

**Issue by arnelap** [ibericode/mailchimp-for-wordpress#595]
Add support for the new MailChimp Tags.

In the meantime we can use Interest groups instead.

**Comment by hchouhan** [comment]
- https://secure.helpscout.net/conversation/696565562/15773?folderId=253120

**Comment by arnelap** [comment]
The problem with Interest groups, for some of our clients, is that you can only have 60 of those. Tags are unlimited. 
https://secure.helpscout.net/conversation/785393840/16813?folderId=253120
