### ISSUE TITLE
503 error when i try to plug in API Key

### ISSUE THREAD

**Issue by lobrien1131** [ibericode/mailchimp-for-wordpress#596]
My website URL: thehookk.com

### The issue
Get 503 error and i contacted my hosting provider and mailchimp and there wasnt anything wrong on their end

### How can we reproduce this issue?
1.
2.
3.

### Technical info
* WordPress version:the latest 
* MailChimp for WordPress version:4.2.5
* Relevant plugins in case of a bug:

**Comment by BIENMIEUX** [comment]
Même problème depuis ce matin. J'ai téléphoné à mon hébergeur OVH. Après vérification, ils pensent que LE SOUCI VIENT DE CHEZ VOUS;

**Comment by BIENMIEUX** [comment]
Ils me demandent quelles sont les  ip utilisées par mailchimp pour résoudre mon problème.

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
