### ISSUE TITLE
Subscribe box misaligned

### ISSUE THREAD

**Issue by janinewhitling01** [ibericode/mailchimp-for-wordpress#597]
My website URL: http://wrq.org.au/
(let me now when you want to have a look, it's in maintenance mode atm) 

### The issue
The form alignment is too far to the left. How do i bring the alignment in to the right? It appears in both the footer and right side bar in this way.

### How can we reproduce this issue?
<img width="1460" alt="screen shot 2018-10-30 at 10 57 17 am" src="https://user-images.githubusercontent.com/44592647/47688912-34147980-dc33-11e8-8b66-62460c4e722d.png">

### Technical info
* WordPress version: latest
* MailChimp for WordPress version: 4.2.5
* Relevant plugins in case of a bug: ?

**Comment by hchouhan** [comment]
Hello,

For support request, please create a new topic at https://wordpress.org/support/plugin/mailchimp-for-wp or if you have an active license to our premium plugin please email us at support@mc4wp.com.
