### ISSUE TITLE
Email Subscription Service Not Working

### ISSUE THREAD

**Issue by wmills2434** [ibericode/mailchimp-for-wordpress#598]
My website URL: https://fasteatrepeat.com/free-beginners-guide

### The issue
I've been informed when people enter their email using the link provided (for free PDF guide), they do not receive the confirmation message and no email is sent. Seems to be a bug, but I can't determine what the issue is.

### How can we reproduce this issue?
1. Enter your name and email
2. Click the "Send me free guide" button
3. Confirm that "Check your Inbox" message appears and email is received with PDF.

### Technical info
* WordPress version:
* MailChimp for WordPress version:
* Relevant plugins in case of a bug:

**Comment by dannyvankooten** [comment]
Hi @wmills2434,

Could you open a support topic on wordpress.org? That'll get you a much faster response, as this is most likely a configuration issue and not a bug in the plugin code itself.
