### ISSUE TITLE
552 Subscribers Auto Deleted for No Reason

### ISSUE THREAD

**Issue by AJF410** [ibericode/mailchimp-for-wordpress#599]
I had 803 Subscribers and for no reason at all MailChimp Auto deleted 552 of them on October 16th at 12:55pm (It notified me on the account, but gave no reason why)

I now have no access to those 552 people who were signups from my site, is there anyway to get them back?

**Comment by arnelap** [comment]
Are you using the UserSync add-on with default status set to "unsubscirbed"? That would unsubscribe your Wordpress users. You can set it to "subscribed" to subscribe them again. 

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
