### ISSUE TITLE
Form ID and editing issue

### ISSUE THREAD

**Issue by Kaylski** [ibericode/mailchimp-for-wordpress#600]
Form results in following error code on frontend:

"MailChimp for WordPress error: There is no form with ID 0, perhaps it was deleted?"

I am unable to edit the form, it says settings have been successfully changed but nothing changes. The ID in the shortcode is also defaulting to 0 which shows the above error code on the frontend.

### Technical info
* WordPress version: 4.9.8
* MailChimp for WordPress version: 4.2.5

**Comment by dannyvankooten** [comment]
Could you open a support topic on wordpress.org? That'll get you a much faster response, as this is most likely a configuration issue and not a bug in the plugin code itself.
