### ISSUE TITLE
Form not resetting after signup as requested

### ISSUE THREAD

**Issue by BroadwickLive** [ibericode/mailchimp-for-wordpress#603]
My website URL: https://www.printworkslondon.co.uk/

### The issue
Setting currently are set to have form remain visible even after signup.  Some computers are not seeing the form. There doesn't seem to be any consistency of the issue across any particular browsers or platforms.

### How can we reproduce this issue?
1.  Signup 
2.  Wait to see if the form resets or disappears even after reload.
3.

### Technical info
* WordPress version: 4.9.8
* MailChimp for WordPress version:  3.2.2
* Relevant plugins in case of a bug:  Top Bar

**Comment by dannyvankooten** [comment]
Hi @BroadwickLive,

Can you please try updating to the latest plugin version to see if the bug persists? The most recent version is 4.3.1. If the issue persists, please re-open this issue.

**Comment by BroadwickLive** [comment]
I'm not even seeing where that is an option.

________________

Don't forget...
1.  Put it on Trello!  *(Also tag your name on the Trello card.)*
2. Optimize your images
3. Clear your cache

Thanks!

Jenn Pike
Web Developer


P: +44 (0) 203 725 6060 <+44%2020%203725%206060>
M: +44 (0) 746 252 8494 <+44+(0)+7704+964105>
A: Camden Wharf, 28 Jamestown Road, London NW1 7BY
<https://maps.google.com/?q=28+Jamestown+Road,+London+NW1+7BY&entry=gmail&source=g>

Insta:  @broadwicklive

W: www.broadwicklive.com
Portfolio: Snowbombing - Snowbombing Canada - Festival Number 6 - Y Not
Festival - Truck Fest - Hideout - Kendal Calling - South West Four - Lost
Village - Standon Calling - Electric Elephant - Field Day - Boardmasters -
Victorious - Rewind North - Rewind South - Rewind Scotland - Transition -
Bacardi Triangle - Printworks London - Broadwick Agency


Please consider the environment before printing this e-mail
Broadwick Live Ltd is registered to Broadwick Live, Floor 3, Camden Wharf, 28
Jamestown Road, London NW1 7BY
<https://maps.google.com/?q=28+Jamestown+Road,+London+NW1+7BY&entry=gmail&source=g>
 Reg:08249491
