### ISSUE TITLE
product image urls are missing the domain name in Mailchimp

### ISSUE THREAD

**Issue by robdove** [ibericode/mailchimp-for-wordpress#604]
Some products in Mailchimp appear to have broken Image links due to the domain being missing from image source. It starts with /wp-content/uploads/.............. rather than https://www.domainname.com/wp-content/uploads/

### Technical info
Woocommerce: 3.5.2
Wordpress: 4.9.8
Mailchimp for Wordpress: 4.3.1

**Comment by dannyvankooten** [comment]
Hi @robdove,

Could you post a list of plugins that are activated on your website?

**Comment by arnelap** [comment]
Since there have been no replies for awhile I will now mark this topic as "resolved". If you are still experiencing this issue or you have a similar problem, please create a NEW issue. Thank you!
