### ISSUE TITLE
How do I disable auto sync with existing users?  Can it be set to only sync new users and not logins?

### ISSUE THREAD

**Issue by scottallanaz** [ibericode/mailchimp-for-wordpress#605]
My website URL: 

### How can we reproduce this issue?
1.
2.
3.

### Technical info
* WordPress version:
* MailChimp for WordPress version:
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
