### ISSUE TITLE
New sign ups not adding to MailChimp list

### ISSUE THREAD

**Issue by bazmanchester18** [ibericode/mailchimp-for-wordpress#606]
My website URL: https://www.robertsoncooper.com/test/ (the form is in the footer on the right)

### The issue
I have added the short code to the CF7 form for the checkbox, and it was adding contacts to the list. 

But in the last 24 hours it has stopped working. The form works, and submits the data but it does not appear in my list in MailChimp.

Wordpress did update last night to 4.9. Could this be the issue?

### How can we reproduce this issue?
You cannot recreate it without my admin accounts.

### Technical info
* WordPress version: 4.9
* MailChimp for WordPress version: Version 4.3.2
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
