### ISSUE TITLE
Error - mailchimp for wordpress

### ISSUE THREAD

**Issue by studiobm** [ibericode/mailchimp-for-wordpress#607]
My website URL: http://beaumarket.com

### The issue

I cant suscribe to the newsletter in the footer, when i put my email, it writes directly "error"
what can i do ?

### Technical info
* WordPress version:
* MailChimp for WordPress version: free
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
