### ISSUE TITLE
Error connecting to MailChimp: 503 Service Unavailable 

### ISSUE THREAD

**Issue by 123create** [ibericode/mailchimp-for-wordpress#608]
My website URL: https://www.martingodwinequine.com/martin-godwin-equine-services-home

### The issue:  I have been around and around and around with this issues between my host provider and mailchimp.  Mailchimp have come back with this:

I've taken a few moments to review your screenshot provided in the previous support ticket, and I can see that you're using the "MailChimp for WordPress" by Ibericode plugin.  Although the "MailChimp for Wordpress" plugin uses our name, it was developed by a third-party company named Ibericode and is not actually associated with us. In cases like this, it is normally best to reach out to Ibericode. 

However, in the interest of helping as much as possible I was able to locate a Support page that goes over that exact error: https://kb.mc4wp.com/solving-connectivity-issues/

It appears that this is a case where the IP address of your website may be blacklisted by an Akamai firewall. See: the [403 "Forbidden" or 503 "Service Unavailable"] section of the above article.  The recommended solution by the 'MailChimp for WordPress' developers is to change your IP address. 

This site has been delayed to go live for 3 weeks now looking for the answer to the issue.

Can you please help as quickly as possible?

Thank you in advance.
Michell

### How can we reproduce this issue?
1.
2.
3.

### Technical info
* WordPress version:
* MailChimp for WordPress version:
* Relevant plugins in case of a bug:

**Comment by hchouhan** [comment]
Hello,

I would request you to please email us at support@mc4wp.com for support. This channel is for creating bug report only. 
Also, please check https://kb.mc4wp.com/solving-connectivity-issues/. The advanced section provides a way to debug the issue you are facing.
