### ISSUE TITLE
Issue with CF7 & MC4WP 

### ISSUE THREAD

**Issue by ytimid2019** [ibericode/mailchimp-for-wordpress#611]
### The issue

I have CF7 and MC4WP installed, form all works great, success messages etc, email gets fired off no problem. However, the data that is injected into Mailchimp is effectively the contents of the reply-to: box:

Debug report says:-
[2019-01-22 08:26:51] WARNING: Contact Form 7 > from_email|emaill**********@st**********.co.uk is already subscribed to the selected list(s)

### Technical info
* WordPress version: 5.03
* MailChimp for WordPress version: 4.3.3
* Relevant plugins in case of a bug: Contact Form 7 version 5.1.1

**Comment by arnelap** [comment]
Since there have been no replies for awhile I will now mark this topic as "resolved". If you are still experiencing this issue or you have a similar problem, please create a NEW topic. Thank you!
