### ISSUE TITLE
MailChimp User Sync;  'Vendor' is specified 'Role To Sync', but all roles are Syncing to Vendor List

### ISSUE THREAD

**Issue by cautious1** [ibericode/mailchimp-for-wordpress#614]
My website URL: 

### The issue
I want to send a mail campaign to users with  Vendor role designation.

However, upon signup,  all roles (customer, subscriber etc) are getting synced into my MailChimp Vendor list.    

I have set the 'Role To Sync' drop down box to Vendor but it seems all roles are receiving email campaigns meant for only the Vendors.  

### How can we reproduce this issue?
1. You would need access to my WP Admin and Mailchimp account 
2.
3.

### Technical info
* WordPress version:  
* MailChimp for WordPress version: Version 4.3.3
* MailChimp UserSync: Version 1.7.6
* Relevant plugins in case of a bug: 4.9.8

**Comment by arnelap** [comment]
Hi,

Maybe you have the Wordpress registration integration activated as well as UserSync, and these other roles come in via the registration integration or any other integrations such as Woocommerce checkout. 

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp

Thanks
