### ISSUE TITLE
WP_Widget in NS_Widget_MailChimp is deprecated since version 4.3.0

### ISSUE THREAD

**Issue by lewiskofsky** [ibericode/mailchimp-for-wordpress#615]
My website URL: growingheartfarm.com

### The issue
when using Mailchimp Word press plugin I get this error

Notice: The called constructor method for WP_Widget in NS_Widget_MailChimp is deprecated since version 4.3.0! Use
__construct()
instead. in /home/growheart/growingheartfarm.com/wp-includes/functions.php on line 3986

Warning: Cannot modify header information - headers already sent by (output started at /home/growheart/growingheartfarm.com/wp-includes/functions.php:3986) in /home/growheart/growingheartfarm.com/wp-admin/includes/misc.php on line 1144

### How can we reproduce this issue?
1. upgrade wordpress to latest
2. put wordpress into debug
3. use mailchimp wp plugin

### Technical info
* WordPress version: WordPress 5.0.3 running TM Organik theme
* MailChimp for WordPress version:  Version 4.3.3 
* Relevant plugins in case of a bug:

**Comment by dannyvankooten** [comment]
Hey @lewiskofsky,

That widget class isn't present in our plugin, so looks like you're using another plugin. Perhaps you're using "Newsletter Sign-Up" instead?

**Comment by lewiskofsky** [comment]
you are correct.  it was an out of date and older WP plugin

**Comment by dannyvankooten** [comment]
Glad to hear it @lewiskofsky, thanks for the update!
