### ISSUE TITLE
Oxygen Builder incompatibility

### ISSUE THREAD

**Issue by luismuv** [ibericode/mailchimp-for-wordpress#617]
My website URL: https://www.vetprep.net.au

### The issue
MailChimp for WordPress is incompatible with Oxygen Builder.

### How can we reproduce this issue?
1. Install and activate Oxygen Builder
2. Install and activate Mailchimp for Wordpress
3. when you edit a page with Oxygen you will see javascript issues related to a Google Maps API key which stops the page from loading properly.

### Technical info
* WordPress version: 5.0.3
* MailChimp for WordPress version: 4.3.3
* Relevant plugins in case of a bug: Oxygen Builder 2.1.2

**Comment by arnelap** [comment]
Hi, 

Can you please create a support ticket here; https://wordpress.org/support/plugin/mailchimp-for-wp

Please include the full exact Javascript errors you see in in your post there. 

I'm not sure how Google Maps API is related to our plugin, so I'm hoping that the errors would clarify that. 

I see Oxygen Builder is a paid Wordpress plugin, so we are not able to test this ourselves. 

If you have a license for Premium support please contact us via the help button in the plugin. 

Thanks!
