### ISSUE TITLE
Mailchimp subscribe not aligned

### ISSUE THREAD

**Issue by tsiridakis** [ibericode/mailchimp-for-wordpress#618]
My website URL: axlimperial.com

### The issue
The sign up button is not aligned correctly. Also how can I change the input color?

### How can we reproduce this issue?
1.
2.
3.

### Technical info
* WordPress version:
* Mailchimp for WordPress version:
* Relevant plugins in case of a bug:
![prnt](https://user-images.githubusercontent.com/48219070/53750512-a384c900-3eb2-11e9-96fa-dccbf942883d.jpg)

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
