### ISSUE TITLE
Verification Methods

### ISSUE THREAD

**Issue by mohammedmousa1** [ibericode/mailchimp-for-wordpress#619]
My website URL: https://live24ksa.com

### The issue
When the visitor subscribes for the signup form which I made from the MailChimp wordpress plugin, he must verify his subscription by validating his email from the inbox.
This is an issue for me and for the visitors that do not like more than 1 step to do.
I want to know how I can cancel this verification step, please,
Thanks in advance.

### How can we reproduce this issue?
1. We need an option that allows us to inactive " more than 1 step subscription " and make it easier for the consumer.
2. 
![2](https://user-images.githubusercontent.com/46036236/54079896-3926bb00-42ee-11e9-81d3-f1a8c60062a6.PNG)

3.

### Technical info
* WordPress version:
* Mailchimp for WordPress version:
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
You can turn off double opt-in under MailChimp for WP > Form > Settings. 

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
