### ISSUE TITLE
Pop-up Not functioning correctly

### ISSUE THREAD

**Issue by Godwme** [ibericode/mailchimp-for-wordpress#620]
My website URL: www.AllyCards.net

### The issue
I set the pop up to only show on the main page. It functions correctly, however on each additional page the pop up shows up but without the fields. It should not show at all. When clicking the Do not show this message again, it still continues to pop up, which annoys customers.

### How can we reproduce this issue?
1.
2.
3.

### Technical info
* WordPress version: 
* Mailchimp for WordPress version:
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp

Also please note we only provide support when you are using our plugin(s). Mailchimp for Wordpress doesn't have any popup feature build in, but we do recommend using our other plugin Boxzilla for that. 
https://kb.mc4wp.com/pop-up-integration/

Hope that helps. If you have any questions, please let us know on the Wordpress .org forums.
