### ISSUE TITLE
Screen options pagination not working

### ISSUE THREAD

**Issue by andrea007** [ibericode/mailchimp-for-wordpress#622]
My website URL: https://digitalhealthrewired.com

### The issue
I have Event espresso plugin installed. When I go to teh registration page to view my list of registrants on 10 at a time displays. When I go to Screen Options and change the pagination to 100 as we have over 2000 registrants, nothing happens. I deactivaed all my plugins and reactivated one at a time and tested again. This time the pagination worked. . When I reactivated Mailchimp for wordpress it stopped working again. I reactivated all the plugin except your and the pagination worked. As soon as I reactivated you the pagination stopped.

### How can we reproduce this issue?
1. install Event esspresso
2. Install mailchimp for wordpress
3. Go to Event espresso Registration page
4. Go to screen Options and change pagination 

### Technical info
* WordPress version: The version before 5.11
* Mailchimp for WordPress version: 4.4
* Relevant plugins in case of a bug: Version Event Espresso - 4.9.79.p Get Version 5.1.1

**Comment by dannyvankooten** [comment]
Thanks for the report @andrea007, this is fixed in our next release of Mailchimp for WordPress Premium!
