### ISSUE TITLE
email site admin on error

### ISSUE THREAD

**Issue by arnelap** [ibericode/mailchimp-for-wordpress#623]
It would be a nice premium feature to automatically email an error to site admin to notify about things such as missing api key, error 503 etc. 

https://secure.helpscout.net/conversation/807378320/17178?folderId=253120

**Comment by dannyvankooten** [comment]
Relates to #162

**Comment by dannyvankooten** [comment]
Actually, duplicate of #162. But I am very slowly warming up to the idea, so there is some progress on this!
