### ISSUE TITLE
Background Field Color

### ISSUE THREAD

**Issue by composerdude** [ibericode/mailchimp-for-wordpress#627]
My website URL: https://jordanseigel.com/

### The issue
On my signup form widget, only the "Email Address" field has a white background. The "First Name" and "Last Name" fields are the same color as the background. How can I get the Name fields to be white as well? Shouldn't this be the default?
Thanks in advance for any assistance!

### How can we reproduce this issue?
1. Go to my website and check out the footer, or check out the screen shot
2.
![image](https://user-images.githubusercontent.com/49380014/55693036-aebf8e80-5961-11e9-9005-f3b671e7ecc1.png)

3.

### Technical info
* WordPress version: 5.1.1
* Mailchimp for WordPress version: 4.5.0
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
