### ISSUE TITLE
GF_Field::get_conditional_logic_event deprecated in Gravity Forms 2.4 and up

### ISSUE THREAD

**Issue by firstchair** [ibericode/mailchimp-for-wordpress#629]
https://github.com/ibericode/mailchimp-for-wordpress/blob/661e429c5e85a2fd38a35393f0e5e97fd0be0e02/integrations/gravity-forms/class-field.php#L112

Maybe change to: `$logic_event = version_compare( GFForms::$version, '2.4-beta-1', '<' ) ? $this->get_conditional_logic_event( 'keyup' ) : '';`

**Comment by elanclarkson** [comment]
+1 also getting this deprecation notice
