### ISSUE TITLE
Form Not Working

### ISSUE THREAD

**Issue by jonathanballcom** [ibericode/mailchimp-for-wordpress#630]
My website URL: www.jonathanball.com

### The issue

My form isn't working: gives the message "Oops. Something went wrong. Please try again later." However, on the backend, it says that the account is CONNECTED.

### How can we reproduce this issue?
1. Go to www.jonathanball.com
2. Scroll down to the form
3. Try to sign up for my newsletter in the mailchimp-for-wordpress form

### Technical info
* WordPress version: 5.1.1.
* Mailchimp for WordPress version: 4.5.1.
* Relevant plugins in case of a bug: Mailchimp for Wordpress

**Comment by lechu1985** [comment]
I have the same problem but on a different config: 
Wordpress@4.9.8 with MailChimp for wordpress@4.3.1)
How can I help debug the problem?

**Comment by dannyvankooten** [comment]
Hi @jonathanballcom and @lechu1985,

Are there any errors listed on the WP Admin > Mailchimp for WP > Other page?

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
