### ISSUE TITLE
Can't modify forms: Form preview launches automatically!

### ISSUE THREAD

**Issue by Melica9** [ibericode/mailchimp-for-wordpress#631]
My website URL: www.yumi.fr

### The issue
I've just installed Mailchimp for Wordpress app & I have some issues... 
Everything seem to work well except from the form part. 
When I try to create a form, as soon as I click on the link to access the feature, the url transforms automatically from "https://www.yumi.fr/wp-admin/admin.php?page=mailchimp-for-wp-forms&view=edit-form&form_id=464859" to "https://www.yumi.fr/?mc4wp_preview_form=464859" which is a preview of an pre-existing form... 

### How can we reproduce this issue?
1. go to the app
2. click on "Forms"
3. the page url will automatically switch.

### Technical info
* WordPress version: 5.1.1
* Mailchimp for WordPress version: 4.5.2
* Relevant plugins in case of a bug: Mailchimp for WordPress

**Comment by dannyvankooten** [comment]
Hi @Melica9,

Do you have our Mailchimp for WordPress Premium plugin activated?

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp or if you are using the Premium add-on please email us at support @ mc4wp .com Thanks!!
