### ISSUE TITLE
Mailchimp for Wordpress popup form redirects to thank-you page properly on desktop, but not on mobile

### ISSUE THREAD

**Issue by MeditationMama** [ibericode/mailchimp-for-wordpress#634]
My website URL: 
www.heartsunyoga.com

### The issue
Put a Mailchimp for Wordpress popup form on my site, been testing it all day. It's great! On desktop, it redirects successfully to the thank you page. It seems that on mobile, it redirects to the Index page of the site (home page). Not sure why?

### How can we reproduce this issue?
1. visit www.heartsunyoga.com/get-a-free-meditation  -- on desktop. fill out your first name & an email address. Email address will receive a welcome email with a download PDF. Once you hit submit on the form you will be directed to the thank you page.
2. Repeat the signup process above -- this time from a mobile device (phone). This time it will redirect to the website's home page instead of the thank-you page.

### Technical info
* WordPress version: 5.2.1
* Mailchimp for WordPress version: free version
* Relevant plugins in case of a bug: Elementor (not sure if relevant)

**Comment by dannyvankooten** [comment]
Hey @MeditationMama,

Could it be that your "thank you" page is causing this? I can't think of anything in the plugin that would do this, so my theory is that you are actually redirected to the thank you page on mobile as well but that in turn just redirects you to your home page again...
