### ISSUE TITLE
I cannot deactivate or delete the plugin -  causing .css style loading issues on my site

### ISSUE THREAD

**Issue by silviasamna** [ibericode/mailchimp-for-wordpress#635]
My website URL:  www.casacuadrau.org

### How can we reproduce this issue?
1. Go to Installed Plugins
2. (Try to) Deactivate plugin
3. (Try to) Delete plugin

### Technical info
* WordPress version: 5.2.1
* Mailchimp for WordPress version: 4.5.2
* Relevant plugins in case of a bug:

**Comment by Christian1998** [comment]
Issue is solved?
If not - why dont delete the folder /%root%/wp-content/plugins/%name of the plugin%?

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
