### ISSUE TITLE
Recaptcha v3 error when enabled

### ISSUE THREAD

**Issue by MarkWest2017** [ibericode/mailchimp-for-wordpress#636]
My website URL: www.edge-tax.com

### The issue
Hi,
I am running WordPress v5.2.1 and Mailchimp for WP v4.5.2 and PHP 7.3
If Recaptcha v3 is disabled in Mailchimp for WP the sign-up form submits fine.
If I enable Recaptcha v3 and add the keys I get the following error:
‘Oops. Something went wrong. Please try again later.’
Nothing is displayed in the Mailchimp for WP debug log and no attempt is logged in the Mailchimp API access log – so it seems like the issue is local to the site/plug-in.
I've also logged this issue on the WP.org support page - hoping it can be investigated/resolved soon.
Recaptcha is currently disabled on the sign-up form, so you won't be able to see the issue on the site from the front-end.
Thanks
Mark

### How can we reproduce this issue?
1. Install Mailchimp for Wp
2. Enable Recaptcha
3. Attempt to submit a sign-up form

### Technical info
* WordPress version: 5.2.1
* Mailchimp for WordPress version: 4.5.2
* Relevant plugins in case of a bug: Mailchimp for WordPress

**Comment by arnelap** [comment]
@dannyvankooten This error has come up a few times, when there is no proper API key filled there should be an error about this when saving the setting as well as when submitting the form.

**Comment by dannyvankooten** [comment]
@arnelap Agreed! Should have been fixed in a07b7fa0cbcd10943c23321f16f526a534325a50
