### ISSUE TITLE
MailChimp Plug-In Works, But Doesn't Acknowledge Submission/Redirect to Site

### ISSUE THREAD

**Issue by RestoreJustice** [ibericode/mailchimp-for-wordpress#641]
My website URL: restorejustice.org

### The issue
I created a form for people to sign up to our MailChimp list. I have tested with sign-ups and know the form works (and the names go into our database). But, there's no indication it's worked on the user's end. The successful sign-up language doesn't appear, and the site doesn't redirect. 

### How can we reproduce this issue?
1.
2.
3.

### Technical info
* WordPress version:
* Mailchimp for WordPress version:
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
