### ISSUE TITLE
Accessibility Errors

### ISSUE THREAD

**Issue by hchouhan** [ibericode/mailchimp-for-wordpress#648]
Screenshots:
https://prnt.sc/paui0k
https://prnt.sc/paujqe

Open Tickets:
- https://wordpress.org/support/topic/accessibility-errors-5/

**Comment by dannyvankooten** [comment]
Looks like we already print the label text inside the `<label>` element, which wraps the `<input type="checkbox" />` so it looks like this is a configuration issue and not an issue in the plugin itself?
