### ISSUE TITLE
add custom tags not working

### ISSUE THREAD

**Issue by sarin-citrus** [ibericode/mailchimp-for-wordpress#650]
Hi... i am using user sync add on to sync my users to mailchimp..i want to add a custom tag when a new user is registered..
I created "Email Registration" tag on mailchimp backend and added this code to my **functions.php**
```
add_filter( 'mailchimp_sync_subscriber_data', function(MC4WP_MailChimp_Subscriber $subscriber) {
   $subscriber->tags[] = 'Email Registration';
   return $subscriber;
},10, 2);
```

but its not working.user email is syncing correctly to mailchimp but user tag is not added.please let me know what i am doing wrong
Thank You

**Comment by hchouhan** [comment]
Hello,

That code should work for new subscribers but it would not work if an existing subscriber is getting updated. When testing did you make sure the email that is being synced does not exist in MailChimp?

P.S. In future for support please contact us at https://wordpress.org/support/plugin/mailchimp-for-wp/ or through the email listed on our website if you have a premium license.
