### ISSUE TITLE
Subscription form is not working!

### ISSUE THREAD

**Issue by Sattawa22** [ibericode/mailchimp-for-wordpress#651]
My website URL: www.mujeralquimia.com

### The issue
Mailchimp for wordpress subscription form is not working. I haven't change anything from the html code, but when you click on the "subscribe me" button, it does nothing.

### How can we reproduce this issue?
1.Trying to subscribe to my website here: https://mujeralquimia.com/newsletter/
2.
3.

### Technical info
* WordPress version: 5.2.3
* Mailchimp for WordPress version: 4.6.1
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
the form works for me, don't forget youa dded that checkbox in the bottom that you need to check, and your theme put the label of the checkbox on a newline. 

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
