### ISSUE TITLE
Updating tags of existing user

### ISSUE THREAD

**Issue by hchouhan** [ibericode/mailchimp-for-wordpress#655]
-https://secure.helpscout.net/conversation/988165879/19428/
- https://stackoverflow.com/questions/52298226/how-to-add-tags-to-mailchimp-subscriber-via-the-api

**Comment by friendlyintruder** [comment]
Not completely sure if this is related but I saw that this setting - https://kb.mc4wp.com/what-does-replace-groupings-mean/#utm_source=wp-plugin&utm_medium=mailchimp-for-wp&utm_campaign=settings-page
tags people, that are not yet on the list, with the tag specified on the settings page. However, when a person is already subscribed the tag is not added to the mailchimp contact even if "Update existing subscribers" has been activated.

**Comment by hchouhan** [comment]
@friendlyintruder Please note that the tags can only be added to new subscribers. I would recommend using "Interest groups".

**Comment by edwindekuiper** [comment]
Although the plugin suggest that interested are added, tags will not be updated or added...

> "Please note that the tags can only be added to new subscribers. I would recommend using "Interest groups"."

Is this a official? Because this means that you will have a lot of lists... and double entries. Tags are more flexible

**Comment by topaz-rep** [comment]
Up! is there any solution of this problem?

**Comment by carloseduardovieira** [comment]
> Up! is there any solution of this problem?

Hello, I made a pull request to fix this problem. I'm waiting approval by the plugin team.
