### ISSUE TITLE
Foreign language not translated in frontend although language file is stored

### ISSUE THREAD

**Issue by dnlhdt** [ibericode/mailchimp-for-wordpress#660]
Hey,
my primary language (German) is not being translated in the frontend. Especially the sentences from _wp-content/plugins/mailchimp-for-wp/config/default-form-messages.php_. All other plugins and the theme are translating into the frontend without problems. The translation files are stored and tested in the plugin folder as well as on the system. Please help. Thanks!

WordPress version: 5.3
Mailchimp for WordPress version: 4.7
PHP version: 7.3

**Comment by dannyvankooten** [comment]
Hey @dnlhdt,

Did you manage to resolve this somehow?

**Comment by dnlhdt** [comment]
Yes. The translations have to be stored in the plugin settings. I guess I just thought too complicated. I thought that the translations had to be stored in the translation files. .pot -> .mo/.po. Best.
