### ISSUE TITLE
PHP Notice: Trying to get property 'status' of non-object

### ISSUE THREAD

**Issue by dashkevych** [ibericode/mailchimp-for-wordpress#661]
### The issue

There is PHP notice once the form is submitted. See screenshot:

![PHP Notice: Trying to get property 'status' of non-object](https://i.snipboard.io/UH8PBd.jpg)

### How can we reproduce this issue?
1. Fill the newsletter form
2. Submit the form

### Technical info
* WordPress version: 5.3
* Mailchimp for WordPress version: Version 4.7 
* Local environment (VVV: https://github.com/Varying-Vagrant-Vagrants/VVV)

**Comment by dannyvankooten** [comment]
Hey @dashkevych,

Thanks for the heads up, this was fixed in eaa5ee8d91d01dc629ca2c72bdb75bc3788529f4 but we've yet to release a plugin update for it.
