### ISSUE TITLE
Error on dates

### ISSUE THREAD

**Issue by sirtronics** [ibericode/mailchimp-for-wordpress#662]
My website URL: http://www.theapplehillacademy.com/leadfreehold/

### The issue[2019-12-02 19:10:10] ERROR: Form 5083 > Mailchimp API error: 400 Bad Request. Invalid Resource. Your merge fields were invalid.
- CDATE : Please enter the date
- TDATE : Please enter the date
Request: POST https://us10.api.mailchimp.com/3.0/lists/f59bc83b1d/members - {"status":"subscribed","email_address":"Isab*****@gm***.com","interests":{},"merge_fields":{"CDATE":"DecDec\/MonMon\/2019201920192019","CENTER":"Kiddie Academy","CNAME":"Chelsea","FNAME":"Lisa","GIVEN":"Helene","INCARE":"Yes","INFO":"Wants to start ASAP, Probality Jan. Needs M.W.F full days","LNAME":"Sabia","PROGRAM1":"Pre-K","SOURCE":"Drive By","TAGE":"6\/6\/15","TAMPM":"AM","TDATE":"DecDec\/ThuThu\/2019201920192019","TOUR":"Set up Tour","TPHONE":"201-341-4061","TTIME":"7:15"},"email_type":"html","ip_signup":"47.20.121.39","tags":[]}
Response: 400 Bad Request - {"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"Invalid Resource","status":400,"detail":"Your merge fields were invalid.","instance":"1461983d-ca27-4210-83c7-701c108c6e0d","errors":[{"field":"CDATE","message":"Please enter the date"},{"field":"TDATE","message":"Please enter the date"}]}

### How can we reproduce this issue?
1. Was working fine untill the update
2. Cdate is automatically inputed
3. Here is the code (nothing has changed)
<br /><br />
<table style="table-layout: fixed; width: 80%;" cellpadding="4"> <!-set table layout to fixed and width to full width -->
    <colgroup>
        <col style="width: 25%" /> <!- "auto"takes the remaining space -->
        <col style="width: 20%" /> <!- or use 33.3333% for all instead if you want to occupy full width -->
        <col style="width: 25%" />
        <col style="width: 20%" />
    </colgroup>
  <tbody>
<td><span style="font-family: 'times new roman', times, serif; font-size: 14pt;color: #ffffff;">First Name</span></td>
<td><span style="font-family: 'times new roman', times, serif; font-size: 14pt;color: #ffffff;">Last Name</span></td>
<td><span style="font-family: 'times new roman', times, serif; font-size: 14pt;color: #ffffff;">Email:</span></td>
<td><span style="font-family: 'times new roman', times, serif; font-size: 14pt;color: #ffffff;">Phone:</span></td>
</tr>
<td><span style="color: #000000;"><input id="mce-FNAME" class="name" name="FNAME" required="" size="1" type="text" /></span></td>
<td><span style="color: #000000;"><input id="mce-LNAME" class="name" name="LNAME" required="" size="10" type="text" /></span></td>
<td><span style="color: #000000;"><input id="mce-EMAIL" class="name" name="EMAIL" required="" size="1" type="text" /></span></td>
<td><span style="color: #000000;"><input id="mce-PHONE" class="name" name="TPHONE" required="" size="1" type="text" /></span></td>
</tr>

<td><span style="font-family: 'times new roman', times, serif; font-size: 14pt;color: #ffffff;">Address:</span></td>
<td><span style="font-family: 'times new roman', times, serif; font-size: 14pt;color: #ffffff;">City:</span></td>
<td><span style="font-family: 'times new roman', times, serif; font-size: 14pt;color: #ffffff;">State:</span></td>
<td><span style="font-family: 'times new roman', times, serif; font-size: 14pt;color: #ffffff;">Zip:</span></td>
</tr>

<td style="width: 150px; height: 1px;"><span style="color: #000000;"><input id="mce-ADDRESS" class="name" name="ADDRESS" size="1" type="text" /></span></td>
<td style="width: 150px; height: 1px;"><span style="color: #000000;"><input id="mce-CITY" class="name" name="CITY" size="1" type="text" /></span></td>
<td style="width: 150px; height: 1px;"><span style="color: #000000;"><input id="mce-STATE" class="name" name="STATE" size="1" type="text" /></span></td>
<td style="width: 150px; height: 1px;"><span style="color: #000000;"><input id="mce-ZIP" class="name" name="ZIP" size="1" type="number" step="0.01" /></span></td>
</tr>    

<td><span style="font-family: 'times new roman', times, serif; font-size: 14pt;color: #ffffff;">1st Child's Name</span></td>
<td><span style="font-family: 'times new roman', times, serif; font-size: 14pt;color: #ffffff;">Age</span></td>
</tr>

<td><span style="color: #000000;"><input id="mce-CNAME" class="name" name="CNAME" type="text" /></span></td>
<td><span style="color: #000000;"><input id="mce-TAGE" class="name" name="TAGE" type="text" /></span></td>
<td span style="font-family: 'times new roman', times, serif; font-size: 14pt; color: #ffffff;">
    <select name="PROGRAM1" required="" >
        <option disabled="" value="" selected="true">Interested Classroom</option>
      <option value=" ">N/A</option> 
      <option value="Infants">Infant</option>
      <option value="Toddlers">Toddler</option>
      <option value="Twos">Terrific Twos</option>
      <option value="Preschool">Preschool</option>
      <option value="Pre-K">Pre-K</option>
 	  <option value="Before Care">Before Care</option>
      <option value="After Care">After Care</option>
      <option value="Before and After Care">Before and After Care</option>
       <option value="Summer Camp">Summer Camp</option>
      </select></td>   
</tr>
<td><span style="font-family: 'times new roman', times, serif; font-size: 14pt;color: #ffffff;">2nd Child's Name</span></td>
<td><span style="font-family: 'times new roman', times, serif; font-size: 14pt;color: #ffffff;">Age</span></td>
</tr>
<td><span style="color: #000000;"><input id="mce-CNAME2" class="name" name="CNAME2" size="10" type="text" /></span></td>
<td><span style="color: #000000;"><input id="mce-TAGE2" class="name" name="TAGE2" size="10" type="text" /></span></td>
<td span style="font-family: 'times new roman', times, serif; font-size: 14pt; color: #ffffff;">
    <select name="PROGRAM2">
        <option disabled="" value="" selected="true">Interested Classroom</option>
      <option value=" ">N/A</option>  
      <option value="Infants">Infant</option>
      <option value="Toddlers">Toddler</option>
      <option value="Twos">Terrific Twos</option>
      <option value="Preschool">Preschool</option>
      <option value="Pre-K">Pre-K</option>
      <option value="Before Care">Before Care</option>
      <option value="After Care">After Care</option>
      <option value="Before and After Care">Before and After Care</option>
      <option value="Summer Camp">Summer Camp</option>
      </select></td>
</tr>
<td></td>
</tr>
<td></td>
</tr>
<td span style="font-family: 'times new roman', times, serif; font-size: 14pt; color: #ffffff;">
    <select name="INCARE"  required="">
        <option disabled="" value="" selected="true">Is child currently in care</option>
        <option value="Yes">Yes</option>
        <option value="No">No</option>
      </select></span></td>
<td><span style="color: #000000; font-family: 'times new roman', times, serif;font-size: 14pt;"><input placeholder="Which Center" id="mce-CENTER" class="name" name="CENTER" size="10" type="text" /></span></td>
<td><span style="text-align:center;;font-family: 'times new roman', times, serif; font-size: 14pt; color: #ffffff;">
    <select name="SOURCE" required="">
        <option disabled="" value="" selected="true">How did they hear about us?</option>
        <option value="Drive By">Drive By</option>
        <option value="Facebook">Facebook</option>
      <option value="Friend">Friend</option>
      <option value="Google">Google</option>
      <option value="Web Search">Web Search</option>
      <option value="Yellow Pages">Yellow Pages</option>
      <option value="Yelp">Yelp</option>
      </select></span></td>
</tr>
<td></td>
</tr>
</tr>
<td></td>
</tr>

<td><span style="text-align:center;;font-family: 'times new roman', times, serif; font-size: 14pt; color: #ffffff;">
    <select name="TOUR" required="">
        <option disabled="" value="" selected="true">Type of lead?</option>
        <option value="Called for Information">Called for Information</option>
        <option value="Tour Today">Tour Today</option>
      <option value="Set up Tour">Set up Tour</option>
      <option value="Signed Up">Signed up</option>
      <option value="Toured">Toured</option>
      </select></span></td>
   <td><span style="color: #000000; font-family: 'times new roman', times, serif;font-size: 14pt;"><input placeholder="Date MM/DD/YYYY" id="mce-TDATE" class="name" name="TDATE" size="10" type="text" /></span></td>
<td><span style="color: #000000; font-family: 'times new roman', times, serif;font-size: 14pt;"><input placeholder="Only put time if this is for a tour" id="mce-TTIME" class="name" name="TTIME" size="10" type="text" /></span></td>
<td><span style="text-align:center;;font-family: 'times new roman', times, serif; font-size: 14pt; color: #ffffff;">
    <select name="TAMPM" >
        <option disabled="" value="" selected="true">AM / PM</option>
        <option value="AM">AM</option>
        <option value="PM">PM</option>
      </select></span></td>
</tbody>
</table>
<br /><br />

<table style=width="700" >
<td><span style="font-family: 'times new roman', times, serif; font-size: 14pt;color: #ffffff;">Notes:</span></td>
  </tr>
<td style="width: 550px; height: 5px;"><span style="color: #000000;"><input id="mce-INFO" class="name" name="INFO" required="" size="1" type="text" /></span></td>
</table>

<br /><br />

<p style="font-family: 'times new roman', times, serif; font-size: 14pt; color: #ffffff;">
    <select name="GIVEN" required="">
        <option disabled="" value="" selected="true">Call Taken By</option>
      <option value="Helene">Helene</option>  
      <option value="Jeanine">Jeanine</option>
      <option value="Jennifer">Jennifer</option>
      </select></p>

<input type="hidden" name="CDATE" value="{date}">
<p>
  <p style="text-align: center;"><input class="wpcf7-form-control wpcf7-submit" type="submit" value="Submit" /></p>
</p>

### Technical info
* WordPress version: 5.3 current
* Mailchimp for WordPress version: 4.7.2
* Relevant plugins in case of a bug:

**Comment by sirtronics** [comment]
took this from mailchimp:
![Capture](https://user-images.githubusercontent.com/58443279/70060698-0675ce80-15b1-11ea-8306-408e42104f97.JPG)

**Comment by dannyvankooten** [comment]
Hey, thank you for reporting. This is fixed in 9819b0bacdcd88807c135f1b708d3993b41ebd18, we'll be pushing out an official plugin update tomorrow morning.
