### ISSUE TITLE
htaccess syntax causing all images to be 403 on some hosting providers

### ISSUE THREAD

**Issue by arnelap** [ibericode/mailchimp-for-wordpress#663]
The syntax that is hiding the logfile seems to not always work correctly, sometimes hiding all the images of that site. 

https://secure.helpscout.net/conversation/1025396841/20397?folderId=253120

**Comment by arnelap** [comment]
https://secure.helpscout.net/conversation/1025940126/20408?folderId=253120

**Comment by arnelap** [comment]
Looks like your htaccess file won’t work with apache 2.4? https://htaccessbook.com/access-control-apache-2-4/

**Comment by dannyvankooten** [comment]
It doesn't look like Apache 2.4 is the issue, just tested the original syntax and it works just fine.

**Comment by sidedwards** [comment]
@dannyvankooten when can we expect a live patch for this? This just took all the images down on a clients site and took me an hour to figure out what happened :(

**Comment by dannyvankooten** [comment]
@sidedwards Sorry to hear that. :( We released an update in which this should be addressed on Saturday already, but if the faulty htaccess was already in place at that time it wouldn’t be fixed retroactively.

If you trigger a debug log message (eg by setting it to log everything, then using a form), does the issue re-appear?

**Comment by sidedwards** [comment]
@dannyvankooten Yes the issue reappears.

**Comment by badcrocodile** [comment]
I see this issue is marked Closed but I don't see mention of the fix. I'm running into this issue on 2 sites, version 4.8.1.

**Comment by badcrocodile** [comment]
Thanks @devondragon for the tip. Adding AuthConfig to my AllowOverride in apache vhost for that site worked perfectly. Totally agree on you that such flaky code practices should not be included in this plugin though.
