### ISSUE TITLE
Call to undefined method stdClass::get_web_url() in .../mc4wp-premium/logging/includes/class-log-table.php:207

### ISSUE THREAD

**Issue by wired79** [ibericode/mailchimp-for-wordpress#665]
### The issue
I received this e-mail from WP:

Error details
===============
A(z) wp-content/plugins/mc4wp-premium/logging/includes/class-log-table.php fájl 207 sora egy E_ERROR típusú hibát okoz. Hibaüzenet: Uncaught Error: Call to undefined method stdClass::get_web_url() in wp-content/plugins/mc4wp-premium/logging/includes/class-log-table.php:207
Stack trace:
#0 .../wp-admin/includes/class-wp-list-table.php(1356): MC4WP_Log_Table->column_list(Object(MC4WP_Log_Item))
#1 .../wp-admin/includes/class-wp-list-table.php(1301): WP_List_Table->single_row_columns(Object(MC4WP_Log_Item))
#2 .../wp-admin/includes/class-wp-list-table.php(1288): WP_List_Table->single_row(Object(MC4WP_Log_Item))
#3 .../wp-admin/includes/class-wp-list-table.php(1273): WP_List_Table->display_rows()
#4 .../wp-admin/includes/class-wp-list-table.php(1204): WP_List_Table->display_rows_or_placeholder()
#5 .../wp-content/plugins/mc4wp-premium/logging/views/admin-reports-log.php(13): WP_List_Table->d

### How can we reproduce this issue?
1. Maybe I clicked the Stat admin panel.

### Technical info
* WordPress version: 5.3.2
* Mailchimp for WordPress version:
    MC4WP: Mailchimp for WordPress: 4.7.4
    MailChimp for WordPress - Premium: 4.5.7
* Relevant plugins in case of a bug:

**Comment by dannyvankooten** [comment]
Hey @wired79,

Looks like you're on an old version of the MailChimp for WordPress - Premium plugin. Updating it to a more recent version should get rid of the issue right away.

The most recent version is 4.7.3, you can see the full [changelog here](https://my.mc4wp.com/plugins/1/changelog).
