### ISSUE TITLE
Mailchimp API error: 400 Bad Request. Forgotten Email Not Subscribed

### ISSUE THREAD

**Issue by Buildzzz** [ibericode/mailchimp-for-wordpress#666]
My website URL: yup.gg/brand-solutions

### The issue
In testing the plugin, we are able to add a new user and update user seems to be working.  However once a user has been subscribed and we go into Mailchimp and permanently delete that user, they can't sign up again b/c of this error:

ERROR: Form 8319 > Mailchimp API error: 400 Bad Request. Forgotten Email Not Subscribed

How do we resubscribe emails and resolve this issue?  Mailchimp says that the user needs to be resubscribed through a signup-form.  However, it seems your plugin isn't counting this use case?

### How can we reproduce this issue?
1. Try signing up with 'test@yup.gg' as the email. 
2. You will see Oops something went wrong.
3. You can see the error in the debug logs

### Debug logs for your reference
[2020-01-18 17:47:07] ERROR: Form 8319 > Mailchimp API error: 400 Bad Request. Forgotten Email Not Subscribed. test@yu*.gg was permanently deleted and cannot be re-imported. The contact must re-subscribe to get back on the list.
Request: POST https://us20.api.mailchimp.com/3.0/lists/eda3ae5921/members - {"status":"subscribed","email_address":"test@yu*.gg","interests":{},"merge_fields":{"COMPANY":"TESTING","COMPANY_SI":"1-20 employees",}
Response: 400 Bad Request - {"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"Forgotten Email Not Subscribed","status":400,"detail":"test@yu*.gg was permanently deleted and cannot be re-imported. The contact must re-subscribe to get back on the list.","instance":"d95c30de-b861-4fa4-a8cb-9c88d0a8efcb"}

**Comment by hchouhan** [comment]
Hello,

This is a restriction set by MailChimp.com, so it's not possible to add a user via API or 3rd party forms who were deleted. The only way to subscribe them again is by using the MailChimp's hosted form.

**Comment by Buildzzz** [comment]
Hello,

I appreciate the feedback. Thx!

**Comment by anj-hanpoom** [comment]
Hi @hchouhan, I'm having the same issue here. User can't resubscribe if they unsubscribe from a Mailchimp link.  Just a question, hope you could help me with this.

Is there a way we can prevent this error from happening? 
Instead of pointing users to Mailchimp unsubscribe link, is there an available unsubscribe feature from the plugin? 

If yes:
1. is this sure that they going to stop receiving emails from us?
2. User can easily resubscribe on plugin provided input field?
