### ISSUE TITLE
Subscribing not working on mobile devices

### ISSUE THREAD

**Issue by janinewhitling01** [ibericode/mailchimp-for-wordpress#667]
My website URL: janinewhitling.com.au

### The issue
nobody can subscribe when using their mobile devices

### How can we reproduce this issue?
1. try to subscribe on your phone
2.
3.

### Technical info
* WordPress version: latest
* Mailchimp for WordPress version: 4.7.4
* Relevant plugins in case of a bug:

**Comment by janinewhitling01** [comment]
actually, it seems that you can't subscribe on laptops or desktops either. it says "error, that action is currently not allowed"

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
