### ISSUE TITLE
Multiple orders created when there are suborders in Woocommerce

### ISSUE THREAD

**Issue by DanielMo123** [ibericode/mailchimp-for-wordpress#670]
My website URL: www.gearfurther.com

### The issue 
Multiple orders are sent to Mailchimp when there are suborders in Woocommerce. One for each suborder and one for the main order. 

### How can we reproduce this issue?
1. create an order with a suborder in wordpress. 
2. sync orders with mailchimp

### Technical info
* WordPress version: 5.3.2
* Mailchimp for WordPress version: 4.7.4
* Relevant plugins in case of a bug: WC Marketplace

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp

If you use the Premium add-on it's best to contact Premium support department by clicking the Help button on the right bottom of the screen while in the MailChimp for Wordpress setting screens in your Wordpress admin.

If you didn't already contact us through a support channel about this, please do so and include what exactly you use for creating suborders. MultiVendor or another plugin as I don't believe MultiOrders is something that comes by default with WooCommerce?

 Thanks!
