### ISSUE TITLE
Re-import vs re-subscribe after permanent delete error

### ISSUE THREAD

**Issue by regionstrauma** [ibericode/mailchimp-for-wordpress#673]
My website URL: thetraumapro.com/pips

### The issue
I am testing a MC4WP form on the page above. After successfully registering once using an email address, I permanently deleted the record from the associated MailChimp audience. If I register using another email address, no problem. But if I try to use the permanently deleted address again I get the "Oops something went wrong" error with the error log listing below.

Since that address was permanently deleted, I would think one could re-subscribe using the form.

### How can we reproduce this issue?
1. Register using one of your email addresses
2. Ask me to permanently delete you from the audience
3. Try to register again using the form

### Technical info
* WordPress version: 5.3.2
* Mailchimp for WordPress version: 4.7.4 / 4.8 Premium
* Error log:
[2020-02-08 11:10:45] ERROR: Form 5116 > Mailchimp API error: 400 Bad Request. Forgotten Email Not Subscribed. regi*********@gm***.com was permanently deleted and cannot be re-imported. The contact must re-subscribe to get back on the list.
Request: POST https://us8.api.mailchimp.com/3.0/lists/2262362539/members - {"status":"pending","email_address":"regi*********@gm***.com","interests":{},"merge_fields":{"FNAME":"michael","LNAME":"mcgonigal"},"email_type":"html","ip_signup":"73.228.147.160","tags":[]}
Response: 400 Bad Request - {"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"Forgotten Email Not Subscribed","status":400,"detail":"regi*********@gm***.com was permanently deleted and cannot be re-imported. The contact must re-subscribe to get back on the list.","instance":"d37365f7-3852-436d-8330-9080d848294d"}

**Comment by arnelap** [comment]
This is a limit created by MailChimp, they do not allow re-subscribing via the API/any plugin once a user unsubscribed or was deleted. 

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
