### ISSUE TITLE
Unable to update set of tags for an existing subscriber.

### ISSUE THREAD

**Issue by CTaylorGuitar** [ibericode/mailchimp-for-wordpress#674]
My website URL: https://christaylordeveloper.co.uk

### The issue
I am attempting to use the following to update the set of tags for an existing subscriber on a list;

```
$mc4wp = new MC4WP_MailChimp();

$args = array(
    'merge_fields' => array(
        'FNAME' => 'Jane',
        'LNAME' => 'Smith',
    ),
    'tags' => array( 'foo', 'bar' ),
    'interests' => array()
);

$mc4wp->list_subscribe( 'abcde12345', 'jane@example.com', $args, true, false );
```

When wp_remote_request( $url, $args ) is called $args["method"] = 'PATCH', $args["body"] contains the json encoded tags and the value of $url is of the form https://us12.api.mailchimp.com/3.0/lists/abcde12345/members/subscriber-hash.

Documentation for (what I assume is) the corresponding endpoint does not have tags listed amongst the request body parameters https://mailchimp.com/developer/reference/lists/list-members/#patch_/lists/-list_id-/members/-subscriber_hash-.

Should my call to list_subscribe above result in an update to the list of tags for this subscriber or have I mis-understood something?

### Technical info
* WordPress version: 5.2.3
* Mailchimp for WordPress version: 4.7.5

**Comment by dannyvankooten** [comment]
Hey @CTaylorGuitar,

Unfortuntely the Mailchimp API only accepts the `tags` property when the subscriber is not already on the list. So it will only add these tags if the susbcriber is a new subscriber, but when it already has the subscriber on the specified list then it will ignore the tags value.

**Comment by CTaylorGuitar** [comment]
Thank you for confirming this.
