### ISSUE TITLE
"The requested resource could not be found."

### ISSUE THREAD

**Issue by arnelap** [ibericode/mailchimp-for-wordpress#677]
MC support: contacts are being added to our system properly but their integration is instantly checking to see if the contact was added instead of relying on the successful API response when initially adding the contact.
So basically, the contact is added in one call, and for that initial call, we reply to the integration "________ contact was added"

Instead this integration is adding a contact and instantly making a GET API call to check our system for the contact that was added. This is leading to an error because our system needs a second to finish adding the contact.

**Comment by arnelap** [comment]
turns out we check if a contact exists BEFORE we submit it to handle update vs create. 
this should not show a resource not found message in our log.

**Comment by dannyvankooten** [comment]
>  this should not show a resource not found message in our log.

It doesn't right now, right? Just in Mailchimp's API log.
