### ISSUE TITLE
Klarna Checkout and Mailchimp checkbox at checkout

### ISSUE THREAD

**Issue by andresendo** [ibericode/mailchimp-for-wordpress#678]
My website URL: 

### The issue
Is it possible to show the mailchimp checkbox also at the checkout with klarna checkout?

### How can we reproduce this issue?
1. Klarna Checkout Plugin
2. Your Plugin
3. activate the checkout for woocommerce checkout

**Comment by arnelap** [comment]
I believe Klarna Checkout  is handled "off server" completely by Klarna so Wordpress and thus MailChimp for WP can't add anything to that page.
