### ISSUE TITLE
Broken link for more info on Woo integration

### ISSUE THREAD

**Issue by mih1dev** [ibericode/mailchimp-for-wordpress#683]
## The issue

hyperlink for Mailchimp's E-Commerce features opens a dead page.
MC4WP > Other:

..." read more about Mailchimp's E-Commerce features. "  (broken link: https://www.mc4wp.com/kb/what-is-ecommerce360/#utm_source=wp-plugin&utm_medium=mailchimp-for-wp&utm_campaign=other-settings-link)

* Mailchimp for WordPress version: 4.7.6

**Comment by dannyvankooten** [comment]
Thank you for the heads-up @mih1dev, much appreciated!

Fixed now.
