### ISSUE TITLE
Export MC4WP form?

### ISSUE THREAD

**Issue by regionstrauma** [ibericode/mailchimp-for-wordpress#684]
Is it possible to export a MC4WP form used on one website and import it on another? I’d like to use the same form data and html without having to rebuild the whole thing on the new site.

**Comment by dannyvankooten** [comment]
Hey @regionstrauma,

You might be able to use a WordPress exporter and importer tool for this (under Tools in your WP Admin) but I haven't yet been able to test this.

If it's just a single form then it might be quicker to just copy-paste the form HTML and any other settings where you're not using the default setting though.
