### ISSUE TITLE
The changes I make in the module do not apply

### ISSUE THREAD

**Issue by juan-cifuentes** [ibericode/mailchimp-for-wordpress#685]
My website URL: 

### The issue
Hello, I have a problem with set in form in MC4WP I had not had it before, but what happens is that I edit a part of the module, that is, I change the text of Subscribe to "Subscribirme", I record it and it indicates the message that was saved correctly, but when reviewing it reverts back to the default settings. And the most complex case is that when adding to the mailchimp list (which is already integrated) to which you must subscribe in the same way, I save and the changes are not applied. What should I do?

I already tried to uninstall and reinstall the plugin and it didn't fix it, I also tried a minor version but it didn't work either

### How can we reproduce this issue?
1. I make a change in the module configuration (set in form MC4WP)
2. I save the change, it tells me the message that if the changes were saved
3. Not applicable, redisplays default settings.

### Technical info
* WordPress version: 5.3.2
* Mailchimp for WordPress version: 4.7.6
* Relevant plugins in case of a bug: MC4WP

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
