### ISSUE TITLE
Can someone help with this? MailChimp plug in: selected options are missing visuals

### ISSUE THREAD

**Issue by GHeik** [ibericode/mailchimp-for-wordpress#688]
My website URL: https://herteamsuccess.com

### The issue
I have created a sign up form in WP using MC4WP. The appearance of the form is missing entry boxes (there is blank space under the fields such as "email" but no box for people to type in, unless they know to click below). In addition, the button is filled with theme color and no text shows to say "Sign Up". I have tested the different styles (basic, inherit from theme, etc), but nothing seems to fix this. It appears to be a bug? A similar form is working fine on another site of mine, so I am not sure what is wrong. I'd appreciate any direction or help! Thank you so much! An image of what's happening is below.

### How can we reproduce this issue?
1. go to https://herteamsuccess.com/contact and view the first contact form.
2.
3.

### Technical info
* WordPress version: 5.4.1
* Mailchimp for WordPress version: current

image file:
![form issue](https://user-images.githubusercontent.com/65035694/81430291-69e5c880-911c-11ea-9621-47a7f366cbdb.JPG)

* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
