### ISSUE TITLE
My screen goes up after submit click in input

### ISSUE THREAD

**Issue by omar93102** [ibericode/mailchimp-for-wordpress#689]
Hello, my newsletter form is in the footer and when I click on subscribe then my screen view goes to the middle of the website. is it a js, php or a plugin problem? does anyone knows how can I fix it? thank you!

![Captura de Pantalla 2020-05-13 a la(s) 09 03 50](https://user-images.githubusercontent.com/65243647/81822424-b2c0c700-94f8-11ea-8bec-3c27647adde0.jpg)

**Comment by DavideDelNista** [comment]
> Hello, my newsletter form is in the footer and when I click on subscribe then my screen view goes to the middle of the website. is it a js, php or a plugin problem? does anyone knows how can I fix it? thank you!
> 
> ![Captura de Pantalla 2020-05-13 a la(s) 09 03 50](https://user-images.githubusercontent.com/65243647/81822424-b2c0c700-94f8-11ea-8bec-3c27647adde0.jpg)

Same issue :-(

**Comment by arnelap** [comment]
possible related to your theme, or to lazy loading images. the plugin takes the location/height of the form on page load, so if the height is changed after loading the page this can mess things up. 

With the Premium add-on you can use the Ajax submission feature so you don't have this issue.

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
