### ISSUE TITLE
User Sync - Send Additional Fields Issue

### ISSUE THREAD

**Issue by rhyscreed** [ibericode/mailchimp-for-wordpress#690]
### The issue
This option use to work fine but now since the last update the drop down here won't show the fields I want to select inside MailChimp. It has since broken the link I use to use to send additional fields. 

Any help in solving this issue would be much appreciated. Is there an option to install a previous version to get it working again? This is the only option I can think of. 

I'm also receiving these two errors at the top of the page when I'm inside the plugin dashboard. Are these errors causing the issue?

### Technical info
* WordPress version: 5.4.1
* Mailchimp for WordPress version: 4.7.7
![MailChimp User Sync Issue](https://user-images.githubusercontent.com/65324099/81887098-c562fb00-95e1-11ea-8b50-aaab6e2e7eaa.PNG)

**Comment by rhyscreed** [comment]
These are the two errors, forgot to include them above:

Notice: Undefined property: stdClass::$merge_vars in /var/www/member/wp-content/plugins/mailchimp-sync/src/admin/class-manager.php on line 183

Warning: array_diff_key(): Argument #1 is not an array in /var/www/member/wp-content/plugins/mailchimp-sync/src/admin/class-manager.php on line 183

**Comment by arnelap** [comment]
We do no longer support the old UserSync addon. 
Instead we now have a completely rebuild version of UserSync features build into the Premium addon. 

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
