### ISSUE TITLE
Double Optin Issue

### ISSUE THREAD

**Issue by imdenise9** [ibericode/mailchimp-for-wordpress#692]
I installed MC4WP plugin recently on my wordpress. I linked it with mailchimp using API key on the very first day and it was working fine until today when I was trying another mailchimp plugin. I uninstalled that one but since then I found my MC4WP is not working again. I opted for double optin everywhere but its not working and redirecting me to another page. Fed up of trying the fault. Can anyone please guide me?

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
