### ISSUE TITLE
On mobile, the topbar makes anything "beneath" unclickable

### ISSUE THREAD

**Issue by PandaSekh** [ibericode/mailchimp-for-wordpress#693]
My website URL: https://www.artedellalettura.it/

### The issue
On mobile, when I try to use the menu or the search box they won't work. If I try to select them, it selects the topbar instead. On desktop it works fine and it works fine in Chrome simulation on a mobile device. This problem occurs both on iOS and Android

### How can we reproduce this issue?
1. Go on my website using a mobile phone
2. Try to use the hamburger menu or the search bar

### Technical info
* WordPress version: 5.4.2
* Mailchimp for WordPress version: 1.5.2
* Relevant plugins in case of a bug: Top Bar addon

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
