### ISSUE TITLE
Mailchimp checkbox for lists strangely lined up

### ISSUE THREAD

**Issue by MartineGoldenbeld** [ibericode/mailchimp-for-wordpress#694]
My website URL: https://www.mwagusicamp.com/

### The issue
Hi,
On my website, I added MC4WP plugin to the footer. It is a sign-up form with 2 lists. The checkboxes for the 2 lists are strangely lined up and looks confusing this way.
I did exactly the same on another website with the same theme and that looks fine. 

### How can we reproduce this issue?
1.
2.
3.

### Technical info
* WordPress version: 5.4.2.
* Mailchimp for WordPress version: 4.7.8.
* Relevant plugins in case of a bug:

Advanced iFrame

Contact Form 7

MailChimp Forms by MailMunchSettings

MC4WP: Mailchimp for WordPressSettings

Popup BuilderSettings

The7 ElementsDeactivate

The7 Slider Revolution

The7 Ultimate Addons for WPBakery Page Builder

The7 WPBakery Page BuilderSettings

UpdraftPlus - Backup

WhatsApp Chat

WhatsApp Chat PRO

Wordfence Security

WP Review Slider Pro (Premium)

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
