### ISSUE TITLE
Redirection is not working

### ISSUE THREAD

**Issue by Maxime40990** [ibericode/mailchimp-for-wordpress#697]
My website URL: https://satgana.com

### How can we reproduce this issue?
1.Go to Satgana.com
2.Go to Agora tab & sign up for the newsletter
3. The 0 is present on the configuration but the redirection is still working 

### Technical info
* WordPress version:5.2
* Mailchimp for WordPress version:Last one 
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp 

Please include a screenshot of MailChimp for WP > Form > Settings where we can see what you filled in the redirect on success url field. You can upload a screenshot to imgur.com or a similar site and share the link in your post to the Wordpress forum. 

Thanks!
