### ISSUE TITLE
Tag all new subscribers not working

### ISSUE THREAD

**Issue by scotnery** [ibericode/mailchimp-for-wordpress#699]
My website URL: 
https://www.scot.fun/damentals
### The issue
1. I went to MC4WP > Forms > Settings 
2. and added a new tag name "Blog Followers" 
3. this tag already exists in my Mailchimp account
4. i added a test email address using the TopBar
5. The subscriber was added, but without a tag.

note: i just added this tag to mailchimp today, if that matters
note: maybe you can't add tags with the topbar?

### Technical info
* WordPress version: 5.4.2
* Mailchimp for WordPress version: latest
* Relevant plugins in case of a bug: topbar

**Comment by arnelap** [comment]
Thank you for reporting the issue. This problem should be solved in the latest update.
