### ISSUE TITLE
Add-on: Send email campaign after new post.

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/mailchimp-for-wordpress#70]
While RSS-driven campaigns are great, they're not that suitable for private posts.

**Comment by krilor** [comment]
We are using the plugin and love it. We are also using a CPT for notifying our customers about interruptions in our services, and are currently looking at sending notification emails when new issues are posted (or removed).

What do you think an MVP of this feature would be?

I'm thinking that nice solution for us would be a generic API to send campaigns. That way plugin users can add_action to send email on save/update, without having to deal the MailChimps API directly. Baking such an API into the main plugin would be nice!

Could that be a nice starting point?

**Comment by krilor** [comment]
I actually took the time to dig though the code and see that api-v3 does have low-level methods to interact with the [Campaigns API](https://developer.mailchimp.com/documentation/mailchimp/reference/campaigns/).

Looking at the MC docs it seems like sending a campaign is a three-step process

1. Create (POST) a campaign
2. Edit (PUT) the content
3. Send (POST action)

Are you open to adding a method that chains these steps and handle (possible) errors?
If there is not time for you to add such a thing, is that something you would accept a PR for, or is that out of scope for what this plugin should contain?

I'm thinking a method on MC4WP_API_v3 along the lines of:

`public function create_and_send_campaign( array $campaign, array $content){}`

Where $campaign would be the data for the initial $campaign creation and and $content would be for the content update.

**Comment by krilor** [comment]
@dannyvankooten Any input?

**Comment by arnelap** [comment]
There is now a button to create a campaign from a post.
It's not fully automatic, it just prepares the campaign for you in MailChimp, you still need to manually send it out. This is a Premium feature. 

For competently automated setup you probably want to look into an RSS campaign.
