### ISSUE TITLE
Phone numbers not importing into Mailchimp

### ISSUE THREAD

**Issue by brightcompetitions** [ibericode/mailchimp-for-wordpress#700]
My website URL: www.brightcompetitions.co.uk

### Email address, address, f name l name, all importing into mailchimp but phone number isn't - how can this be resolved?
Thanks!

### Technical info
* WordPress version: 5.4.2
* Mailchimp for WordPress version: Version 4.8
* Relevant plugins in case of a bug:

**Comment by dannyvankooten** [comment]
Hello @brightcompetitions,

What is the type of the phone-number field in Mailchimp? Is this set to "phone" and if so, does changing it to a regular text-field solve the issue for you?

**Comment by brightcompetitions** [comment]
No it's not taking the phone number field from woocommerce. Can this be 
done?

**Comment by arnelap** [comment]
It can be done via  code snippet. Her eis an example:
https://github.com/ibericode/mc4wp-snippets/blob/master/integrations/woocommerce/send-billing-fields.php

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
