### ISSUE TITLE
Add feature to Logging section

### ISSUE THREAD

**Issue by askel45** [ibericode/mailchimp-for-wordpress#701]
My website URL: 

### The issue
Add a feature to stop logging altogether. I block PHP from running in my uploads folder. Or alternatively, provide an option to set optional logging file location.

### How can we reproduce this issue?
1.
2.
3.

### Technical info
* 5.4
* Mailchimp for WordPress version:
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
Logging can be disabled with this code snippet: 
https://github.com/ibericode/mc4wp-snippets/blob/master/misc/disable-log-debugging.php
