### ISSUE TITLE
Error message after updating to Wordpress 5.5

### ISSUE THREAD

**Issue by nikfox** [ibericode/mailchimp-for-wordpress#702]
My website URL: https://dronesurvey.asia/

### The issue: This is appearing at the top of every admin page inside my Wordpress site for https://dronesurvey.asia/

_Notice: register_rest_route was called incorrectly. The REST API route definition for mc4wp/v1/form is missing the required permission_callback argument. For REST API routes that are intended to be public, use __return_true as the permission callback. Please see Debugging in WordPress for more information. (This message was added in version 5.5.0.) in /home/nickfoxa/public_html/dronesurvey.asia/wp-includes/functions.php on line 5225_

### How can we reproduce this issue?
1.
2.
3.

### Technical info
* WordPress version: 5.5
* Mailchimp for WordPress version: 4.8
* Relevant plugins in case of a bug: 
### Begin System Info ###
Akismet Anti-Spam: 4.1.6
Better Analytics: 1.2.5
Contact Form 7: 5.2.1
Create And Assign Categories For Pages: 1.1
Display Categories Widget: 3.1
Engage Core: 3.4.3
Facebook for WooCommerce: 2.0.0
GDPR Cookie Consent: 1.8.9
Google Ads for WooCommerce: 1.0.4
Google XML Sitemaps: 4.1.1
Health Check & Troubleshooting: 1.4.4
Limit Login Attempts Reloaded: 2.15.1
Mailchimp for WooCommerce: 2.4.5
MC4WP: Mailchimp for WordPress: 4.8
Post Type Switcher: 3.2.0
Site Kit by Google: 1.13.1
Sliced Invoices: 3.8.11
Slider Revolution: 6.2.17
Vafpress Post Formats UI: 1.5
W3 Total Cache: 0.14.3
Widget Logic: 5.10.4
WooCommerce: 4.3.2
WooCommerce Breadcrumbs: 1.0.7
WooCommerce Stripe Gateway: 4.5.1
Woo Invoices: 1.2.1
WPBakery Page Builder: 6.2.0
Yoast Duplicate Post: 3.2.5

/////-- PHP Configuration

Safe Mode:                Disabled
Memory Limit:             256M
Upload Max Size:          50M
Post Max Size:            64M
Upload Max Filesize:      50M
Time Limit:               30
Max Input Vars:           1000
Display Errors:           On (1)

/////-- PHP Extensions

cURL:                     Supported
fsockopen:                Supported
SOAP Client:              Installed
Suhosin:                  Not Installed
Mbstring:                  Installed

**Comment by dannyvankooten** [comment]
Hello,

Thank you for the heads up - this is addressed in the next plugin update. Until then you can safely ignore the warning, it's just a notice to developers to ensure the code is correct (which it was, WordPress just wants it more explicitly as of version 5.5). :-) 

Thanks again!
