### ISSUE TITLE
503 Service Unavailable 

### ISSUE THREAD

**Issue by socialseed** [ibericode/mailchimp-for-wordpress#704]
My website URL: 

### The issue
Hello,

We are using a mailchimp plugin that we always do for every site. This site throws this error:

This means that the IP address that your hosting provider uses for outbound cURL connections made by PHP is blacklisted by the Akamai firewall. Akamai is the firewall Mailchimp and many other major websites use to protect their servers, which is why this is somewhat harder to fix.

Note that many hosting providers use shared IP addresses, meaning that your website IP is shared with a number of their users. It’s possible that another client of your hosting provider did something to get the IP blacklisted, completely out of your control.

After checking my IP address with https://mxtoolbox.com it shows it is not blocked.

### How can we reproduce this issue?
1.
![gdf](https://user-images.githubusercontent.com/69732628/90320322-34682c80-df0e-11ea-9e37-bb8341308c1b.JPG)

### Technical info
* WordPress version: 5.5
* Mailchimp for WordPress version: 4.8
* Relevant plugins in case of a bug: One page express companion

**Comment by arnelap** [comment]
That mens your hosting IP is blocked by MailChimp's Akamai firewall. 

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
