### ISSUE TITLE
plugin has stopped automatically syncing

### ISSUE THREAD

**Issue by perthupmarket** [ibericode/mailchimp-for-wordpress#709]
My website URL: www.perthupmarket.com.au

### How can we reproduce this issue?
1. Create a new user registration
2. Go to users and change user to subscriber
3. Go to mailchimp and search for email to see they are on the PUM retailer list 

### Technical info
* WordPress version: 5.4.2
* Mailchimp for WordPress version: 4.8.7
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
