### ISSUE TITLE
adding fields to MC4WP

### ISSUE THREAD

**Issue by Corsini1998** [ibericode/mailchimp-for-wordpress#711]
https://mysilvercoast.pt/newsletter: 
When i try to add fields on it always goes "403 Forbidden" .. Everything is fine but the additional fields.

How can we reproduce this issue?
1. Going to MC4WP, clicking on form
2. Choosing the fields to add.
3. Pressing save button goes to "403 Forbidden" "You don't have permission to access /wp-admin/admin.php on this server."

### Technical info
 Wordpress Version: 5.5.1
Mailchimp for wordpress ( v. 4.8.1 )

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
