### ISSUE TITLE
Not receiving some email notifications

### ISSUE THREAD

**Issue by cece-dex** [ibericode/mailchimp-for-wordpress#712]
My website URL: www.dexibit.com

### The issue
Hi there, we are receiving most email notifications when someone fills out a form but we are missing 2 or 3 out of every 10 form fill outs. We were made aware of this because we have the Mailchimp > Slack messages and we are still getting slack notifications for every form fill out. 

### How can we reproduce this issue?
1.
2.
3.

### Technical info
* WordPress version: 
* Mailchimp for WordPress version:
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp

If you use the Premium addon that has email notifications build in you can use the help button on the right bottom of any of the MC4WP settings screens to contact Premium support. 

Thanks!
