### ISSUE TITLE
Privacy checkbox doesn't work

### ISSUE THREAD

**Issue by realsaaw** [ibericode/mailchimp-for-wordpress#713]
My website URL: brainup.it

### The issue
When clients want to subscribe to my newsletter it isn't possible because yu can't verify checkbox.
If you try the work the HTML code it works.
How can I solve?

### How can we reproduce this issue?
1. try to open an html page with this code

<p>
    <label>Il tuo nome:</label>
    <input type="text" name="FNAME" placeholder="Metti il tuo nome." required="" /><p> 
</p>

<p>
	<label>Il tuo indirizzo email: </label>
	<input type="email" name="EMAIL" placeholder="Inserisci qui la tua migliore email." required="" /><p>
<label>
    <input name="AGREE_TO_TERMS" type="checkbox" value="1" required=""> <a href="https://www.brainup.it/privacy-policy-2/" target="_blank">Accetto la privacy policy.</a>
</label>

<p>
	<input type="submit" value="Iscriviti" />
</p>

2. The checkbox will work

### Technical info
* WordPress version: 5.5.3
* Mailchimp for WordPress version: 4.8.1

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
