### ISSUE TITLE
plugin does not work

### ISSUE THREAD

**Issue by ondrejvrtel** [ibericode/mailchimp-for-wordpress#714]
My website URL: 
https://amcon-de.de/

### The issue
The "forms" page does not show all forms, only new created forms.

### How can we reproduce this issue?
1.  See page /wp-admin/admin.php?page=mailchimp-for-wp-forms

### Technical info
* WordPress version:  5.5.3
* Mailchimp for WordPress version:  4.8.1    (pro version: 4.8.13)
* Relevant plugins in case of a bug: Contact Form 7, Flamingo
* This site is duplicate from https://amcon-eu.com/ with diferent licences.

**Comment by hchouhan** [comment]
Hey @ondrejvrtel,

Please contact us using the email provided on https://www.mc4wp.com/contact/. Make sure to email us using the same email address you had used to purchase our license.

**Comment by ondrejvrtel** [comment]
Hey Harish Chouhan,I will contact you by email at https://www.mc4wp.com/contact/. I have already sent about 5 emails. No answer yet.


(email using the same email address used to purchase our license... bellow)================-----Postoupil(a) Ondrej Vrtel/marco/cz dne 22.12.2020 10:47 -----Komu: support@mc4wp.comOd: Petr Marek/marco/czDatum: 21.12.2020 10:25Kopie: Ondrej Vrtel/marco/cz@marco-agencyPředmět: ask for help - plugin mc4wp doesn't workHello, I would like to ask you for help.We have applied plugin for contact forms to our clients web site and it doesn't work properly. System shows correct number of forms - 3 but we can't edit the forms and make changes there. We also tried erase the cash but it didn't help.Bellow I attached technical info.Thank you in advance for your support.Petr MarekS pozdravem / With kind regards 
Ondřej Vrtěl, Digital Specialist, Developer
T: +420 532 300 060 Direct T: +420 532 300 076 E: ondrej.vrtel@marco.eu ------------------------------------------------------------------------- 
MARCO reklamní agentura, spol. s 
r.o. Palackého třída 2203/186, 612 00 Brno, Czech Republic 
GPS: 49.2365372N, 16.5868267E Ukázat 
na mapě ------------------------------------------------------------------------- 
Web: www.marco.eu B2B Blog: www.marcob2b.cz LinkedIn: MARCO BBN Czech Republic 
Facebook: MARCO / BBN Czech Republic 
MARCO je členem BBN THE WORLD’S B2B AGENCY ------------------------------------------------------------------------- 


-----Harish Chouhan <notifications@github.com> napsal(a): -----Komu: ibericode/mailchimp-for-wordpress <mailchimp-for-wordpress@noreply.github.com>Od: Harish Chouhan <notifications@github.com>Datum: 20.12.2020 02:16Kopie: ondrejvrtel <ondrej.vrtel@marco.eu>, Mention <mention@noreply.github.com>Předmět: Re: [ibericode/mailchimp-for-wordpress] plugin does not work (#714)
Hey @ondrejvrtel,
Please contact us using the email provided on https://www.mc4wp.com/contact/. Make sure to email us using the same email address you had used to purchase our license.
