### ISSUE TITLE
Request: Defer CSS and JS

### ISSUE THREAD

**Issue by arnelap** [ibericode/mailchimp-for-wordpress#716]
Hi, you can improve the performance of the plugin by adding defer in the js and this css rule in the css files
https://developers.google.com/web/updates/2020/08/nic85#content-visibility
https://web.dev/content-visibility/

https://wordpress.org/support/topic/improve-perfomance-2/

**Comment by Camilo517** [comment]
And some js are not minified
It would also be good not to use jquery

**Comment by dannyvankooten** [comment]
Hello @Camilo517,

The plugin already doesn't use jQuery and all JavaScript files come with a minified version that is loaded if `SCRIPT_DEBUG` is not enabled. Can you point to the files which are not minified for you?

**Comment by Camilo517** [comment]
Hello @dannyvankooten 
Right, my fault
But you could add this to improve performance
https://web.dev/content-visibility/
