### ISSUE TITLE
Text before mail chimp form on footer (ON MOBILE)

### ISSUE THREAD

**Issue by alvaciomx** [ibericode/mailchimp-for-wordpress#718]
My website URL: 
https://alvaciomx.com/
### The issue
Text before mail chimp form on footer

### How can we reproduce this issue?
1. Look on the footer (on mobile) 
2. Where it says "NOTICIAS Y DESCUENTOS"
3. There is some text above the line to enter your address

### Technical info
* WordPress version:5.6.1
* Mailchimp for WordPress version:4.8.3
* Relevant plugins in case of a bug: -
![IMG_F2275A0BC4CB-1](https://user-images.githubusercontent.com/78765568/107290150-a89e0b80-6a2b-11eb-9401-32a38d89fac3.jpeg)

note: The issue happens on iPhone 11

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
