### ISSUE TITLE
WC4WP Dashboard

### ISSUE THREAD

**Issue by bongklim** [ibericode/mailchimp-for-wordpress#719]
My website URL: www.theprojectdefinition.com

### I am normally accessing to the MC4WP Dashboard for a new campaign generation through WP dashboard -> Mailchimp in MC4WP -> Click List Name -> Click Edit this list in Mailchimp -> MC4WP Dashboard. 

But, after reinstated database by Web Hosting company yesterday, Click Edit this list in Mailchimp -> Download file, no longer move to the MC4WP Dashboard.

It would be greatly appreciated if you could assist me to solve above problem.

BK Lim

### How can we reproduce this issue?
1. If you need any further information, please let me know.
2.
3.

### Technical info
* WordPress version: 5.6.2
* Mailchimp for WordPress version: 4.8.2
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
For me the Edit List link in MC4WP still directs to the Audience in de Mailchimp account. 

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
