### ISSUE TITLE
The form shows a success message but subscribers are not added to my list(s)

### ISSUE THREAD

**Issue by jstaerk** [ibericode/mailchimp-for-wordpress#720]
My website URL: https://quba-viewer.org/

### The issue

Like your FAQ entry 
https://wordpress.org/plugins/mailchimp-for-wp/#the%20form%20shows%20a%20success%20message%20but%20subscribers%20are%20not%20added%20to%20my%20list%28s%29%3F
my form shows success messages (and logs successes) but I added serveral email addresses two days ago already by form and I doubt mailchimp's SMTP servers are that slow, so far nobody received a single confirmation request mail: As recommended I left double opt in. 

The mailchimp dashboard does not show any subscriptions or subscription attempts, despite the log showing 

```
[2021-02-27 10:18:12] INFO: Form 347 > Successfully subscribed joch*********@gm***.com
[2021-02-27 10:20:00] INFO: Form 347 > Successfully subscribed joch*********@we*.de
[2021-02-27 10:20:17] INFO: Form 347 > Successfully subscribed wrgt******@er**.fe
[2021-02-27 10:32:46] INFO: Form 347 > Successfully subscribed jsta***@us******.de
```
### How can we reproduce this issue?
1. register a mailchimp account, 
2. copy the API key to the MC4WP settings
3. add a form with email address and submit button, 
4. changed the text on the submit button
5. leave double opt in 
6. embed the form
7. use the form

### Technical info
* WordPress version: 5.6.2
* Mailchimp for WordPress version: 4.8.3
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
I suppose double opt-in is turned on? The subscriber will only show after the opt-in is confirmed. 

We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
