### ISSUE TITLE
Admin's first name appearing in the confirmation email but not registered in mailchimp neither in the email provider norin wordpress

### ISSUE THREAD

**Issue by marco-ita** [ibericode/mailchimp-for-wordpress#722]
My website URL: 
https://bonuseristrutturazione.it

### The issue
As a user, when i subscribe, i receive an email confirmation message where the address of the sender it is showing a first name (the first name of the sender should not be there as there is no first name recorded in mailchimp neither in the email provider).
As the admin of the site, if i send an email through that same email address registered with mailchimp, as a receiver i don't see my first name but i see the correct information (the name of the site: Bonus e Ristrutturazione).

### How can we reproduce this issue?
1. subscribe on https://bonuseristrutturazione.it
2. check your confirmation email
3. you will see a first name "Marco" in the sender... that name should not be there.

### Technical info
* WordPress version: 5.6.2
* Mailchimp for WordPress version: Version 4.8.3
* Relevant plugins in case of a bug: Contact Form 7, Elementor, Jetpack by WordPress.com, MC4WP: Mailchimp for WordPress, MC4WP: Mailchimp Top Bar, MOJO Marketplace, OptinMonster, WooCommerce, WPForms Lite

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
