### ISSUE TITLE
Mailchimp form / WP integration

### ISSUE THREAD

**Issue by RikyWine89** [ibericode/mailchimp-for-wordpress#723]
My website URL: www.winetelling.it

### The issue
the botton "iscriviti" doesn't work.

### How can we reproduce this issue?
1.  complete the MC form at the bottom of the page
2. click the button "iscriviti"
3. the subscription on the newsletter is impossible

### Technical info
* WordPress version: WordPress 4.9
* Mailchimp for WordPress version: Versione 4.8.3
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
