### ISSUE TITLE
issue when signing up with already used email - page not found

### ISSUE THREAD

**Issue by elisa1993** [ibericode/mailchimp-for-wordpress#724]
My website URL: https://www.kvindernesbilmagasin.dk

### How can we reproduce this issue?
1. Sign up to the form. Once signed up, try again with same email. It shows "page not found" - it should lead to "you've already signed up with this email.
2.
3.

### Technical info
* WordPress version: 5.7
* Mailchimp for WordPress version: 4.8.3
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
