### ISSUE TITLE
Trying to get property 'post_type' of non-object

### ISSUE THREAD

**Issue by Beee4life** [ibericode/mailchimp-for-wordpress#725]
My website URL: dev

### The issue
I got a "Trying to get property 'post_type' of non-object" entry in my error logger after I activated the plugin MailChimp For Wordpress and tried to edit the form which is used.

### How can we reproduce this issue?
1. Install Mailchimp for wordpress
2. Add an API key
3. Edit the HTML for the form to use
4. The error shows in the preview pane if WP_DEBUG_DISPLAY = true (otherwise in the logger)

### Technical info
* WordPress version:5.7
* Mailchimp for WordPress version:
* Relevant plugins in case of a bug: WooCommerce (latest)

The function (in Wordpress) where the error occurs is
```
public function is_singular( $post_types = '' ) {
    if ( empty( $post_types ) || ! $this->is_singular ) {
        return (bool) $this->is_singular;
    }
    var_dump(is_singular());
    var_dump(is_admin());
    $post_obj = $this->get_queried_object();
    
    return in_array( $post_obj->post_type, (array) $post_types, true );
}
```

Both var_dumps are added by me. If I dump `is_singular()` it shows true (in the admin on the MC4WP settings page) and `is_admin()` shows false.

As reported [here](https://github.com/woocommerce/woocommerce/issues/29400).

**Comment by dannyvankooten** [comment]
Hello @Beee4life,

Can you please share the following information?

- Your active theme
- Your active plugins
- Any other snippets in your `functions.php` file, especially one that use the `wp_head` action hook or call `is_singular`?

**Comment by Beee4life** [comment]
It's a custom theme, but I tested with twentytelve and only Woocommerce and MC4WP active.

My custom theme is without any hooks to `wp_head`. There is only 1 `is_singular` instance which is in `singular.php` so not affecting the admin.

These are the plugins installed (with composer)
```
"wpackagist-plugin/broken-link-checker":              "^1.0",
"wpackagist-plugin/classic-editor":                   "^1.4",
"wpackagist-plugin/cookie-notice":                    "^2.0",
"wpackagist-plugin/disable-comments":                 "^2.0",
"wpackagist-plugin/disable-json-api":                 "^1.0",
"wpackagist-plugin/mailchimp-for-wp":                 "^4.0",
"wpackagist-plugin/mollie-payments-for-woocommerce":  "^6.0",
"wpackagist-plugin/redirection":                      "^5.0",
"wpackagist-plugin/regenerate-thumbnails":            "^3.0",
"wpackagist-plugin/side-cart-woocommerce":            "^2.0",
"wpackagist-plugin/ti-woocommerce-wishlist":          "^1.0",
"wpackagist-plugin/timber-library":                   "^1.0",
"wpackagist-plugin/user-role-editor":                 "^4.0",
"wpackagist-plugin/w3-total-cache":                   "^2.0.0",
"wpackagist-plugin/wordpress-seo":                    "^16.0",
"wpackagist-plugin/woocommerce":                      "^5.0",
"wpackagist-plugin/woo-postnl":                       "^4.0",
"wpackagist-plugin/woo-preview-emails":               "^1.0",
```

**Comment by arnelap** [comment]
can you please send us a link to this issue on support at mc4wp .com? Thanks
