### ISSUE TITLE
Dismissing review notice gives error

### ISSUE THREAD

**Issue by Beee4life** [ibericode/mailchimp-for-wordpress#726]
When I click the dismiss button in the admin to hide the notice "You've been using..." it goes to an invalid link, which is expired.

The reason might be because there are 2 elements with the ID #nonce.

![Screenshot 2021-06-22 at 21 59 05](https://user-images.githubusercontent.com/4508731/122991247-188eac00-d3a5-11eb-92d9-de076a4750f5.png)

1 is used to empty the log (other-settings.php line 134) and 1 for (I think the general options form) but don't have time to look into it...

Also (according to phpstorm) there seems to be an undefined var in other-settings.php on line 80 ($opts).

**Comment by dannyvankooten** [comment]
Hey @Beee4life,

Great catch! This is fixed in 1324b22452155c771a4d1215704ef4c098772b0b. Thank you for bringing it to our attention.
