### ISSUE TITLE
Getting email notification many times

### ISSUE THREAD

**Issue by riklewis** [ibericode/mailchimp-for-wordpress#727]
My website URL: https://londonartweek.co.uk

### The issue
When a user fills in a form they are successfully added to the list and the notification email is sent to my client as expected.  However, this email can arrive anywhere between 1 and 8 times, seemingly randomly.  Here's a screenshot, with the name/email redacted of course, but they're identical...

![image](https://user-images.githubusercontent.com/991173/123857981-e50acf00-d91a-11eb-902f-d24c593fcddf.png)

### How can we reproduce this issue?
1. Setup form with email notification
2. Submit form
3. See multiple email notifications

I really don't think I've done anything odd to cause this.  I have added a "mc4wp_form_subscribed" action, could that be a factor?

### Technical info
* WordPress version: 5.7.2
* Mailchimp for WordPress version: 4.8.6
* Relevant plugins in case of a bug: N/A

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
