### ISSUE TITLE
General Issue: Implementation of Google Recaptcha hurts web vitals score of pages using the plugin

### ISSUE THREAD

**Issue by martinWelte** [ibericode/mailchimp-for-wordpress#728]
My website URL: -

### The issue

- Google Recaptcha gets Inlined in Footer, which makes it rather unpleasant to add async or defer it. Since Google web vitals punish it harshly this should be eighter offset by default, or the script enqued in a wordpress fashion via wp_enque_script. 
Also the following inline script could be added with a wp_localize_script function, otherwise it does suffer the same issues.

### How can we reproduce this issue?

- having forms with recaptcha activated i guess.

### Technical info

* WordPress version: -
* Mailchimp for WordPress version: 4.8.6
* Relevant plugins in case of a bug:-

### File wich contains the issue

* mailchimp-for-wp/includes/forms/class-google-recaptcha.php:49-98

![Bildschirmfoto 2021-06-30 um 16 58 39](https://user-images.githubusercontent.com/2704997/123983860-7a15d280-d9c4-11eb-818c-ab1b87e61adb.jpg)

**Comment by martinWelte** [comment]
Let me know what you think. I could add a PR if there are no resources available to fix it.

**Comment by arnelap** [comment]
I recommend using WpBruiser. We decided to move away from any build in recatcha in MC4WP.

**Comment by martinWelte** [comment]
@arnelap thanks for the information, what about the code though? will you remove it, or will i have to hack it?
