### ISSUE TITLE
Submit Button Isn't Themed Even Though Setting Is Selected - Plz Help

### ISSUE THREAD

**Issue by JennMcLane** [ibericode/mailchimp-for-wordpress#729]
My website URL: https://thelazybubble.com/

### I am using Mailchimp for WP and my button to my mailing list form isn't designed with my theme. The rest of the form looks beautiful, however, the submit button is UGLY!

**Screenshots included**
<img width="1440" alt="Screen Shot 2021-07-02 at 7 22 48 AM" src="https://user-images.githubusercontent.com/86833445/124267509-59ee2c80-db06-11eb-97f0-74d6d5578af6.png">
<img width="1185" alt="Screen Shot 2021-07-02 at 7 21 42 AM" src="https://user-images.githubusercontent.com/86833445/124267512-5a86c300-db06-11eb-8896-2e517c8e6752.png">
<img width="1099" alt="Screen Shot 2021-07-02 at 7 21 48 AM" src="https://user-images.githubusercontent.com/86833445/124267514-5a86c300-db06-11eb-84ce-4e976d85e89e.png">

### How can we reproduce this issue?
1. Go to https://thelazybubble.com/
2. School down to 'Join Our Mailing List
3. Bask in the gloriousness of the ugly button!

### Technical info
* WordPress version: 5.7.2
* Mailchimp for WordPress version: Version 5.7.2
* Relevant plugins in case of a bug: Elementor Pro, Laurent 2.5 (WP theme)

**Comment by larsschafer** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
