### ISSUE TITLE
Submit Button is in the wrong place, overlaying the form fields

### ISSUE THREAD

**Issue by drikarx** [ibericode/mailchimp-for-wordpress#731]
My website URL: https://thesavingnerd.com

### The issue
The form buttons show up in the wrong place.

### How can we reproduce this issue?
1. Using the "Mailchimp for WordPress" create a form
2. The submit/subscribe button is in the wrong place. It is overlaying the form fields instead of being placed after the form fields in the end of the form.

### Technical info
* WordPress version: 5.8
* Mailchimp for WordPress version: 4.8.6
* Relevant plugins in case of a bug:

![mailchimp_bug](https://user-images.githubusercontent.com/36480528/129454910-8124348b-8d4c-4437-8fc4-f24a74f33e7a.PNG)

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
