### ISSUE TITLE
MC4WP newsletter form does not work

### ISSUE THREAD

**Issue by BernieSamui** [ibericode/mailchimp-for-wordpress#732]
My website URL: https://mwf-institute.org/

### The issue
Hello, I need your help please. Subscription to the newsletter does not work. The error message that something went wrong appears.
The MP4WC extension is well connected to Mailchimp via API.
Here is the error code from the log in your extension:
[2021-08-21 07:25:32] ERROR: Form 228 > Mailchimp API error: 404 Not Found. Resource Not Found. The requested resource could not be found.
Request:
POST https://us6.api.mailchimp.com/3.0/lists/a328b7e698/members
{"status":"pending","email_address":"fbw.***@gm***.com","interests":{},"merge_fields":{},"email_type":"html","ip_signup":"134.196.73.0","tags":[]}
Response:
404 Not Found
{"type":"https://mailchimp.com/developer/marketing/docs/errors/","title":"Resource Not Found","status":404,"detail":"The requested resource could not be found.","instance":"f175d9fa-676c-91a2-6ae5-cebed9bad47d"}

### How can we reproduce this issue?
1. enter your email on the home page (middle) or in the footer of the site.
2.
3.

### Technical info
* WordPress version: 5.8
* Mailchimp for WordPress version: Version 4.8.6
* Relevant plugins in case of a bug: MCW4C

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
