### ISSUE TITLE
Form not redirecting

### ISSUE THREAD

**Issue by Jerconjake** [ibericode/mailchimp-for-wordpress#736]
My website URL: revolutionboutique.ca

### The issue

The form is set to redirect to a thank you page but it does not

### How can we reproduce this issue?
1. go here: https://revolutionboutique.ca/signup-discount/
2.
3.

### Technical info
* WordPress version: latest
* Mailchimp for WordPress version: latest
* Relevant plugins in case of a bug: shouldn't be any

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
