### ISSUE TITLE
Reports not working on multisite subsites. (Mailchimp for WordPress Premium 4.8.16)

### ISSUE THREAD

**Issue by gregbob13** [ibericode/mailchimp-for-wordpress#737]
My website URL:  I've tested this on a fresh local multisite install with no other plugins using Twenty Twenty One theme to confirm the issue. First noticed on a client's live multisite.

### The issue
Reporting works well on primary site (db prefix wp_) but does not work on subsites (db prefix wp_2, etc.).

### How can we reproduce this issue?
1. Create a new multisite environment and add one subsite.
2. Install and configure mc4wp & mc4wp premium on both primary and subsite
3. Create a form on each site, sign up for each form (using different email addresses, of course), check reports for each site. You'll see that reporting works well for the primary site (wp_) but not the subsite (wp_2)

### Technical info
* WordPress version: 5.8.1
* Mailchimp for WordPress version:  MC4WP: Mailchimp for WordPress 4.8.6 and MC4WP: Mailchimp for WordPress Premium 4.8.16
* Relevant plugins in case of a bug: Tested on fresh install with no other plugins running.

Thank you.

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
