### ISSUE TITLE
Spinning wheel when clients try to hit the submit button

### ISSUE THREAD

**Issue by candaceweir** [ibericode/mailchimp-for-wordpress#738]
My website URL: www.candaceweir.com/contact

### The issue
Spinning wheel when clients try to hit the submit button. I think this is happening from their mobile devices.

### How can we reproduce this issue?
1. Fix it
2.
3.

### Technical info
* WordPress version:
* Mailchimp for WordPress version:
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wor dpress.org/support/plugin/mailchimp-for-wp
