### ISSUE TITLE
error in reiceving email 

### ISSUE THREAD

**Issue by lcox0004** [ibericode/mailchimp-for-wordpress#739]
My website URL: sentonesim.org

### The issue

[2021-11-14 08:15:57] WARNING: Contact Form 7 > Unable to find EMAIL field.

### How can we reproduce this issue?
1. no new emails are added to mail chimp list, even though it seems sucessful
2.
3.

### Technical info
* WordPress version: lastest
* Mailchimp for WordPress version: lastest
* Relevant plugins in case of a bug: Contact 7 form

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordp ress.org/support/plugin/mailchimp-for-wp
