### ISSUE TITLE
Visitors to site can't subscribe to Newsletter

### ISSUE THREAD

**Issue by AndersHaag** [ibericode/mailchimp-for-wordpress#741]
My website URL: https://www.ostravatterbranterna.se

### How can we reproduce this issue?
1. Go to site
2. On first page, under the heading "Få vårt nyhetsbrev", write your e-mail adress, using a dot com adress.
3. Push the button "prenumerera".

### Technical info
* WordPress version: 5.8.2 with Divi
* Mailchimp for WordPress version: 4.8.6
* Relevant plugins in case of a bug: Don't know

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp

Don't forget the include the full error message you can see it in the log under MC4WP > Other.
