### ISSUE TITLE
Showing wrong error message? General vs. Already on list 

### ISSUE THREAD

**Issue by Netzie** [ibericode/mailchimp-for-wordpress#742]
My website URL:  sensitiv.dk

### The issue
When a user wants to subscribe and the email is already on the list and unsubscribed. The general error message shows.
But this is a "combo" of Already on the list and unsubscribed

### How can we reproduce this issue?
1. Pro user :)
2. Unsubscribe
3. try to get back on

### Technical info
* WordPress version: 5.8.2
* Mailchimp for WordPress version:4.8.6
* Relevant plugins in case of a bug: PRO 4.8.20

**Comment by hchouhan** [comment]
Hey @Netzie,

For support related issues, please email us at support@mc4wp.com.

Regarding the issue you mentioned, the error we show depends on the data returned by MailChimp's API and for the user who has already unsubscribed, there is unique

**Comment by Netzie** [comment]
@hchouhan - Why the unfriendly "close" ??

**Comment by hchouhan** [comment]
Hey @Netzie,

I apologize for that. We created another ticket at https://github.com/ibericode/mailchimp-for-wordpress/issues/743.

Currently, the error response is the same for different errors and hence not possible to show custom messages for each situation. We will look into the API again but for now, we plan to include a link to the error log in the frontend for admin users as they are usually who come across such issues during tests.

**Comment by Netzie** [comment]
Ok - All forgiven 
Happy New Year

I am sure you are aware of the "General Error msg" is shown to the user and they create cases/tickets... :-( 
It is a rare case that a person wants to re-seubscribe... but I'm sure you can find a quick-fix :-)

**Comment by hchouhan** [comment]
Happy New year to you too :)

I would recommend placing a link to the subscription page on MailChimp inside the general error message. This will allow your user to click on it and subscribe and for now this is the only solution that could be useful for the end user.

**Comment by Netzie** [comment]
Hi 
Thanks - I did add the link and did some more testing. The lead / subscriber was imported from another list in 2017 but unsubscribed short after. She couldn't resubscribe... When I test now with a "normal" subscribe via the form on the site. I can unsubscribe ... and then be entering my email again : subscribe with no probs!
So there must be a "flag" on imported leads or a time issue? - Any way with the link in the error message ... All should be ok!
Thanks for quick reply(s) 👍
