### ISSUE TITLE
Incorrect rendering of subscription text when it is places before Submit button

### ISSUE THREAD

**Issue by Dimensionone** [ibericode/mailchimp-for-wordpress#744]
My website URL: 

### The issue
Using version 4.8.6. When I place the checkbox for subscribing to the newsletter prior the submit button, it is incorrectly rendered. When I put it after e-mail address, it is displayed correctly.
See the attached screenshots:

![Location under email - correct](https://user-images.githubusercontent.com/19395771/148699761-5762e710-2b82-4d2f-854b-cac8bbbb1aeb.jpg)

![image](https://user-images.githubusercontent.com/19395771/148699916-0a6bdea9-1350-4b0d-8ab5-a9c466fd08f1.png)

### How can we reproduce this issue?
1. MC4WP - Integrations - Woocommerce Checkout - select position Before Submit button
2. Refresh checkout page - the checkbox appear there but it is incorrectly rendered
3.

### Technical info
* WordPress version: 5.8.3
* Mailchimp for WordPress version: 4.8.6. 
* Relevant plugins in case of a bug: Woofunnels, but the issue is reproducible also with a standard woocommerce checkout

**Comment by arnelap** [comment]
We only use git for development related issues. For free support please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
