### ISSUE TITLE
Translation fail in error message

### ISSUE THREAD

**Issue by tomas73larsson** [ibericode/mailchimp-for-wordpress#752]
My website URL: sundbyberg.replaydesign.se

### The issue
error message at required field, not translating into Swedish

### How can we reproduce this issue?
1. Klick the 'Prenumerera' button
2.
3.

### Technical info
* WordPress version:6.0.2
* Mailchimp for WordPress version: 4.8.10
* Relevant plugins in case of a bug: none

**Comment by dannyvankooten** [comment]
Hello @tomas73larsson,

The plugin uses HTML5 validation first (before performing its server-side validation) and in your case, your browser language is probably set to English. HTML5 validation will use the language of your browser.

If you want, you can [disable HTML5 validation using this code snippet](https://github.com/ibericode/mailchimp-for-wordpress/blob/master/sample-code-snippets/forms/disable-html5-form-validation.md).

Hope that helps!
