### ISSUE TITLE
Indicate Woocommerce HPOS compatibility

### ISSUE THREAD

**Issue by arnelap** [ibericode/mailchimp-for-wordpress#755]
See https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book#declaring-extension-incompatibility

**Comment by arnelap** [comment]
we do have update_post_meta($order_id, 'mc_cid', $campaign_id); 
the campaign tracking was the only post meta i could find (so far)

**Comment by marcusforsberg** [comment]
@arnelap Is HPOS compatibilty on your roadmap or would you accept a PR that fixes it?

**Comment by arnelap** [comment]
https://secure.helpscout.net/conversation/2538422334/38353?viewId=253120

**Comment by dannyvankooten** [comment]
@marcusforsberg Terribly sorry for the late reply, but we'll be adding support for WooCommerce HPOS over the next few weeks.
