### ISSUE TITLE
Email Subscribe form error

### ISSUE THREAD

**Issue by suzionthemove** [ibericode/mailchimp-for-wordpress#756]
My website URL:  suzionthemove.com

### The issue no number indicated
<img width="1134" alt="Screen Shot 2023-01-01 at 2 35 38 PM" src="https://user-images.githubusercontent.com/121774519/210187727-ea9579e6-9c1a-425d-a442-6a1983a10a42.png">

There was an error subscribing. Please try again.

### How can we reproduce this issue?
1. Succesful subscription to email
2.
3.

### Technical info
* WordPress version:
* Mailchimp for WordPress version:
* Relevant plugins in case of a bug:

**Comment by arnelap** [comment]
Please update the MC4WP plugin to the latest version first. If that doesn't solve the issue. please see https://www.mc4wp.com/kb/fix-the-oops-something-went-wrong-error/

If you can still not solve the error after reading that kb article, please let me know the error you see in the log under MC4WP > Other.

Hope that helps. If you have any questions please use the Wordpress forums for support, we use git only for bugs and code related issues.

**Comment by suzionthemove** [comment]
Hi,

I did not see any issues under the log & no updates are needed on the plug
in. Looks like I am still getting the same error while testing out the
subscribe button.

Please let me know if there's anything else I can do to fix this.
