### ISSUE TITLE
Request: Add $postid to comment form integration

### ISSUE THREAD

**Issue by arnelap** [ibericode/mailchimp-for-wordpress#761]
That way someone can pull in for example that category of a post and set some tags based on that.

**Comment by dannyvankooten** [comment]
The `mc4wp_integration_wp-comment-form_data` hook already receives the comment ID as a parameter. This comment ID can be used to retrieve any related information on the comment, as follows:

```php
add_action( 'mc4wp_integration_wp-comment-form_data', function( $data, $comment_id ) {
    $comment = get_comment( $comment_id );
    $post_id = $comment->comment_post_ID;
    // .... etc 
}, 10, 2);
```
