### ISSUE TITLE
Code shows instead of form

### ISSUE THREAD

**Issue by nordink** [ibericode/mailchimp-for-wordpress#763]
My website URL:  cookingontheweekends.com

I've used MC4WP on my site for years. I didn't change anything, but the shortcode is now showing code in the sidebar instead of the optin form?

<img width="1440" alt="Screen Shot 2023-03-31 at 09 28 57" src="https://user-images.githubusercontent.com/3420003/229177692-9db2f741-8e6e-4b60-bad4-0c76ca40be92.png">

**Comment by hchouhan** [comment]
Hello,

Please note that this platform is for reporting bugs. For support, please contact us at support@mc4wp.com
