### ISSUE TITLE
Error in the widget footer columns

### ISSUE THREAD

**Issue by kepo123** [ibericode/mailchimp-for-wordpress#764]
My website URL: 

### The issue
When I add a MC4WP form in the footer it shows it with some error or piece of code right above the field name label. I haven't added the form in the footer so far, so I don't know if the problem existed before. Even though the problem is entirely visual, it makes a bad impression to our customers. There are no problems in the other pages where the form is used, it happen only in the footer. There are no problems in the functionality either.

### How can we reproduce this issue?
1. _Go to the widgets page._
2. _Add the MC4WP form in the Footer Column 1 area._
3. View the changes

### Technical info
* **WordPress version:** 6.2
* **Mailchimp for WordPress version:** 4.9.3
* **Relevant plugins in case of a bug:** _The theme I use is WoodMart. I haven't added any new plugins in a while, and that was actually the only change I made for the whole day. I just added the MC4WP form to the footer via the widget feature._

![image](https://user-images.githubusercontent.com/17118210/233818349-25c03f19-9797-47d8-a4f1-51e25c5d1ab4.png)

**Comment by arnelap** [comment]
it might be an issue with your theme. 
you can work around it by using a text widget with a shortcode to the form, instead of using the MC4WP widget directly. Does that solve the issue for you?
