### ISSUE TITLE
"There has been a critical error on this website" when opening MC4WP form option

### ISSUE THREAD

**Issue by cyprianongori** [ibericode/mailchimp-for-wordpress#768]
My website URL: https://www.portsacco.co.ke

### The issue
Plugin throws an error when I open forms option.

### How can we reproduce this issue?
1. Click on the forms option on the MC4WP plugin

### Technical info
* WordPress version: 6.2
* Mailchimp for WordPress version: 4.9.4
* Relevant plugins in case of a bug: Be Custom

**Comment by arnelap** [comment]
Please contact us for support on support at mc4wp.com Thanks
