### ISSUE TITLE
Country field not working

### ISSUE THREAD

**Issue by jcoonrod** [ibericode/mailchimp-for-wordpress#774]
My website URL: mcld.org/subscribe

### The issue

Country field not making it into Mailchimp record
### How can we reproduce this issue?
1. Fill in the form including selecting a country.
2. Submit the form
3. View the record in Mailchimp - no country entered.

### Technical info
* WordPress version: 6.4.2
* Mailchimp for WordPress version: 4.9.11
* Relevant plugins in case of a bug: n/a

**Comment by arnelap** [comment]
I do not recommend using the field of type "address" in Mailchimp. It has very strict validation and needs to be a full and complete address with state and country and everything or else Mailchimp will just drop the whole address. So you can't only send the postal code.

Better to use normal text field for the data you want to collect, then you won't have this issue.

We only use git for development related issues. 

For free support related to the Mailchimp for Wordpress plugin, please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
