### ISSUE TITLE
How to enable ReCaptcha

### ISSUE THREAD

**Issue by kush1960** [ibericode/mailchimp-for-wordpress#778]
We've getting some spam submissions to our Mailchimp signup form and need to enable reCaptcha.
I've had a good dig around but can't find anything that seems to be supported in 2024.
What is the recommended approach for this?
I tried https://wordpress.org/plugins/google-captcha/ but MC4WC isn't in it's list of supported plugins.
I use the premium version of the plugin.
Thanks.

**Comment by arnelap** [comment]
We now have a new Captcha integration you can find under MC4WP > Integrations. 

We only use git for development related issues. 

For free support related to the Mailchimp for Wordpress plugin, please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
