### ISSUE TITLE
Add-on: Email Verification

### ISSUE THREAD

**Issue by dannyvankooten** [ibericode/mailchimp-for-wordpress#78]
http://quickemailverification.com/

**Comment by dannyvankooten** [comment]
Notify Xavier (who came with the initial idea) once we actually do this (if ever): https://secure.helpscout.net/conversation/71808777/1689/

**Comment by arnelap** [comment]
Duplicate of https://github.com/ibericode/mailchimp-for-wordpress/issues/160
