### ISSUE TITLE
Form check insufficient

### ISSUE THREAD

**Issue by joombler** [ibericode/mailchimp-for-wordpress#780]
I recently have been spammed through a form that I created with MC4WP, where the spammer registered with same first name and last name and email address (form7). Looks like reCaptcha didn't work.
Can you tell how I can (i) add an interactive questions at the end of the form and (ii) check if first name and last name are the same so that this kind of spam is blocked? Your expertise is appreciated.
Thanks, Jos

**Comment by arnelap** [comment]
If it was submitted via ContactForm 7 then it owuld be best to ask them for support. 
If it's directly via a MC4WP form, we now have a new Captcha integration you can find under MC4WP > Integrations. 

We only use git for development related issues. 

For free support related to the Mailchimp for Wordpress plugin, please create a ticket at https://wordpress.org/support/plugin/mailchimp-for-wp
