### ISSUE TITLE
Subscriber Count not updating

### ISSUE THREAD

**Issue by bryandoi** [ibericode/mailchimp-for-wordpress#781]
My website URL: 

### The issue
The subscriber count is not updating; I already registered 4 emails to test the subscription Mailchimp button.

### How can we reproduce this issue?
1. 
2.
3.

### Technical info
* WordPress version: 6.5.4
* Mailchimp for WordPress version: 4.9.13
* Relevant plugins in case of a bug:  MC4WP

**Comment by dannyvankooten** [comment]
Hello @bryandoi,

The subscriber count is only updated once every 24 hours, in order not to slow down your website. You can manually refresh it quicker than that by going into your WP Admin > Mailchimp for WP settings page and clicking the "Renew lists cache" button.

Hope that clarifies! 
Danny
